### ISSUE TITLE
No .ovpn files getting downloaded

### ISSUE THREAD

**Issue by aneng64** [Zomboided/service.vpn.manager#100]
Hi.  Trying to get VPN Manager to work on a fresh install of OSMC on a RPi 3.  VPN provider is IPVanish.

Openvpn works fine when started from command line.  Symptoms are that it appears to not be downloading any of the .ovpn files required for IPVanish (not tested it with any others though).  Therefore, it never populates the vpn server list and just sits there forever.  I have tried manually copying the relevant .ovpn files into /home/osmc/.kodi/addons/service.vpn.manager/IPVanish and this makes the list populate but it will not connect - complaining that it cannot find the .crt file for IPVanish (even though it is in that folder).

Log file: https://pastebin.com/4jfDAbQq

Many thanks !

**Comment by Zomboided** [comment]
Fixed in 4.1.3

**Comment by aneng64** [comment]
4.1.3 is not in https://github.com/Zomboided/repository.zomboided.plugins/releases/download/1.0.0/repository.zomboided.plugins-1.0.0.zip

Is there a newer repository I can use ?

**Comment by Zomboided** [comment]
Wait for it to update
