### ISSUE TITLE
No VPN connections available (no .ovpn files)

### ISSUE THREAD

**Issue by guigros** [Zomboided/service.vpn.manager#103]
Hi there,

I ran into an issue with VPN manager. I'm using Kodi 17 on a raspberry. (OS : raspbian)

Add-on installation goes well but then I want to configure the add-on and I can't set the first connection thus I cannot "validate" the connection.

When I click on "FIRST VPN CONNECTION..." a pop-up saying "The openvpn executable isn't working....".

I started troubleshooting : 
- openvpn is installed on my distrib and fully functionnal when I start it by cmd line
- when I go under /home/user/.kodi/addons/service.vpn.manager/AirVPN/ there is no .ovpn file and it's the same for all providers fodlers
- I tried to manually add an .ovpn file but still not working

Anyone who could help me ?
Thanks

**Comment by Zomboided** [comment]
Look at the install page on the wiki, and the debug page.  There are
options to use sudo.  If sudo is needed on raspbian, it's probably that.
Otherwise it might be related to the log location.  There's an option to
use the same location as for the kodi log.

**Comment by guigros** [comment]
I did check the install page on wiki

"Enable Debug for just vpn manager" is enabled
"Use sudo with openvpn and killall" is set to "Always"
"Always use Kodi log directory for openvpn log" is enabled

and this the Kodi log : 
09:29:09.685 T:1653793536    NONE: VPN Mgr Debug: Requested update to service process via settings monitor
09:29:09.693 T:1653793536    NONE: VPN Mgr Debug: Update service requested KodiMonitor
09:29:09.920 T:1524556544 WARNING: CPythonInvoker(9): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
09:29:10.559 T:1524556544    NONE: VPN Mgr Debug: Entered connect.py with parameter 1
09:29:10.576 T:1524556544    NONE: VPN Mgr Debug: Checking openvpn can be run
09:29:10.593 T:1524556544    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
09:29:10.671 T:1524556544  NOTICE: VPN Mgr : **(platform.py) Testing openvpn with : sudo /usr/sbin/openvpn > /home/kodi/.kodi/temp/openvpn.log &**
09:29:11.739 T:1524556544   ERROR: VPN Mgr : (platform.py) Ran openvpn command and it failed
09:29:11.751 T:1524556544  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
09:29:11.751 T:1524556544  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end
09:29:11.925 T:1653793536    NONE: VPN Mgr Debug: VPN monitor service was requested to run an update
09:29:11.933 T:1653793536    NONE: VPN Mgr Debug: Update primary VPNs from settings
09:29:11.946 T:1653793536    NONE: VPN Mgr Debug: Found no VPNs, setup is invalid
09:29:11.953 T:1653793536    NONE: VPN Mgr Debug: Flag lists have changed
09:29:11.963 T:1653793536    NONE: VPN Mgr Debug: Checking if a timer or file reboot is required
09:29:19.820 T:1524556544    NONE: VPN Mgr Debug: Exit connect.py

If the add-on is trying to launch "sudo openvpn" it won't start. I need a config file but as I said before there is no .ovpn file under my provider folder.

**Comment by Zomboided** [comment]
You don't need an ovpn file, you need to solve the problem that the command
won't run.  If the command doesn't run, and spit out the info you get when
you run it without an ovpn file then the addon won't work when it comes to
using an ovpn file (which will appear later).  The addon is telling you
what it needs to be able to do with the line you've highlighted in bold.

**Comment by guigros** [comment]
Sorry but I don't get what you mean by "**_If the command doesn't run, and spit out the info you get when
you run it without an ovpn file then the addon won't work when it comes to
using an ovpn file (which will appear later)._**"

I have no log into the openvpn log file so how can I know what is the problem with the command ?

**Comment by Zomboided** [comment]
Type the command you see in the log EXACTLY as you see it, into the command
line.  See what happens.
The log is saying, either the command isn't running, or the log isn't being
created.  The log not being created might be a cause of the command not
running, or it might be that the location of the log cannot be written to.

**Comment by guigros** [comment]
Ok, so I typed the command "sudo /usr/sbin/openvpn > /home/kodi/.kodi/temp/openvpn.log &" on my terminal

The file /home/kodi/.kodi/temp/openvpn.log is created but nothing get write into it.

![kodi-vpn-manager](https://user-images.githubusercontent.com/15982724/29974907-752f5eb4-8f02-11e7-8dc0-6b23a66208b7.PNG)

**Comment by Zomboided** [comment]
That suggests to me that the command isn't running.  Type everything before
the '>' exactly as you see it

**Comment by guigros** [comment]
Ok. I'm moving forward I think.

When I type the command "sudo /usr/sbin/openvpn > /home/kodi/.kodi/temp/openvpn.log &" from my terminal ---> the openvpn log file is created and written to 
![capture](https://user-images.githubusercontent.com/15982724/29975352-fc9042aa-8f03-11e7-81ab-c319f727a887.PNG)

The log is populated with : 
![capture](https://user-images.githubusercontent.com/15982724/29975416-429c5266-8f04-11e7-8084-e2260f73ce9c.PNG)

When I go on the add-on interface and I press "First VPN connection...", the openvpn log file is created but nothing get write

![capture](https://user-images.githubusercontent.com/15982724/29975494-906ce1ae-8f04-11e7-9cb6-c34099b3453e.PNG)

Do you think it could be an issue with Kodi or the add-on write access ?

**Comment by Zomboided** [comment]
Yeah, I'd guess that it's a permissions thing because of the way Kodi (or
the addon) is calling openvpn.

**Comment by Zomboided** [comment]
No further input, closing this
