### ISSUE TITLE
Filtering VPN Manager but No Validated Connections Available

### ISSUE THREAD

**Issue by floppy-disk** [Zomboided/service.vpn.manager#104]
I have worked to get this great plugin working forever now, and I just keep running into the same setup no matter my configuration. I have PIA, and I've tried running it on OpenELEC and LibreELEC (which I'm running now, version 8.1.0, on an Intel NUC.

The first connection will work successfully. Then, if I try to connect to any other location or add a second location, it connects and immediately disconnects, displaying the error Filtering VPN Manager for OpenVPN but no validated connection available. The only way to recover is to go to Utilities>Reset all VPN provider files to default and change the primary.

There doesn't appear to be anything outright happening in the logs, but I've included the  Kodi logs in debug mode. I'd really appreciate any help.

https://pastebin.com/4EfTLaWx

**Comment by Zomboided** [comment]
I really need to see a full log, not an extract, I can't really see what's going on.

There's an option to detect a running task in an alternative way in either the debug or monitor tab in settings. Try that.

Otherwise, clear vpn provider files, turn on debug, reboot to clear the log, then use the menu to connect to a couple of different VPNs. Then get the log and post it.

**Comment by Zomboided** [comment]
No further input, closing this

**Comment by rziegler72** [comment]
Hi, I just installed LibreELEC 8.2.2 on a Raspberry Pi 3 Model B and am seeing this same behavior.  My VPN provider is IPVanish.  After first time setup, I can connect fine to one of their servers.  When trying other servers (or that same one that worked), it just tells me "VPN Manager for OpenVPN - 
Filtering VPN Manager for OpenVPN but no validated connection available."

If I run openvpn from the command line using one of the ovpn files, that seems to launch any of them fine.

When trying again in the "VPN Manager for OpenVPN" UI again, it tells me "The OpenVPN executable isn't working. Check the log, then from a command line prompt, type 'openvpn' and fix any issues reported."

Running 'openvpn' with no arguments just displays the version and options parameters as expected.

Let me know what information I can provide.

**Comment by marco01h** [comment]
sur votre routeur, 
soit activez UPnP, mais danger au niveau de la sécurité
soit ouvrez le port 1194

**Comment by Zomboided** [comment]
@rziegler72 reset your VPN provider files (settings/utilities), restart your box and see the 2nd Sept post for what to gather.

The filter message is usually related to you having set up a filter but haven't defined a connection for that filter.  I don't understand why the executable is being reported as not working though (assuming you're really running a non-beta, unmolested LE build)
