### ISSUE TITLE
LimeVPN - changed config files

### ISSUE THREAD

**Issue by JonBenNoah** [Zomboided/service.vpn.manager#105]
[OpenVPN.zip](https://github.com/Zomboided/service.vpn.manager/files/1282341/OpenVPN.zip)
Hi Zomboided,

I'm sorry to bother you again concerning LimeVPN.
For the last couple of days the connections for all the servers I checked did not work.
I contacted their support, and they sent me new config files, which I attach.

I have tried one server (Sweden) in UserDefined as it works OK with the new config files.

As you may guess, I am annoyed with LimeVPN for changing things without any notification. I would well understand if you don't want to update your LimeVPN config database again after such a short time. If so, I can get by with UserDefined. On the other hand, I would appreciate it if you would agree to update your files.

Regards, Jon

**Comment by Zomboided** [comment]
Updated this...haven't tested it, but there was really only one change, and a couple new servers so it should be fine.  Thanks for sending me the zip, very helpful.

**Comment by JonBenNoah** [comment]
Thanks. I checked most of the servers and it works well.
