### ISSUE TITLE
Local playback stops when VPN connection drops

### ISSUE THREAD

**Issue by inspector71** [Zomboided/service.vpn.manager#106]
```
Raspberry Pi 3
LibreELEC 8.1.1 (Kodi 17.4 Krypton)
VPN Manager for OpenVPN 4.1.4 (Zomboided Repo)
```
Thanks for this impressive add-on. It makes a complicated concept and task possible and usable. I've only one issue. Why is local playback of backed-up content stopped when the VPN connection is lost?

I've looked everywhere and tried to tweak all the settings, even disabled the add-on filtering, but nothing short of entirely disabling the plugin prevents this behaviour. 

Presumably if I add the main playback window to the exclusion list, that will prevent the VPN from working on the *rare* occasions I watch streaming content.

Could an option be added to prevent this behaviour?

**Comment by Zomboided** [comment]
This is how the networking in the operating system/openvpn reacts, it has nothing to do with the addon and nothing I can do to fix it. You can run with vpn disabled using window filtering for local media, or you can ask your vpn provider why their connection is so poor. I've been running a VPN for close to two years and I can't remember the last dropout I had

**Comment by Zomboided** [comment]
I might be changing my mind about this.  See this post here
https://forum.libreelec.tv/thread/5032-vpn-manager-for-openvpn/?postID=63096#post63096
Feel free to do the same experiment and post up in the forum or here what your results are.

**Comment by inspector71** [comment]
It's kinda funny. I was thinking _local_ as in off the SD card of my Pi. Of course I'm talking about playback from a local _NAS_ over a wired *network* connection :) Never occured to me that oVPN wouldn't allow the connection to stay up.
Anyway, trying 4.1.5 now. 
Impressive responsiveness to users on this one. Thanks for your efforts.

**Comment by inspector71** [comment]
I think the problem may be worse for me now. Not trying to blame anyone, just describe the situation.

I installed 4.1.5 and enabled logging. The problem didn't seem to have stopped so I added the main player window ID of 12005 to the window exclusion list. That didn't seem to help and I thought perhaps that's because I have to go back to the Add-On's window to cycle VPN connections. So I added that window ID as well: 10001.

However now it's just killing the VPN connection whenever I try to _start_ playback from the usual nfs service on my NAS which is within the LAN.

Is this helpful:

```
00:08:03.444 T:1265628064  NOTICE: Creating audio stream (codec id: 86017, channels: 2, sample rate: 48000, no pass-through)
00:08:06.806 T:1582646176  NOTICE: VPN Mgr : (service.py) Window ID is now 12005
00:08:06.830 T:1582646176    NONE: VPN Mgr Debug: Encountered a new window ID 12005
00:08:06.855 T:1582646176    NONE: VPN Mgr Debug: Previous window ID was 10025
00:08:06.856 T:1582646176  NOTICE: VPN Mgr : (service.py) Disconnect filter found for window 12005 or addon
00:08:06.870 T:1582646176    NONE: VPN Mgr Debug: Disconnecting, previous VPN stored as /storage/.kodi/addons/service.vpn.manager/PIA/Switzerland (UDP).ovpn
00:08:06.887 T:1582646176    NONE: VPN Mgr Debug: Running VPN (dis)connect request Disconnect, current is /storage/.kodi/addons/service.vpn.manager/PIA/Switzerland (UDP).ovpn
00:08:06.900 T:1582646176    NONE: VPN Mgr Debug: Got forced cycle lock in connection part of service
00:08:06.914 T:1582646176    NONE: VPN Mgr Debug: Changing VPN. Current playing nfs://192.168.1.12/...
```

**Comment by Zomboided** [comment]
The only change was a debug statement, it wasn't supposed to make it better, and certainly filtering hasn't changed. Any change in behaviour is because you changed the filtering you'd originally set up.

This is helpful tho, thanks. I can see how your NAS box and the media is being reported which is what I needed. I'll let you know when I update something to help

**Comment by inspector71** [comment]
I didn't have filtering set up.
Don't worry, you don't have to be defensive.
Thanks for you efforts. Please let me know if I can help any further.

**Comment by Zomboided** [comment]
I promise I'm not being defensive, just economical with words. I'm suggesting that you change your window filtering back to what it was (this is what I mean by filtering) as the new, worse behaviour you're seeing is not going to happen because of this update - it's just a debug statement.

I have some good info now from you and a couple others. I'm thinking on a fix and will let you know when there's a new build. Thanks for your input so far

**Comment by Zomboided** [comment]
4.1.6 fixes this (probably) without doing window filtering.  Open a new issue if you still see the problem and provide a debug log.
