### ISSUE TITLE
NordVPN does not update .ovpn using NordVPN's DNS

### ISSUE THREAD

**Issue by forlotto** [Zomboided/service.vpn.manager#107]
When you use Nord's DNS server it does not allow you to update .ovpn files it errors out on 10 files due to some type of filter or throttle on their DNS servers which prevents you from updating the .ovpn files.

Keep this in mind if you are using NordVPN be sure to change DNS to something different while doing an update. If your updates are failing it may very well be DNS settings like this.

**Comment by Zomboided** [comment]
Use some other DNS servers.  This is not an issue with this plugin.  Opening an issue here as well as banging on about it on forums will not change my mind

**Comment by forlotto** [comment]
Not my intention the intention was to make mention and raise awareness of the issue so some poor sap doesn't spend days figuring out what the heck is wrong with a near perfectly working piece of software a rather simple thing. The issue as stated is NordVPN's DNS not the software and as I said I do not expect you to lift a finger but if you want to help I am more than greatful for it! 

This has nothing to do with forcing you to do anything it is not all about you it is about the other people that will waste a crap ton of time trying to figure out an issue that is not documented anywhere a simple solution exists but due to the obscurity and the nature of the problem it is very easy for it to be an oversight as you continue down the road of banging on as you put it. There is nothing mentioned in the wiki about the problem nothing mentioned anywhere it is a conflicting issue like it or not and it is solvable by software automating the change of DNS I started a new thread so I could stay out of your thread as you said you are not interested I get it as I stated.

I have no idea what the vague explanation you give "use some other dns servers and up/down scripts to change them when you are connected" Translates to my logical brain tells me that a simple debug switch to change DNS and two texts boxes to add the entries would likely allow any connection issues simply and easily using alternate DNS if gits fail. A useful tool for all. Something like this or possibly a new build of your software would work if I could figure out the process to mod it build it and learn how to use github and a number of other things like I said I am not forcing or banging you to do anything nor would I want to be forced into stopping my objective to raise awareness of the problem to save people a crapload of time but alas this is what it seems like to me. 

Bottom line the issue exists weather you want to acknowledge it does not matter it is an issue is it a fault of your software? NO I do not believe it is. Could the issue be fixed by modification to your software? YES IT CAN. 

Just proof anytime you do things out of kindness to help often they get taken out of context. 

I don't require you to lift a finger doing anything nor will I tell you what to do and at the same time I expect the same respect from you don't tell me how to live my life if you don't want to help or list something problematic don't but I feel it is needed after days of wasting time so I will continue to do so like it or not I am not hurting you in anyway nor am I attempting to damage your pride I am just sharing a truth if that hurts you I assure you it is not my intention but I cannot change your mind on how you feel only you can.

**Comment by Zomboided** [comment]
Wow, you are just pesty.  I've told you the answer, and I don't agree with your conclusions. But you want to carry on regardless because you can't be bothered to google and help yourself.  This is free software. I don't care if you use it or not - makes no difference to me at all.
