### ISSUE TITLE
How to solve? "Error, Service not running.  Check log and re-enable."

### ISSUE THREAD

**Issue by kiat-huang** [Zomboided/service.vpn.manager#108]
When my vanilla openelec kodi (17.3) box is brought back from suspend, when I try to change to any vpn connection the openvpn addon will refuse to connect and give that error in the UI.  The Kodi log shows this.

1. Workaround. How to restart the monitor manually?
2. Fix.  How to avoid such problems permanently?

`openelec:~/downloads/nordvpn-openvpn # tail -f /storage/.kodi/temp/kodi.log 
06:53:23.868 T:140583991432960    NONE: VPN Mgr Debug: Getting list of profiles in /storage/.kodi/addons/service.vpn.manager/NordVPN/*.ovpn
06:53:24.043 T:140583991432960    NONE: VPN Mgr Debug: -- Exit addon.py --
06:53:25.773 T:140583991432960    NONE: VPN Mgr Debug: -- Entered addon.py plugin://service.vpn.manager/ -1 ?change?/storage/.kodi/addons/service.vpn.manager/NordVPN/United Kingdom 47 (UDP).ovpn --
06:53:25.782 T:140583991432960    NONE: VPN Mgr Debug: Parsed arguments to action=change params=/storage/.kodi/addons/service.vpn.manager/NordVPN/United Kingdom 47 (UDP).ovpn
06:53:25.798 T:140583991432960    NONE: VPN Mgr Debug: Changing connection to /storage/.kodi/addons/service.vpn.manager/NordVPN/United Kingdom 47 (UDP).ovpn from , connected:False
06:53:34.582 T:140584329107200  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        external_ip_alert: external IP received 80.XX.XX.XX
06:53:35.820 T:140583991432960    NONE: VPN Mgr Debug: Connecting to VPN.
06:53:36.331 T:140583991432960    NONE: VPN Mgr Debug: Requesting service stops
06:54:06.344 T:140583991432960   ERROR: VPN Mgr : (common.py) Couldn't communicate with VPN monitor service, didn't acknowledge a stop
06:54:06.373 T:140583991432960   ERROR: VPN Mgr : (common.py) VPN monitor service is not running, can't start VPN
`

**Comment by Zomboided** [comment]
Can you post the full log please, ideally reboot, connect, then suspend and then get the log with debug on

**Comment by Zomboided** [comment]
No log, no problem.....closing

**Comment by SomeEggs** [comment]
Hi there,

Im trying to use the NordVPN app - and im getting a similar error.

Im running retropie with kodi as a port in retropie.

Any ideas here - in Kodi i can go into the setup wizard and try and connect - but after some time i get this error = 
Error service not running check log and re-enable or reboot

i checked the logs and got the parts that are mentioning nordvpn or openvpn - 

![thumbnail_20210316_200822](https://user-images.githubusercontent.com/80751798/111289384-36a78a80-8699-11eb-9f3f-3524c444d2c4.jpg)
![thumbnail_20210316_201000](https://user-images.githubusercontent.com/80751798/111289392-37d8b780-8699-11eb-82b5-7bb80ee26e1b.jpg)
![thumbnail_20210316_201053](https://user-images.githubusercontent.com/80751798/111289403-39a27b00-8699-11eb-8710-05bf11c46e0a.jpg)
![thumbnail_20210316_201235](https://user-images.githubusercontent.com/80751798/111289406-3a3b1180-8699-11eb-878b-c33a4685e15b.jpg)
![thumbnail_20210316_201619](https://user-images.githubusercontent.com/80751798/111289414-3c04d500-8699-11eb-9534-321544915bd4.jpg)

**Comment by Zomboided** [comment]
If you know which bits of the log I need to see, then you must know how to
solve the problem....

Get a full log, with debug switched on as per the wiki (do not switch
general Kodi debug on).  Share via pastebin.  I'm not looking at random
screenshots.
