### ISSUE TITLE
OpenVPN dissapears from program add one on kodi libreElec

### ISSUE THREAD

**Issue by ricardobf15** [Zomboided/service.vpn.manager#110]
Hi,

Can someone help me. I installed the latest zip from zomboided and after I install it the OpenVPN manager is under services but it never comes up on programs add-ons so I can use the display status, disconnect or change, etc. 

Would you know why?

**Comment by Zomboided** [comment]
Not without a log, I can't guess at this stuff.

**Comment by ricardobf15** [comment]
How do I get the log. Is wierd because it comes and goes it's back out of nowhere then start failing saying can't filter to validate and dissapears

**Comment by Zomboided** [comment]
Read the trouble shooting page on the wiki

**Comment by ricardobf15** [comment]
I replied via email

**Comment by ricardobf15** [comment]
Ok it came back to me cuz is to large

**Comment by ricardobf15** [comment]
https://imgur.com/a/jTxIv

**Comment by Zomboided** [comment]
I've a TorGuard change that I need to review.  You shoudl see a
notification that an update is available in the next day or so.

For future reference, Pastebin and the Kodi log is the right answer for
problems tho, not 3 screen shots.

**Comment by ricardobf15** [comment]
Yeah I'm new with the kodi on a pi3 so I don't how.to get the log from the pi and post here tho. Sorry

**Comment by Zomboided** [comment]
I've merged the TorGuard changes now.  You should try and reconnect and observe to see if it downloads new VPN provider data.  I'm not clear when your system will notice github has changed - it can take sometime - but it should be in the next day or so.

**Comment by ricardobf15** [comment]
Ok, so in other words when I turn on my pi3 and get into kodi if I go to my add one y should see an update is available for the OpenVPN manager? (From 4.1.6 to 4.1.7)?

I'm going to test it in about 15 minutes I know you said might take a couple of days. I'll let you know

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Zomboided** [comment]
No, just try and connect. It'll notice new provider files and update just those
