### ISSUE TITLE
Unable to resolve location information

### ISSUE THREAD

**Issue by matamualomia** [Zomboided/service.vpn.manager#112]
I'm an amateur at best when it comes to this kind of stuff, but can usually google my way out of a problem...not this time.

I set up a Rpi3 for a friend with retropie and kodi at my house. While at my house, I got it working fine. Now that I've brought it to his house and am connected to his wifi, it is hobbled. This appears to be within kodi alone while trying to use the VPN. I know this because I was able to update all the packages in retropie without an issue (retropie 4.3, kodi 17.4, emulators, etc), but when I try to access any content in kodi, I'm unable to. I also can't update any addons within kodi with the vpn enabled. I'm using windscribe.

I get the following error after I get the green update in the R upper corner of the screen saying I'm connected to the VPN:

"Connected to a VPN in unknown. 
Using profile United States West (UDP).
External IP address is no info.
Service provider is unknown."

Can you shed any light on this? I've read through the debug log and while I'm no expert, I can't find any issues. I've read through the https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting guide and tried switching the IP provider. The date is also correct. 

Since his ISP is the same as mine, and it works on two separate Pis at my house, I'd have to say this is an issue with his router settings. Does that sound right?

What is weird about that though is that I can use windscribe on my laptop on his network and it works...

I'm stumped. Any help would be appreciated.

**Comment by Zomboided** [comment]
Put debug on and look in the log.  The call to resolve is just an HTTP
request.  It traces out the response.  If it can't find it, then I'd
suspect some networking issue and associated message to appear in the log.
I did do a bug fix in this area some weeks back, so make sure you're on the
correct level.

**Comment by matamualomia** [comment]
Thanks for the prompt reply! I'll try it again in a few days when I'm back there.

**Comment by gijsvandinther** [comment]
I have the same issue. It seams it only happens when I power off my router for the night. My RP3 with Openelec stays powered on. On reconnect, the lan connection works fine, but I get this message from VPN addon.
![vpnaddon](https://user-images.githubusercontent.com/35948478/35549788-8e0cb11a-0587-11e8-9ff4-4ac06c29aed6.png).

Hope this helps. Do you have any idea for a fix (dirty if need be :-))
