### ISSUE TITLE
[Windows] OpenVPN executable isn't working

### ISSUE THREAD

**Issue by ZerGo0** [Zomboided/service.vpn.manager#114]
Hey,

every time I try to set up a VPN I get this message: https://i.imgur.com/fs7PxL8.png

I'm using Kodi on Windows, I installed OpenVPN to the default path but it doesn't seem to detect it, Kodi is running as administrator. 

Kodi-Log: https://i.imgur.com/4gyNALw.png

OpenVPN-Log is empty since it doesn't detect it. ^^

**Comment by Zomboided** [comment]
Get a full debug log and put it on pastebin

**Comment by ZerGo0** [comment]
I got it to work, had to add OpenVPN as Environment Variables by myself.

**Comment by Zomboided** [comment]
Ok, good

**Comment by nickshe89** [comment]
help i got some issues and i dont know how add to environment variables by myself
https://pastebin.com/HkbDFCck

thanks

**Comment by nsheehan** [comment]
Just install the NordVPN Client for windows. Turn it on when you use Kodi.
