### ISSUE TITLE
VPN disconnections

### ISSUE THREAD

**Issue by PiE81** [Zomboided/service.vpn.manager#115]
Since I configured the vpn, I noted frequent vpn disconnections (almost every 1-2 hours).
Considered that I had disconnections in internet in general, not only in vpn, I removed an old long cable that connect internet port to the router. I'm using a shorter cable, with less noise.
The connection seems more stable. Anyway, for now, I had one vpn disconnection. How can I debug it? This is the log around the disconnection.

22:16:20.843 T:1440740240 WARNING: VideoPlayer::Sync - stream player video does not start, flushing buffers
22:19:25.125 T:1504703376   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
22:19:25.126 T:1504703376 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
22:19:33.742 T:1819276176   ERROR: VPN Mgr : (service.py) VPN monitor service detected VPN connection /storage/.kodi/addons/service.vpn.manager/TorGuard/Romania (UDP).ovpn is not running when it should be
22:19:33.794 T:1819276176   ERROR: VPN Mgr : (platform.py) Couldn't write VPN error log
22:19:33.794 T:1819276176   ERROR: VPN Mgr : (platform.py) [Errno 2] No such file or directory: '/run/openvpn.log'
22:19:34.883 T:1819276176  NOTICE: VPN Mgr : (service.py) Disconnect from VPN
22:19:34.904 T:1819276176  NOTICE: VPN Mgr : (service.py) Connecting to VPN profile /storage/.kodi/addons/service.vpn.manager/TorGuard/Romania (UDP).ovpn
22:19:41.079 T:1819276176  NOTICE: VPN Mgr : (common.py) Received connection info from ipinfo.io, IP 93.115.85.148 location RO, ISP AS3223 Voxility S.R.L.
22:20:08.140 T:1504703376   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)

**Comment by PiE81** [comment]
Actually I noted on a previous log that this error repeat every hour, exactly 60 minutes.
I checked my router configuration, I had a dhcp lease time of 60 minutes. Maybe this was the problem.

**Comment by Zomboided** [comment]
Probably, but this concerns me:
22:19:33.794 T:1819276176 ERROR: VPN Mgr : (platform.py) Couldn't write VPN
error log
22:19:33.794 T:1819276176 ERROR: VPN Mgr : (platform.py) [Errno 2] No such
file or directory: '/run/openvpn.log'

If you'd connected successfully, then this file would have been written out
and there might be some stuff in it that would help.  Switch on debug, make
sure that the IP address you're told about is not your local one and when
it happens again, post something up.  If we can confirm that connection is
good, and that I'm writing out hte appropriate debug then I'll leave you to
debug your network problems.

**Comment by PiE81** [comment]
the file is written in /run/openvpn.log

I attached the log. 
I didn't get what you mean about (make sure that the IP address you're told about is not your local one).

This night the problem happens again, disconnections every hour, so it wasn't related to dhcp lease time.
But I read some posts about router provided by isp and wi-fi channel autoscanning. It is set every 60 minutes and it causes disconnections to all devices connected. I tried to remove this autoscanning, I'll check later (I'm not at home).

[openvpn.log](https://github.com/Zomboided/service.vpn.manager/files/1417345/openvpn.log)

**Comment by Zomboided** [comment]
I made a change to the TorGuard files.  If you revalidate the first connection you should pick this up automatically.

I've seen a problem before where a key is regenerated every hour, causing the connection to drop.  I don't see evidence of this in the openvpn file but I want to eliminate it before you waste time chasing down router issues.

**Comment by PiE81** [comment]
OK thanks, I'll reset all ovpn files and revalidate connection.

**Comment by PiE81** [comment]
It's ok now. It was a router problem. The wi-fi channel autoscan makes drop all connections every 60 minutes.

**Comment by Zomboided** [comment]
ok, great news I'll close this
