### ISSUE TITLE
Issue with LE and Milhouse Build 

### ISSUE THREAD

**Issue by Marv1896** [Zomboided/service.vpn.manager#119]
Hi Zomboided,

first of all: Thanks for your great add On, works perfect on mit Pi but I have just found out that there is an issue since I updated from LE to a Milhouse Build. 
I do use the newest version of your add on (4.1.9) and the newest Milhouse build. 
When I switch to the settings of the add on I am not able to open the add on filter rules. There is no pop up window showing up and the system crashes and reboots. I have tried the estuary and confluence skin but is not a skin issue. Is there a workaround to fix that or another way to filter several addons with different VPN Servers? 

Thanks.

**Comment by Zomboided** [comment]
You should report the problem to whoever provided the build. I'm not interested in debugging problems when the issue is flakey Kodi code. If you see this on a proper build then I'll look at it

**Comment by Zomboided** [comment]
I should add that there isn't an alternative way of filtering

**Comment by Marv1896** [comment]
Okay. Thanks anyway for your work and your respond. ;-)
