### ISSUE TITLE
What happened to NordVPN Support?

### ISSUE THREAD

**Issue by nsheehan** [Zomboided/service.vpn.manager#121]
The latest version does not offer Nord as a provider, attempting to setup as user defined causes the plugin to hang. Please advise

**Comment by Zomboided** [comment]
Clear the vpn provider settings and see the wiki for how to use the user defined settings. Nord is no longer supprted

**Comment by nsheehan** [comment]
There needs to be more information in the article. I spent 2-3 hours trying to get this to work due to the missing information. Thanks to the openelec.tv forum I found this:
Alright, I got it to work with the following steps:

In VPN Manager go to Settings -> Utilities and select 'Reset all VPN provider files to default', then select 'Remove all downloaded VPN provider files'
Open a shell to your kodi, then download the server files from nordvpn from this source 'downloads.nordcdn.com/configs/archives/servers/ovpn.zip' using 'wget'
Log in to Nord, go to your downloads and grab the appropriate file for your device: https://ucp.nordvpn.com/profile/downloads
Unzip the file: 'unzip config.zip'
download the nordvpn App on any pc.
Use it to connect to a server.
**Get the Servers list, Pick the one you want and note the Server Name Canada #151 for example
Wait for it to resolve your new IP. Write that down or leave it open.
Back in your downloaded server files go into the folder you extracted config.zip.
Find the config file containing that IP** you found
**You are looking for the server that matches the one you want here it would be something like ca151....
you should only find one file beginning with a country code and a number. remember that.
inside the folder ovpn_tcp**, there should also be a file with the same country code and number
**The config Folder will have the two required files
copy both files to /storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/
(you may have to create the folder 'UserDefined')
go to vpn manager settings and VPN configuration.
Select 'User Defined' as VPN Provider
Enter your username and password. (I already had that entered from before)
Further down in section 'advanced settings', go to Protocol filter and select 'UDP and TCP'
Now go to VPN Connections and click the first entry. It should now prompt you for your password and connect to the server.
***You can add several server files from the Config Folder so you can configure more than one under Connections, however adding too many will crash this plugin.
These steps needed some fixes as well, the tip I got from it was adding just a few NordVPN .ovpn files to the UserDefined folder or the 'VPN Manager for OpenVPN' chokes and hangs. Canceling doesn't work, you must reboot the device.
NordVPN was supported for over a year, I like many use Nord so why did you opt to drop support? Doesn't seem like a good choice.
