### ISSUE TITLE
NordVPN no longer appears as an option

### ISSUE THREAD

**Issue by brianmoran** [Zomboided/service.vpn.manager#122]
I had this working for the longest time. I did an update and Nord is gone.

**Comment by brianmoran** [comment]
@zomboided I see support for Nord was removed in e54a7c8. Any reason why?

**Comment by Zomboided** [comment]
Because I don't want to continually support their constant changes

**Comment by brianmoran** [comment]
Fair enough.

**Comment by brianmoran** [comment]
@zomboided - I’m trying to do the import wizard so I can get my Nord files loaded but the browse window won’t let me browse the file system. I’m on OpenElec. Any help is appreciated.
