### ISSUE TITLE
IPVanish - Vienna Servers "dead"

### ISSUE THREAD

**Issue by Jaboa72** [Zomboided/service.vpn.manager#123]
Hello!
Great Addon, working perfectly - just one thing:
I'm using a RPI3 with LE Millhouse and IPVanish with the Open VPN Manager ...
Since about 3 weeks the 3 Vienna Servers the Addon is showing **are dead**...
Austria - Vienna 01, Vienna 02, Vienna 03

Talked to IPVanish and they confirmed that these servers are dead - but they said they have Vienna 04 to Vienna 09 also working ...

Any chance to replace the dead servers (Vienna 01-03) with the working ones (Vienna 04-09)?

Thanks

**Comment by Zomboided** [comment]
Updated.  You'll see a message in the next day or so telling you there's an update and you'll need revalidate

**Comment by Jaboa72** [comment]
... great, thanks a lot!!!
