### ISSUE TITLE
tigerVPN

### ISSUE THREAD

**Issue by mg1234567** [Zomboided/service.vpn.manager#124]
On a raspberry pi 3b with osmc. 
I have been messing around with this for a while.  Finally, had to do this:
sudo apt-get update
sudo apt-get install openvpn
sudo apt-get install psmisc 
Now, it runs without errors (besides login). 

Now that it's working, nearest I can tell it is a problem with what tigerVPN has given you.  
I have an unlimited / lifetime account and when I try either "Full Account" or "Lite Account" it doesn't work.  

tigerVPN says:
"Active Plan: Lifetime-Full"

The error I get is that there is an incorrect username/password, but of course, there isn't.  

Would you be able to contact tigerVPN and ask about unlimited account settings? 
Any help would be greatly appreciated. 
Thanks

**Comment by mg1234567** [comment]
VPN log file start >>>
15:34:00.907 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 26 2017
15:34:00.907 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 WARNING: file '/home/osmc/.kodi/addons/service.vpn.manager/tigerVPN/pass.txt' is group or others accessible
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 Socket Buffers: R=[163840->131072] S=[163840->131072]
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 UDPv4 link local (bound): [undef]
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 UDPv4 link remote: [AF_INET]162.220.221.42:1194
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 TLS: Initial packet from [AF_INET]162.220.221.42:1194, sid=fe91b0a4 e6b9528c
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 VERIFY OK: depth=1, C=SK, ST=Bratislava, L=Bratislava, O=Tiger At Work & Co. k. s., OU=tigerVPN, CN=tigerVPN, name=tigerVPN, emailAddress=help@tigervpn.com
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 Validating certificate key usage
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 ++ Certificate has key usage  00a0, expects 00a0
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 VERIFY KU OK
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 Validating certificate extended key usage
15:34:00.908 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 VERIFY EKU OK
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 VERIFY OK: depth=0, C=SK, ST=Bratislava, L=Bratislava, O=Tiger At Work & Co. k. s., OU=tigerVPN, CN=tigervpn.com, name=tigerVPN, emailAddress=help@tigervpn.com
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 NOTE: --mute triggered...
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 3 variation(s) on previous 10 message(s) suppressed by --mute
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:52 2017 [tigervpn.com] Peer Connection Initiated with [AF_INET]162.220.221.42:1194
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:54 2017 SENT CONTROL [tigervpn.com]: 'PUSH_REQUEST' (status=1)
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:58 2017 AUTH: Received control message: AUTH_FAILED,Username or password incorrect
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:33:58 2017 SIGTERM received, sending exit notification to peer
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:34:00 2017 SENT CONTROL [tigervpn.com]: 'PUSH_REQUEST' (status=1)
15:34:00.909 T:1726108656  NOTICE: Thu Dec 14 15:34:00 2017 SIGTERM[soft,exit-with-notification] received, process exiting
15:34:00.910 T:1726108656  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end
15:34:01.513 T:1726108656   ERROR: VPN Mgr : (common.py) Error connecting to VPN, authentication failed. Check your username and password (or cert and key files).

**Comment by Zomboided** [comment]
I've got a tiger account and I've just checked it still works - it does.
This error message is clearly saying that you've supplied the wrong credentials.  If you're using yatse to enter data, stop, it fucks things up.  Otherwise, it's up to you to work out what the right user/pass is, I'm not going to be able to do that for you.

**Comment by mg1234567** [comment]
I wish I could show you and tell you that I'm entering the correct information.  It works on my phones, tablets and windows.  I use it often.  But, the same info does not work on my pi with OSMC.  I wish it did.  I'm not using yatse, I'm using Rii Mini i8+.  I can clearly see the login and hit the box to show the password.  Both are correct.  Do you have a tigervpn lifetime account like I do?  Do you have any suggestions?

**Comment by KennyK7** [comment]
Mg1234567, you have to use different credentials. When visiting the tigervpn website (when logged in) you have to click on the menu, and select "Geeks". Here you will find credentials for third party builds.
