### ISSUE TITLE
Downloading on krypton raspbery pi 2

### ISSUE THREAD

**Issue by str80** [Zomboided/service.vpn.manager#126]
Getting message "the openvp executable isn't working. Check the log, then from command. Line type 'openvpn' and fix any problem reported.
New to this though i runned command. And everthing seems to be ok(even though seems like foreign. Language to me) anyhow. I am trying to connect to ipvanish.
Then u runned some sudo commands on command line like sudo install openvpn and sudo installxxx.mics.
Nothing. Have done so far fix the issue. Can someone let me know what to do..helpppp.
Thank you for you assistance. (Running krypton 17.5 in my raspberry pi connected to my tv)

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#openvpn-errors

If you don't understand how to do this stuff, then install LibreELEC which comes with all this stuff pre configured.

**Comment by str80** [comment]
Hi there,

Thank you fro your prompt response.
I'll try to fix it.

Thank you again.
________________________________
