### ISSUE TITLE
VPN connection does not disconnect

### ISSUE THREAD

**Issue by fredall** [Zomboided/service.vpn.manager#127]
Hi
First thank you for this excellent plug-in. 
I am using it with Proton VPN and have done the setup with the user defined wizard. 
But I am facing the issue that the VPN is impossible to disconnect 
When I try to disconnect it gives the message "VPN disconnected" but right below it still gives the connection details to the previous VPN connection. 
When I check the status menu it is still connected to the VPN. 

I will try to extract the log tonight to share.

**Comment by Zomboided** [comment]
If you're using something other than LibreELEC, especially something like OSMC, then check the install page and the trouble shooting page on the wiki. It sounds like you're missing the things you need to manage and stop the openvpn task

**Comment by fredall** [comment]
Thank you Zomboided
Somehow PSMISC istallation failed and "killall" was missing.
reinstalling psmisc solved the issue:
    sudo apt-get install psmisc

Sorry for bothering
