### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by hoshsadiq** [Zomboided/service.vpn.manager#128]
Sorry to revive an old topic. Regarding #65 

There's this openvpn app https://github.com/schwabe/ics-openvpn .

The docs suggest it's possible to control the Android openvpn app using AIDL. Perhaps it might be possible to require this to be a requirement, and then have some integration between the two. This would allow for this addon to work on Android too. Any possibilities for this to be implemented?

**Comment by Zomboided** [comment]
I don't have access to the hardware to even try this out, so I'm not gonna be able to do this.  If you do, and can install this and are happy to go understand the droid bits, I'd be happy to help with the changes in VPN Mgr?  Here are the requirements :

Would need a way to start the connection, passing in an ovpn file with full path name.

Would need a way to determine whether a connection was running (On Linux and Windows I use an OS call to see if the openvpn task is running).

Would need a way to stop the connection (I use killall on Linux, probably something similar on Windows)

**Comment by Zomboided** [comment]
Closing as not supported
