### ISSUE TITLE
SmartDnsProxy

### ISSUE THREAD

**Issue by marcofrl1** [Zomboided/service.vpn.manager#13]
Hi,
i have tried to configure a custome profile for the SmartDNSProxy vpn services.
I followed the instructions of the README, but when I try to activate the VPN error appears no service to the UDP protocol.
Is possible to this provider ?
Is a very good service, very fast and economic.

**Comment by Zomboided** [comment]
It might be a filter problem - if you're running the latest version you shouldn't run into this, all ovpn files will be displayed to you (or you can change the filter to UDP and TCP to see everything).
I've added this as a future request, but it's behind a bunch of other requests.

**Comment by marcofrl1** [comment]
Thank you very much

Best regards

*Marco Fiorletta*

This e-mail (including attachments) is intended only for the 
recipient(s) named
above. It may contain confidential or privileged information and should 
not be
read, copied or otherwise used by any other person. If you are not the 
named
recipient, please contact (info@m2syseng.com) and delete the e-mail from 
your
system.
Il 01/12/2016 18:24, Zomboided ha scritto:
> It might be a filter problem - if you're running the latest version 
> you shouldn't run into this, all ovpn files will be displayed to you 
> (or you can change the filter to UDP and TCP to see everything).
> I've added this as a future request, but it's behind a bunch of other 
> requests.
