### ISSUE TITLE
same issue as matamualomia commented on Oct 12, 2017

### ISSUE THREAD

**Issue by gijsvandinther** [Zomboided/service.vpn.manager#130]
I have the same issue. It seams it only happens when I power off my router for the night. My RP3 with Openelec stays powered on. On reconnect, the lan connection works fine, but I get this message from VPN addon.
![vpnaddon](https://user-images.githubusercontent.com/35948478/35555342-23149b12-059f-11e8-87b2-f7071eeb619b.png)

I have to manually reconnect, then everything is working fine again. Is there a commandlinescript I could run with cron that does this everyday automatically?

**Comment by Zomboided** [comment]
You can use the ping option in the debug settings which will keep pinging the VPN server to see if it's still alive.  I don't know what the long term behaviour of it is, it might just quit after a while.

If the connection is bad, the addon will keep trying to reconnect.  That gets bored after 10 attempts at increasingly long intervals and stops trying too.

There's an API you can use to force a reconnect.  That's documented on the wiki and should be easy to integrate into a cron job.

**Comment by gijsvandinther** [comment]
Thanks for you quick response. 

python RunScript(special://home/addons/service.vpn.manager/api.py, Reconnect)

returns:

-sh: syntax error: unexpected "("

I call the script directly from commandline (have no python experience). Calling the script with:

python ./api.py --script-args Restart

Results in:

Traceback (most recent call last):
  File "./api.py", line 22, in <module>
    import xbmcaddon
ImportError: No module named xbmcaddon

Maybe it is a dumb python newbie question... ? But what am I doing wrong?

Regards, Gijs

**Comment by Zomboided** [comment]
You need to run it within the Kodi environment or it has no context.  See
here
https://forum.kodi.tv/showthread.php?tid=285499

Alternatively, there are some Kodi addons that will let you run a script
periodically.  I can't remember what they're called, it's been a while
since I looked for them.

**Comment by gijsvandinther** [comment]
Thanks for the explanations. From command line and with cron it is working. I wil check tomorrow morning if everything working after the router had been offline several hours.

**Comment by gijsvandinther** [comment]
By the way, I really appreciate your time and help. Is there anywhere I can donate for the good cause :-)

**Comment by Zomboided** [comment]
Good news...if you want to buy me a virtual beer, then throw something at
my paypal - mattedsmith@googlemail.com, thanks for the thought man.
