### ISSUE TITLE
Windows:  "The OpenVPN executable isn't working"

### ISSUE THREAD

**Issue by abfaelle** [Zomboided/service.vpn.manager#131]
"The OpenVPN executable isn't working" - this is the error I get when I try to establish a connection. 

I've read all the documentation, including your advice in the Troubleshooting section ("If you're running Windows, then it's probably just that you failed to check the box which adds to the openvpn executable to the path. You can google all about Windows paths to fix this.") and the info in the section on Installation ("Make sure you keep the option to update the path checked"). I've also googled heavily but I still don't know to do.

My computer runs Windows 8.1, OpenVPN has been installed and it's working. I assume I have to somehow inform VPN Manager what is the path to openvpn-gui.exe but I have no idea how to do that. I would very much appreciate your help.

**Comment by Zomboided** [comment]
You need to make the openvpn.exe available on the system path. Google "windows 8 path variable". I don't use 8, so no idea how to do this.

**Comment by abfaelle** [comment]
Do you know how to do that on any version of Windows? If you could explain it to me or give me a link to an article, I'd probably be able to find the solution for my version of the system. 

It's not laziness on my part, just desperation :). I've been googling that intensely and I still have no idea what the problem is and what it means to keep the option to update the path checked (where was this option?).

**Comment by Zomboided** [comment]
https://www.java.com/en/download/help/path.xml
