### ISSUE TITLE
Digibit

### ISSUE THREAD

**Issue by pcpaulsbuild** [Zomboided/service.vpn.manager#134]
Hi would it be possible to add digibit as a provider please

**Comment by Zomboided** [comment]
I don't want to add any more providers because it causes me to much overhead to continually update them.  You can use the import wizard if you want to use this provider, or select one of the ones that are supported

**Comment by pcpaulsbuild** [comment]
Hi mate


Many thanks for replying didn't even think I would get that , I can understand the work involved and i currently use the user way to make it work , just was a thought being how popular digibit has become.




Get Outlook for Android







On Wed, Feb 21, 2018 at 11:01 PM +0000, "Zomboided" <notifications@github.com> wrote:












I don't want to add any more providers because it causes me to much overhead to continually update them.  You can use the import wizard if you want to use this provider, or select one of the ones that are supported
