### ISSUE TITLE
Purevpn removed

### ISSUE THREAD

**Issue by philborman** [Zomboided/service.vpn.manager#137]
Unfortunately the purevpn kodi addon does not work on osmc kodi, whereas zomboided addon worked fine until latest release. Can purevpn be added back in?

**Comment by Zomboided** [comment]
I'm done supporting problems caused Pure with their insecure and unreliable service, it's not getting added back in.  If you want to continue to use this add-on then you can try and use user defined.  It'll probably work fine but you'll need to support it yourself.  Or you can ask Pure why they don't do a good job of supporting their own customers.

For my money, I'd be getting another VPN provider.

**Comment by andresrinivasan** [comment]
@philborman Came across this issue and wanted to add to the artifacts that a) PureVPN for Kodi is inconsistent even on a supported OS and b) I have worked around this with Zomboided's VPN Manager.

* Install both VPN Manager and PureVPN for Kodi
* Follow the instructions to create a user defined VPN directory for VPN Manager
* Copy the .ovpn you want from PureVPN into the user defined directory

The reason this works is the .ovpn files provided by PureVPN all have absolute pathname references for certificates, private key, etc.
