### ISSUE TITLE
checking location info hang

### ISSUE THREAD

**Issue by dogbobbin** [Zomboided/service.vpn.manager#138]
Hi,

When trying to connect to my VPN (CyberGhost) on my Raspberry Pi 3 running OSMC and it is hanging on "checking location info". Here is the log showing this (I'm assuming this is the relevant part):

18:24:26.107 T:1698689792    NONE: VPN Mgr Debug: VPN connection status is 1
18:24:26.130 T:1698689792    NONE: VPN Mgr Debug: Getting IP info from ipinfo.io
18:25:06.300 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider ipinfo.io
18:25:06.300 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) <urlopen error [Errno -2] Name or service not known>
18:25:06.371 T:1698689792    NONE: VPN Mgr Debug: Got response, IP is error response time in seconds is 40
18:25:06.371 T:1698689792   ERROR: VPN Mgr : (common.py) Didn't get a good response from ipinfo.io
18:25:06.394 T:1698689792    NONE: VPN Mgr Debug: Getting IP info from IP-API
18:25:46.474 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider IP-API
18:25:46.474 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) <urlopen error [Errno -2] Name or service not known>
18:25:46.545 T:1698689792    NONE: VPN Mgr Debug: Got response, IP is error response time in seconds is 40
18:25:46.546 T:1698689792   ERROR: VPN Mgr : (common.py) Didn't get a good response from IP-API
18:25:46.569 T:1698689792    NONE: VPN Mgr Debug: Getting IP info from freegeoip.net
18:26:26.609 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider freegeoip.net
18:26:26.609 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) <urlopen error [Errno -2] Name or service not known>
18:26:26.678 T:1698689792    NONE: VPN Mgr Debug: Got response, IP is error response time in seconds is 40
18:26:26.678 T:1698689792   ERROR: VPN Mgr : (common.py) Didn't get a good response from freegeoip.net
18:26:26.702 T:1698689792    NONE: VPN Mgr Debug: Getting IP info from ipinfo.io
18:27:06.908 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider ipinfo.io
18:27:06.909 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) <urlopen error [Errno -2] Name or service not known>
18:27:06.979 T:1698689792    NONE: VPN Mgr Debug: Got response, IP is error response time in seconds is 40
18:27:06.979 T:1698689792   ERROR: VPN Mgr : (common.py) Didn't get a good response from ipinfo.io
18:27:07.002 T:1698689792    NONE: VPN Mgr Debug: Getting IP info from IP-API
18:27:47.106 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider IP-API
18:27:47.106 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) <urlopen error [Errno -2] Name or service not known>
18:27:47.176 T:1698689792    NONE: VPN Mgr Debug: Got response, IP is error response time in seconds is 40
18:27:47.176 T:1698689792   ERROR: VPN Mgr : (common.py) Didn't get a good response from IP-API
18:27:47.199 T:1698689792    NONE: VPN Mgr Debug: Getting IP info from freegeoip.net
18:28:27.339 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider freegeoip.net
18:28:27.340 T:1698689792   ERROR: VPN Mgr : (ipinfo.py) <urlopen error [Errno -2] Name or service not known>
18:28:27.410 T:1698689792    NONE: VPN Mgr Debug: Got response, IP is error response time in seconds is 40
18:28:27.410 T:1698689792   ERROR: VPN Mgr : (common.py) Didn't get a good response from freegeoip.net
18:28:27.923 T:1698689792  NOTICE: VPN Mgr : (common.py) Connected to a VPN in unknown.
                                            Using profile United Kingdom Premium (TCP).
                                            External IP address is no info.
                                            Service Provider is unknown.

This started happening when I got a new router, so I'm assuming it's something to do with port forwarding? I have tried opening port 1194 (when using UDP) on my router:

<a href="https://ibb.co/ns92VS"><img src="https://thumb.ibb.co/ns92VS/port.jpg" alt="port" border="0"></a>

But unfortunately the same thing happens... I've tried different port numbers and I've also tried TCP. I've also tried different version of VPNmanager and OSMC. The problem always persists.

Could you offer any advice?

Thanks

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation#linux

https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#debugging-vpn-problems

Particularly https://github.com/Zomboided/service.vpn.manager/issues/129

**Comment by dogbobbin** [comment]
Yeah I did see that thread but honestly it's a bit over my head... I was just assuming there would be some kind of setting I could change on my router? It must be related to my router because this only started happening when I changed it

**Comment by Zomboided** [comment]
This line and the others like it - 18:28:27.340 T:1698689792 ERROR: VPN Mgr : (ipinfo.py) <urlopen error [Errno -2] Name or service not known
make me think that the DNS is not working.  After it spews out the dialog covered with 'unknown', you could SSH onto the box and try doing some pings.  If the DNS can't resolve basic things like google.com then it's a DNS problem.  Not sure why it would only start happening with a new router though.

**Comment by dogbobbin** [comment]
Umm okay and how would I go about resolving a DNS problem?

**Comment by Zomboided** [comment]
Well I'd try what I said in the previous post, then I'd read post #129 and follow those links, and I'd google 'DNS resolution problems with VPN' or something similar, maybe also looking for DNS issues with your router.  If it's all out of your depth, then using LibreELEC rather than OSMC might work for you.  If that doesn't do it, then what I just said.
