### ISSUE TITLE
Stuck , really

### ISSUE THREAD

**Issue by DennedugazAsti** [Zomboided/service.vpn.manager#139]
I just installed it on a Kodi(LibreElec) and it's great,
but
I  flipped most of the switches available in the add-on settings and now can't get back into ANY settings or menu, a popup diplaying the available connections for PIA is coming up and preventing me from going into any Kodi's menus, 
so 
how do I disable it from a ssh ?

**Comment by Zomboided** [comment]
Can you save off the log in /storage/.kodi/temp/kodi.log so I can see why this is happening first please?  Not seen this before.

Using ssh you can delete everything in /storage/.kodi/addons/service.vpn.manager and reboot. If you reinstall all the settings should persist, which may or may not lead to the same problem

**Comment by DennedugazAsti** [comment]
Yeah , thanks for your quick reply,
I found it, as I wrote I tried every switch available in there, so I mis-remaped the 'OK' button on my remote to display a table(popup) showing the available VPN connections...
I discovered this by trying 'kore' the android remote for Kodi.
I added the key remap addon from the Kodi repo so that my hardware-remote would work again and it did => my remote re-became OK, 
but
now vpn-manager sees that, that the key remap isn't the original file so it's bringing back it's version evertime, 
so
is there a way to wipe the key-maps performed from vpn-manager & use the original file so vpn-manager will not complain when starting?

**Comment by Zomboided** [comment]
Makes sense. It's in /storage/.kodi/userdata/keymaps I think. Delete any files that contain "zomboided" or "vpnmanager" and reboot
