### ISSUE TITLE
Won't connect suddenly

### ISSUE THREAD

**Issue by blatchy** [Zomboided/service.vpn.manager#14]
Ran latest code in both 7.01,7.02 and alpha builds of libreelec..  Receive the following errors:

12:57:09  49.571815 T:1600385952   ERROR: VPN Mgr : (common.py) No LOCATIONS.txt files found in VPN directory.  Cannot generate ovpn files for User Defined.
12:57:09  49.955441 T:1600385952  NOTICE: VPN Mgr : (vpnproviders.py) Copying user defined files from userdata directory
12:57:09  49.963989 T:1600385952   ERROR: VPN Mgr : (vpnproviders.py) No User Defined files available to copy from /storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/
12:57:10  51.379662 T:1600385952   ERROR: VPN Mgr : (common.py) Error updating .ovpn files or creating user credentials file.
                                            Check log to determine cause of failure.

I created the UserDefined folder, I added my .ovpn files.  Nothing works.  What's weird is that this worked up until a few days ago.  But I rebuilt the image and ever since, can't log in.  I can connect to the VPN on my PC.

**Comment by Zomboided** [comment]
Recreate it on a non-alpha build and provide a full log.  I'm not really interested in debugging alpha builds as they can break things in weird ways.

**Comment by blatchy** [comment]
15:45:18 714.155457 T:1784673184 WARNING: CPythonInvoker(11): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
15:45:23 718.486267 T:1784673184   ERROR: VPN Mgr : (common.py) No LOCATIONS.txt files found in VPN directory.  Cannot generate ovpn files for User Defined.
15:45:23 718.752502 T:1784673184  NOTICE: VPN Mgr : (vpnproviders.py) Copying user defined files from userdata directory
15:45:23 718.760864 T:1784673184   ERROR: VPN Mgr : (vpnproviders.py) No User Defined files available to copy from /storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/
15:45:24 720.196899 T:1784673184   ERROR: VPN Mgr : (common.py) Error updating .ovpn files or creating user credentials file.

Thanks again

**Comment by blatchy** [comment]
That's 7.0.2

**Comment by Zomboided** [comment]
A full log, with debug switched on, not just 5 lines from the log.

**Comment by Zomboided** [comment]
And an ls -l of /storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/

**Comment by blatchy** [comment]
[output.txt](https://github.com/Zomboided/service.vpn.manager/files/629881/output.txt)

[kodi.log.txt](https://github.com/Zomboided/service.vpn.manager/files/629882/kodi.log.txt)


Output is the ls -l command.  I do put the two .ovpn files in that directory.  After I go to connect for the first time, the files disappear from the directory.

**Comment by Zomboided** [comment]
The log shows a clean install, which will clear out all addon directories (same happens after the add-on is updated).  I think you're putting the files in /storage/.kodi/addons/service.vpn.manager/UserDefined and not the userdata path I mentioned above?   The userdata directories are never cleared, the initialisation process will copy from the userdata to addon directories when it needs to.  The log is also showing there are no files available which is consistent with this theory.

If I'm wrong, then it could be a bug in the new 2.2.4 version which is doing something that I can't recreate on my system.  If so, roll back to 2.2.3 and get a log with full debug switched on (Settings/Debug/General/Enable debug for just VPN Manager)

**Comment by blatchy** [comment]
No, you were right.  I had the path mixed up.  Thank you so much.  This add-on work amazing (if I can remember the proper paths from build-to-build).
