### ISSUE TITLE
PIDOF test does not return true

### ISSUE THREAD

**Issue by Pelican973** [Zomboided/service.vpn.manager#140]
Hello,
I have a raspberry pi with OSMC installed.

I encountered a problem when trying to use VPN manager, first an error message told me that "the pidof command isn't writing out a response" so I've looked into the logs and into your code, I saw that the pidof command test is using kodi.bin, which was not in my $PATH, I fixed it but now I have this error in kodi.log : 
```
11:11:58.308 T:1635775232  NOTICE: VPN Mgr : (service.py) Starting VPN monitor service, platform is 2, version is 4.4.2
11:11:58.308 T:1635775232  NOTICE: VPN Mgr : (service.py) Kodi build is 17.6
11:11:58.308 T:1635775232  NOTICE: VPN Mgr : (service.py) Addon path is /home/osmc/.kodi/addons/service.vpn.manager/
11:13:29.395 T:1635775232  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : sudo /usr/sbin/openvpn > /home/osmc/.kodi/temp/openvpn.log &
11:13:33.351 T:1635775232  NOTICE: VPN Mgr : (platform.py) Testing pidof with : sudo pidof kodi.bin/home/osmc/.kodi/temp/command_test.txt>&/home/osmc/.kodi/temp/command_test.txt &
11:13:34.898 T:1635775232   ERROR: VPN Mgr : (platform.py) Ran pidof command and it failed
11:13:35.247 T:1635775232  NOTICE: VPN Mgr : (platform.py) Command test file start >>>
11:13:35.248 T:1635775232  NOTICE: VPN Mgr : (platform.py) <<< Command test file end
```

So I ran the command directly : 
```
osmc@osmc:~/.kodi/temp$  sudo pidof kodi.bin/home/osmc/.kodi/temp/command_test.txt &> /home/osmc/.kodi/temp/command_test.txt
 [1] 7588
osmc@osmc:~/.kodi/temp$
[1]+  Done                     sudo pidof kodi.bin/home/osmc/.kodi/temp/command_test.txt &> /home/osmc/.kodi/temp/command_test.txt
```
But nothing appeared in the "command_test.txt" file.
Then I tried with "bash" : 
`osmc@osmc:~/.kodi/temp$ sudo pidof bash>&/home/osmc/.kodi/temp/command_test.txt &
[1] 7802
osmc@osmc:~/.kodi/temp$
[1]+  Done                    sudo pidof bash &> /home/osmc/.kodi/temp/command_test.txt
`
And It worked : 
`osmc@osmc:~/.kodi/temp$ tail -f command_test.txt
7490 3733 295
`
I think that the pidof command works like a charm, but there is a space missing between kodi.bin and the test file path.

**Comment by Zomboided** [comment]
I'm busy changing a bunch of stuff at the moment and the latest code in the repo isn't guaranteed to work (I've not tested it on a Linux platform yet...).  Use an official release until I package all this up properly.  I'll look into fixing this meantime though, thanks for mentioning it, but get off the bleeding edge ;)

**Comment by Pelican973** [comment]
Ok, sorry, I did not realize it was not the release, I don't even remember where I get this version, I've used your repository and it works. Thank you for your reactivity, and good job for the rest!
