### ISSUE TITLE
LibreELEC (Krypton) 8.2.4 MR

### ISSUE THREAD

**Issue by MidnightRyd3r** [Zomboided/service.vpn.manager#141]
Just installed this version of LibreElec and discovered that pidof is only located in /usr/bin and not in /usr/sbin. When ever the call to this is made it seems like it's only looking in /usr/sbin and never sees it in /usr/bin even though my path is /usr/bin;/usr/sbin.

**Comment by Zomboided** [comment]
Are you using a released build from the repo or rolling your own? Code is being updated at the moment so the GitHub code has issues and should be avoided

**Comment by MidnightRyd3r** [comment]
Not rolling my own. First tried service.vpn.manager-master.zip from a link provided in an article I read. Then uninstalled and installed from repository.zomboided.plugins-1.0.0.zip, but this didn't have NORDVPN like the other. Reinstalled the other again for NORDVPN and it shows as 4.4.2. If there's something I can do or update I would be happy with that until an official release.

[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/1871194/kodi.log)

**Comment by Zomboided** [comment]
So whatever article you got that from has just linked to a bunch of code that doesn't work yet.
Install the version from repo.  Nord is not support yet.
