### ISSUE TITLE
Writing a log failed

### ISSUE THREAD

**Issue by exe22** [Zomboided/service.vpn.manager#143]
Today I tried to setup the VPN Manager on LibreElec

After I entered my login credentials I went to VPN Connections and selected the First VPN connection.

I keep receiving the error: _The OpenVPN executable isn't writing out a log. Try changing the Kodi log directory setting in Setting-Debug menu and retry._

So I went to the Debug tab in the settings and put _Always use Kodi log directory for OpenVPN log_ to **Active**.

Unfortunately I still receive the same error.

Anything I can do to fix it?

**Comment by Zomboided** [comment]
See if the ovpenvpn executable is working on the command line.  Read the
troubleshooting section in the wiki.

**Comment by exe22** [comment]
I did a fresh installation and suddenly it works, no clue why though. Anyway, thank you very much.

One more request: Is it possible to include ProtonVPN in your VPN provider list? Would be great. Thanks!

**Comment by Zomboided** [comment]
Good news, but no, can't be doing with adding more providers as it's effort
to keep them up to date.  The import function works well, you can likely
just import everythign you need with some clicks if you want to use that.
