### ISSUE TITLE
VPN Manager for OpenVPN on mac

### ISSUE THREAD

**Issue by hermannkm** [Zomboided/service.vpn.manager#144]
"is currently not supported on this hardware platform" is shown when I try to set up my VPN-Connection as primary in "VPN-Connections".
I am on a Macbook Pro with High Sierra installed.
How can I set up my already defined VPN-Connection in "VPN-Configuration"?

**Comment by Zomboided** [comment]
Who knows, I don't use a mac and there's no support built into this addon
