### ISSUE TITLE
PIA not working

### ISSUE THREAD

**Issue by mirc66** [Zomboided/service.vpn.manager#146]
PIA had been working flawlessly till april 2018.  I tried on all methods usable on the pi 3. openelec, libreelec and OSMC and cannot connect to PIA vpn.  Read your documentation and tried downloading the files from openvpn config files from  PIA  site to a thumb drive and use user defined vpn and give the path to the thumb drive that did not work either.

**Comment by Zomboided** [comment]
So you've tried to connect using 3 different operating systems, using both
the built in support and user defined, and your conclusion is that it's a
problem with the add-on?
And you can't be arsed to provide any logs, or describe it in any way that
would be at all helpful (yet you claim you've read the documentation which
tells you to provide logs to get support).
Good job...

You should also be aware that I use PIA and have connected to it today, and
there were no issues.

**Comment by mirc66** [comment]
Sorry i did not mean it was the add on i though it was the definitions.. .no offense was meant.  I am a newbie and i did read the documentation since im learning i was hoping

to get help.  I realize you get a ton of help requests but sorry to have bothered you.  I will continue to try on my own now that i at least know that it works

I was unable to get any help from PIA.

 Sorry no offense meant.



________________________________
