### ISSUE TITLE
NordVPN weirdness

### ISSUE THREAD

**Issue by gcleaves** [Zomboided/service.vpn.manager#149]
Hello. I just installed your addon in LibreElec on a Raspberry Pi 2B by downloading the addon only from Github. I was offered a Wizard, which I followed. In the Wizard, I had the option of selecting NordVPN, which I did. Things went well until this point, I was able to select my main country. 

Then when I went into the options to select secondary countries, things started to go wrong. I received a message that new profiles existed and whether to download. I said yes. This erased my fist option and I wasn't able to get my country list again as NordVPN was not longer available as a provider.

I have ended up using the User Defined option, but just wanted to bring this to your attention. Is NordVPN supported?

**Comment by Zomboided** [comment]
No it's not supported...I removed it from settings, but forgot to remove it from the wizard. Support *might* appear in the next few weeks again.

Meantime use the user defined wizard and feed it a Nordvpn ovpn file (or files). Should work just fine

**Comment by Zomboided** [comment]
Removed NordVPN references in 4.9.3
