### ISSUE TITLE
PLS HLP! Openvpn Executable isnt working (windows)

### ISSUE THREAD

**Issue by kemotgib** [Zomboided/service.vpn.manager#151]
hello zomboided,

i just dont understand how to fix this. i searched the troubleshooting, but i dont understand the problem with the paths. and i just dont know what i have to search on google. especially i dont understand what means "openvpn must be installed and available on the command path". what ist the command path? the path of kodi.exe? if yes, how to manage to bring the openvpn.exe and kodi.exe in one path?
please give me a tell.

00:28:55.226 T:7136  NOTICE: VPN Mgr : (service.py) Starting VPN monitor service, platform is 1, version is 4.9.3
00:28:55.226 T:7136  NOTICE: VPN Mgr : (service.py) Kodi build is 17.6 Git:20171114-a9a7a20
00:28:55.226 T:7136  NOTICE: VPN Mgr : (service.py) Addon path is C:\Users\Tomek\AppData\Roaming\Kodi\addons\service.vpn.manager\
00:29:05.684 T:7136  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : openvpn
00:29:06.723 T:7136   ERROR: VPN Mgr : (platform.py) Ran openvpn command and it failed
00:29:06.730 T:7136  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
00:29:06.730 T:7136  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end

**Comment by Zomboided** [comment]
Type "setting command path windows" into google. Add the path of the openvpn executable

**Comment by kemotgib** [comment]
Zomboided.......... !!!!! BIG UP!!! 👍  Thx man!!!!! :D
