### ISSUE TITLE
Pidof check not working

### ISSUE THREAD

**Issue by Gaet81** [Zomboided/service.vpn.manager#153]
Hello,

I've tried this add-on version 4.9.4 on a RPI with Arch Linux.
I'm sure that I have pidof because I can use it.
But everytime I run this addon it check for pidof and the check is failing...even if I have it.
It seems in the code that you are searching for the pidof kodi.bin but it doesn't exist in arch linux.
See the screenshot:
![image](https://user-images.githubusercontent.com/22379937/39971154-268450ba-56e6-11e8-9dde-f4c49600a2e2.png)

Let me know if you want me to do any further test.

Regards,

Gaet81

**Comment by Gaet81** [comment]
Argh...in the meantime I've dowloaded from the repository and this one is working fine. I've upgraded to the latest release but don't have this pidof check as the config file is already there...I'll let you know if I have issue when using it.

**Comment by UPRHome** [comment]
Is there something else happening with the 4.9.5 release? I've noticed now that all systems that are using this addon now automatically run the set-up wizard every time the system is rebooted

**Comment by Zomboided** [comment]
Working as designed.  It'll stop offering if you set it up.  If you don't want to run a VPN, disable the add-on

**Comment by UPRHome** [comment]
Curious. So it is by design to now run the wizard each reboot if the addon is enabled ... it never did that before

**Comment by Zomboided** [comment]
I wanted it to work like that.  If you don't run a VPN, uninstall the add-on

**Comment by Zomboided** [comment]
Fixed this by disabling the check, opened a new issue to track reintroducing this in a different way
