### ISSUE TITLE
Stucked on Connected,checking loc info.

### ISSUE THREAD

**Issue by Bubus12** [Zomboided/service.vpn.manager#158]
I have IPVANISH, all my credentials are working. As I try to connect to whatever location I get Connected,checking location info.
I will attach a pic of the log.
Hope you can help me.
Best
![20180519_100606](https://user-images.githubusercontent.com/39439042/40270094-105573f8-5b4d-11e8-9d28-35dbcbf35a24.jpg)

**Comment by Zomboided** [comment]
The log shows that it's connected fine, so it's more than likely an issue with your DNS servers not being updated (which is outside of the remit of this addon).  See here
https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#dns-issues
