### ISSUE TITLE
"killall" test fails, even with a working "killall", if the system language localisation is set not to english.

### ISSUE THREAD

**Issue by gissuer0815** [Zomboided/service.vpn.manager#159]
https://github.com/Zomboided/service.vpn.manager/blob/7ea32f87273e8d1a3620e38ddaf2b51873135d0a/libs/platform.py#L371

Because of looking for "no process"  it will fail on all non english system language localized outputs even if killall is working properly.

**Comment by Zomboided** [comment]
THis is a really good point, thanks for raising it.
If you enter 'killall vpnmanagertest', into your non-English system, what do you see come back?  Does the line always with "killall:" ?

**Comment by Zomboided** [comment]
Actually, I'll just fix this by checking for 'vpnmanagertest' as if the command exists, then no matter what the other text is, this should always be in the line.  Once again, thanks for raising.
