### ISSUE TITLE
PureVPN connection not working on LE 7.0.2

### ISSUE THREAD

**Issue by Anjerlaan** [Zomboided/service.vpn.manager#16]
Hi,

I am having a problem with the VPN Manager with PureVPN connection. Login details and First VPN Connection (UDP) are set and are valid, but a very slow connection (buffering constantly) in add-ons or add-on crashes, update errors, etc. 

As soon as I delete the VPN Manager, everything is smooth and working again.

I have Installed VPN Manager on top of my existing LE 7.0.2 System
Network setup is Router(DD-WRT) behind Router/Modem (Cisco from ISP)

These are my kodi and openvpn error logs after fresh restart
[Logs.zip](https://github.com/Zomboided/service.vpn.manager/files/653294/Logs.zip)

I have read on forums that "ERROR: Linux route add command failed: external program exited with error status: 2" might be an indication that something is wrong

When I perform an "curl ipinfo.io" to get the RPi's outside ip address, it is refering to "206.123.147.98" which is the IP of the first VPN Connection (UDP) in the VPN Manager, but I can't see this IP in the openvpn.log the closest one is 206.123.147.97

Any idea what cause these problems?

**Comment by Zomboided** [comment]
I'm not seeing any obvious issues in the log, and other users are using PureVPN on the same level of code as you with out issues,  As a guess I'd say that the error you're seeing is related to the way your network is set up, but maybe it doesn't matter as your external network IP address appears to change.  

If you can demonstrate that using openvpn from the command line to establish the connection with a VPN provider supplied ovpn then I'd be happy to take a look at where it differs to the one I'm using.

Regarding the performance of the link, that's between your network config, your ISP and your VPN provider.  I'd expect some drop in speed when you connect but not to the level that you seem to be seeing.  Maybe if you're totally out of luck, try another VPN provider.
