### ISSUE TITLE
PureVPN

### ISSUE THREAD

**Issue by usphil** [Zomboided/service.vpn.manager#160]
Hi, 
How can i use PureVPN with VPN Manage? Their plugin is poor, it does not support many things like OpenVPN Manager. 
Please show me if you have any way to manual install this.
Thank you!

**Comment by Zomboided** [comment]
I removed pure support because their service was utter shite and their customers expected me to fix it.  You can use user defined, instructions are on the wiki, but I want nothing to do with any issues. Good luck, get a VPN provider that actually protects you.

**Comment by rohan-purevpn** [comment]
@usphil Please accept our sincere apologies for the inconvenience. We would like to help you resolve the problem and address your query. Please email your issue in detail to enquiry@purevpn.com. Please mention GitHub in the subject line.
Thank You
