### ISSUE TITLE
2 providers for setting

### ISSUE THREAD

**Issue by usphil** [Zomboided/service.vpn.manager#161]
Can I use 2 providers same time?
I want to use Vietnam VPN server on PureVPN, because it's very fast while UK and US are very unstable.
So I want to use PIA for UK and US servers, PIA doesn't have VN VPN server . 
Is it possible? If yes, could you please show me how?
I am very appreciated about User Defined instructions

**Comment by Zomboided** [comment]
Take the ovpn files from crappy Pure and PIA for the locations you need and use them with user defined.
