### ISSUE TITLE
Celo server update

### ISSUE THREAD

**Issue by fixitkid** [Zomboided/service.vpn.manager#162]
Celo advise they have altered their servers in last few weeks, these no longer apparently require key cert pairs. Forcing extraction from ovpn files causes failure.

**Comment by Zomboided** [comment]
Can you attach the Linux and the openvpn profiles from here https://celo.net/members/downloads/1/OpenVPN-Server-Confguration-Files
And I'll do the update

**Comment by fixitkid** [comment]
Hey, don't think I can but as vpn manager is quoted in their official guide sure they will supply it.

**Comment by Zomboided** [comment]
Thanks, fixed in 4.9.9
