### ISSUE TITLE
Express VPN Auth_Failed

### ISSUE THREAD

**Issue by coolartfj** [Zomboided/service.vpn.manager#163]
Hi Support

 Running VPN Manager on OPEN VPN on OSMC on KODI 17.6

I have a express VPN account tried to sign in using it followed few guides 

https://thevpn.guru/install-zomboided-kodi-17-vpn-addon 

got details from my account key and cert with user and pass but getting error below

Auth_Failed
soft.auth-failure

any help would be really appreciated

Thanks

**Comment by Zomboided** [comment]
You're using the wrong credentials, either password or key...dunno what else to say really
