### ISSUE TITLE
Stuck on connecting to first VPN

### ISSUE THREAD

**Issue by cognitiaclaeves** [Zomboided/service.vpn.manager#164]
Trying to set up VPN (NordVPN) as a custom VPN for Kodi (non-elect) running in retropi 4.14.34-v7+ #1110.

Everything seems fine until it gets to this point:
Connecting to first VPN
Setting up VPN provider UserDefined (please wait) ...

I am able to manually connect to the vpn by SSHing into the retropie and running openvpn with a profile.

When I look at the OpenVPN log, I see:
cat /opt/retropie/configs/ports/kodi/temp/openvpn.log
OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017

General Options:
--config file   : Read configuration options from file.
--help          : Show options.
--version       : Show copyright and version information.

...

... as if the command may not have been executed correctly.

I'm not sure where to find any other logs.

**Comment by Brian-Milnes** [comment]
Yep, me too.
I uninstalled and reinstalled
(using PIA config)
But gets stuck at Connecting to VPN 
Connected, checking location info...)

**Comment by Zomboided** [comment]
@Brian-Milnes did you read the message that came back, or follow any of the suggested resolutions on the wiki?  Your problem is not the same as the OP and is well documented.  If you still think you have a problem and it's NOT because your OS is not setting the DNS correctly, raise a new issue.

@cognitiaclaeves Use the user defined wizard.  I'm guessing you're just setting user defined and then trying to connect - you need to supply the ovpn files - that's the point of user defined.  This is documented on the wiki too

**Comment by Brian-Milnes** [comment]
Thanks @Zomboided 
I've been through the Wiki now
Which troubleshoot/advice are you recommending?

**Comment by cognitiaclaeves** [comment]
@Zomboided, I used the wizard. I think the issue is that there are 8700 files that ship in NordVPN's zip file from here: https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip .

It's actually not stuck, but it looks like it is because something the add-on is doing is resulting in 8700+ lines that look like this:
DEBUG: VPN Mgr : Processing file /home/pi/.kodi/addons/service.vpn.manager/UserDefined/us1687.nordvpn.com.tcp.ovpn

Before I could figure that out, I had to start over with installing the addon, and when I did, it complained that it couldn't write the log. I found other issues that pointed to setting the debug log on in system settings and always using the kodi log. When I figured out which log it was writing to, I found it trying to process what will be 8700+ config files.

What is this processing step? How often does it happen? I'm guessing that these configs will be populated in a drop-down somewhere. Is 8700+ entries in a drop-down going to cause issues?

**Comment by Zomboided** [comment]
It copies and updates all the files that you give it to work with the addon. I can imagine this would take a long time to complete. Give it just the files you need. I have no idea whether 8000 items In a menu will be a problem or not. It's not gonna be useable tho.

Support for Nord will return sometime soon anyway using their API which avoids this vast number of files and the way that Nord update them continuously.

**Comment by Zomboided** [comment]
Closing this because I don't think there's a problem with the import, and for user defined it's up to the user to make it work. If there is an import problem, provide a log
