### ISSUE TITLE
Compatibility with Custom OpenVPN config

### ISSUE THREAD

**Issue by rubenkr** [Zomboided/service.vpn.manager#168]
Hi there,

thank you for the great application

I created my OpenVPN on my VPS with [Easy oVPN setup script](https://github.com/Nyr/openvpn-install). This results in one single .ovpn file. Despite the .ovpn file is working on my MacOSX with app "tunnelblick", it is not working with [OpenVPN Manager](https://github.com/Zomboided/service.vpn.manager). I thought this might be to the fact that other files (crt,key files) are required. So I created them manually according the the [OpenVPN manipulation](https://gist.github.com/Morley93/9697578). Without any luck the log file keeps telling me:

```
14:44:44.460 T:1857024928  NOTICE: VPN Mgr : (userdefined.py) Updating /storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/c
14:44:44.568 T:1857024928  NOTICE: VPN Mgr : (userdefined.py) Copying /storage/backup/openvpn/client.ovpn to /storage/.kodi/userdata/addon_
14:44:44.569 T:1857024928  NOTICE: VPN Mgr : (userdefined.py) Updating /storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/c
14:44:56.591 T:1857024928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--     
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                               
                                            Error Type: <type 'exceptions.UnboundLocalError'>                                              
                                            Error Contents: local variable 'vpn_username' referenced before assignment                     
                                            Traceback (most recent call last):                                                             
                                              File "/storage/.kodi/addons/service.vpn.manager/addon.py", line 234, in <module>             
                                                wizard()                                                                                   
                                              File "/storage/.kodi/addons/service.vpn.manager/libs/common.py", line 1177, in wizard        
                                                addon.setSetting("vpn_username", vpn_username)                                             
                                            UnboundLocalError: local variable 'vpn_username' referenced before assignment                  
                                            -->End of Python script error report<--                                                        
14:44:59.459 T:1739674528    NONE: VPN Mgr : -- Entered addon.py plugin://service.vpn.manager/ -1 ?display --  
```

It would be great if you could help me how to get my custom OpenVPN working.

Thank you so much !

Update: The configuration script of VPN does not require a username - only a password for .pem file was required. So maybe this is one root of the problem.

**Comment by Zomboided** [comment]
Well how you get your vpn working with user defined is on the wiki but this looks like a bug I need to fix first

**Comment by Zomboided** [comment]
Updated 5.0.1 with a fix for this problem.  If you're already using 5.0.1, just download and reinstall over the top.  It's not on the repo yet.
https://github.com/Zomboided/service.vpn.manager/releases/tag/5.0.1

**Comment by rubenkr** [comment]
that is really great! can I donate you with bitcoin - hand over your address?! Keep your work up. cheers

**Comment by Zomboided** [comment]
It's all good dude, I don't do bitcoin, but feel free to chuck some at the
Kodi devs, they're the ones that really deserve this.
