### ISSUE TITLE
Windscribe Support?

### ISSUE THREAD

**Issue by yegors** [Zomboided/service.vpn.manager#17]
Hello,

Is it possible to add Windscribe (https://windscribe.com) support?

**Comment by Zomboided** [comment]
Added to the list of future items but they don't provide their openvpn files without getting an account so I don't know this will happen anytime soon.

**Comment by yegors** [comment]
I'm the founder of the above mentioned service. Can you give me your email, I'll send you the configs + a test account.

**Comment by Zomboided** [comment]
Sure, can you send me (zomboided) a private message on the LibreELEC forum please, I'd rather not share my email here.  Thanks

**Comment by yegors** [comment]
I can't register there as registration is broken: http://openelec.tv/forum/23-feedback/82908-register-page-broken-captcha-is-not-displayed

You can email me from a disposable email if you like, yegor@windscribe.com
