### ISSUE TITLE
Issue with validate VPN Service Provider

### ISSUE THREAD

**Issue by Josefh90** [Zomboided/service.vpn.manager#171]
Hey,

the validate VPN-Provider in the OpenVpn-Manager list is missing a few Providers like SpyOFF whitch is already listed in the service.vpn.manager.providers-master.zip. Can i solve the issue on my own or is there already an update vor the list.
Thanks a lot Josefh
![issuevpnprovider](https://user-images.githubusercontent.com/41289732/42755107-46b4793a-88f7-11e8-9036-ac9aefdfa1f7.PNG)

**Comment by Zomboided** [comment]
All of the supported and tested providers have been added.  If there's a provider that's not included, you need to use User Defined
