### ISSUE TITLE
DNS fix dont work on system with arm CPU

### ISSUE THREAD

**Issue by spawnlmg** [Zomboided/service.vpn.manager#173]
DNS fix dont work on system with arm CPU.

**Comment by spawnlmg** [comment]
In the arm system there is no bash, there is only ash. Is it possible to do something?

**Comment by Zomboided** [comment]
Write your own up/down scripts to do whatever is needed on the base OS you're using. I'm not gonna fix this for the semi infinite number of possible kodi installs
