### ISSUE TITLE
kodi mobile app interaction

### ISSUE THREAD

**Issue by Githeo** [Zomboided/service.vpn.manager#174]
Hi,
thanks for your work! It became far easily to connect to a VPN right now.
Anyway since the first connection the kodi mobile app for the remote control doesn't want to connect to kodi anymore. Apparently the openvpn uses the same port as kodi 8080:

```
$ sudo ss -lptn 'sport = :8080'
State      Recv-Q Send-Q                           Local Address:Port                             Peer Address:Port 
LISTEN     0      5                                    127.0.0.1:8080                                        *:*      users:(("sudo",pid=7098,fd=62))

$ ps aux | grep 7098
root      7098  0.0  0.0   4476   460 ?        SN   Aug11   0:00 sudo /usr/sbin/openvpn /home/osmc/.kodi/addons/service.vpn.manager/PIA/Ireland (UDP).ovpn
```
I didn't find any port settings in your code. How can I specify a different port so that I don't have to change the default kodi port?

Thanks.

**Comment by Zomboided** [comment]
PIA connects to 1197 or 1198 for UDP and 443 for TCP.  I don't do anything
within my addon to determine which port it goes out on.

**Comment by Zomboided** [comment]
Closing this as it's not something this addon forces
