### ISSUE TITLE
Potential DNS fix on systemd enabled platforms

### ISSUE THREAD

**Issue by Raylan189** [Zomboided/service.vpn.manager#175]
This advanced feature does not work on Ubuntu 18.04 (Bionic Beaver) which uses the systemd-resolved service. There are two different problems:

1) Contents of "APPEND.txt" file
Most important is the fact that the following entry is required:
-) dhcp-option DOMAIN-ROUTE .
Otherwise the DNS leak test provided by "dnsleaktest.com" fails. It shows the DNS of the VPN, but also the DNS of my ISP which is wrong. On the other hand, overriding the PATH variable is not required on my system, but does not harm.

2) Script location
On my Ubuntu system both scripts are located in the same directory:
a) /etc/openvpn/update-resolv-conf
b) /etc/openvpn/update-systemd-resolved
The first script comes with the "openvpn" package und thus is always present. The second script has to be installed afterwards with the following command:
-) sudo apt install openvpn-systemd-resolved
If the second script is present, you can be sure that the system uses the systemd-resolved service. Nevertheless the logic in your addon is vice versa. It only uses the second script if the first one does not exist. This makes no sense because as I already mentioned the first one cones with the "openvpn" package and thus always exists. I had to rename it manually in order to activate the systemd-resolved branch in your code.
I also observed that your addon always expects the second script in the "scripts" subdirectory although it was installed in the upper directory on my system.
The conclusion from this is that you should first check for "update-systemd-resolved" (maybe in both directories) and then for "update-resolv-conf".

**Comment by Zomboided** [comment]
Thanks, I had been making some changes in this area and this is useful info.  I think your conclusion is correct, although I had been considering also checking in the kodi user directory to deal with some really funky installs.

**Comment by Zomboided** [comment]
Fixed in 5.0.4.   Feel free to check it out and let me know if it works on your system as I have no real way of testing this

**Comment by Raylan189** [comment]
Thank you very much your quick response.
Part 1 of my request (append file contents) works great (no longer DNS leaks).
Unfortunately part 2 (script location) does not work as expected.
As I suggested your addon now checks for both files:
 -  /etc/openvpn/update-systemd-resolved and
 -  /etc/openvpn/scripts/update-systemd-resolved,

but these files are only used if the default one
 -  /etc/openvpn/update-resolv-conf

does not exist. I still had to rename it manually before I called the potential DNS fix option in your addon. Maybe this behavior is required for backward compatibility and/or other platforms. On my Ubuntu system it prevents the respective advanced option from working out of the box.

**Comment by Zomboided** [comment]
You're right, I screwed that bit up.  Changed the order in 5.0.5 to make more sense.

**Comment by Raylan189** [comment]
Thank you very much for the new release 5.0.5. I have tested the DNS fix option on both of my systems
- Raspbian stretch (arm) with resolv.conf file,
- Ubuntu 18.04 (x64) with systemd-resolved daemon

and it now worked out of the box as expected. For my VPN provider NordVPN (still configured as User Defined despite your changes) this option is necessary if I want to use the original configuration files.

**Comment by Zomboided** [comment]
Ok good, thanks for letting me know.  I think the fix will work with Nord too...it's been a while since I wrote that code so I can't quite remember :)
