### ISSUE TITLE
DNS Error

### ISSUE THREAD

**Issue by orabas** [Zomboided/service.vpn.manager#176]
Hi,

Im experiencing what seems to be a common error. I am using NordVPN and trying to connect to any server but it hangs on the location info at the end then errors. 

I've tried different providers but I get the same error. Switching from TCP to UDP doesnt work either. Nor does turning off my firewall on router. 

I have tried the potential DNS fix but that also didnt work. 

Any help appreciated. 

Snippet from log:

12:12:37.056 T:1694495488  NOTICE: VPN Mgr : (platform.py) Checking platform, found 2, linux2
12:12:38.045 T:1694495488  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : sudo /usr/sbin/openvpn > /run/openvpn.log 2>&1 &
12:12:39.110 T:1694495488  NOTICE: VPN Mgr : (platform.py) Testing killall with : sudo killall vpnmanagertest > /run/command_text.txt 2>&1 &
12:12:46.063 T:1694495488  NOTICE: VPN Mgr : (vpnproviders.py) Writing default up script
12:12:46.069 T:1694495488  NOTICE: VPN Mgr : (vpnproviders.py) Fixing default up.sh sudo chmod +x /home/osmc/.kodi/addons/service.vpn.manager/up.sh
12:12:46.115 T:1694495488  NOTICE: VPN Mgr : (vpnproviders.py) Copying user defined files from userdata directory
12:12:46.118 T:1694495488  NOTICE: VPN Mgr : (vpnproviders.py) Updating VPN profiles for UserDefined
12:13:35.016 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider ipinfo.io
12:13:35.016 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) API call was http://ipinfo.io/json
12:13:35.017 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Response was <class 'urllib2.URLError'> <urlopen error [Errno -2] Name or service not known>
12:13:35.095 T:1694495488   ERROR: VPN Mgr : (common.py) Didn't get a good response from ipinfo.io
12:14:18.150 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider ipinfo.io
12:14:18.150 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) API call was http://ipinfo.io/json
12:14:18.150 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Response was <class 'urllib2.URLError'> <urlopen error [Errno -2] Name or service not known>
12:14:18.231 T:1694495488   ERROR: VPN Mgr : (common.py) Didn't get a good response from ipinfo.io
12:14:58.391 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider IP-API
12:14:58.391 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) API call was http://ip-api.com/json
12:14:58.391 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Response was <class 'urllib2.URLError'> <urlopen error [Errno -2] Name or service not known>
12:14:58.466 T:1694495488   ERROR: VPN Mgr : (common.py) Didn't get a good response from IP-API
12:15:41.664 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider IP-API
12:15:41.665 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) API call was http://ip-api.com/json
12:15:41.665 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Response was <class 'urllib2.URLError'> <urlopen error [Errno -2] Name or service not known>
12:15:41.737 T:1694495488   ERROR: VPN Mgr : (common.py) Didn't get a good response from IP-API
12:16:21.885 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider freegeoip.net
12:16:21.885 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) API call was http://freegeoip.net/json/
12:16:21.886 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Response was <class 'urllib2.URLError'> <urlopen error [Errno -2] Name or service not known>
12:16:21.960 T:1694495488   ERROR: VPN Mgr : (common.py) Didn't get a good response from freegeoip.net
12:17:05.168 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Couldn't connect to IP provider freegeoip.net
12:17:05.168 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) API call was http://freegeoip.net/json/
12:17:05.168 T:1694495488   ERROR: VPN Mgr : (ipinfo.py) Response was <class 'urllib2.URLError'> <urlopen error [Errno -2] Name or service not known>
12:17:05.233 T:1694495488   ERROR: VPN Mgr : (common.py) Didn't get a good response from freegeoip.net
12:17:05.241 T:1694495488   ERROR: VPN Mgr : (common.py) All services failed with no response, could be a DNS issue
12:17:05.742 T:1694495488  NOTICE: VPN Mgr : (common.py) Connected to a VPN using profile bytesized (UDP), but either there's a DNS issue or some other network problems. You may not be able to access other internet resources until you fix this.
12:17:10.298 T:1686106880  NOTICE: VPN Mgr : (service.py) Updating systemd, connect before boot is false, location is /home/osmc/.kodi/addons/service.vpn.manager/UserDefined/bytesized (UDP).ovpn
12:17:10.312 T:1686106880  NOTICE: VPN Mgr : (platform.py) Disabling systemd service with sudo systemctl disable openvpn.service

**Comment by orabas** [comment]
Worth adding im on Raspberry Pi using OSMC

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#dns-issues

**Comment by orabas** [comment]
looked at that and followed all the steps apart from the APPEND.TXT file section - cant get my head around how I actually do that?

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/10.-Updating-VPNs

It's on this page, although it's not great documentation admittedly

**Comment by Zomboided** [comment]
Closing this because I don't think it's a VPN Mgr problem - the openvpn project don't consider it's their job to kick the DNS, and the fix I put in relies on the availability of scripts.   Also, 5.0.5 has NordVPN support - I'm not sure it'll fix your problem here though.
