### ISSUE TITLE
Error: sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by dylif** [Zomboided/service.vpn.manager#178]
I am attempting to get a VPN upand running on Kodi 17.6 under a clean install of Ubuntu 18.04. When checking for openvpn and killall (the check uses sudo and the setting which can change this takes no effect) it returns the error in the title, thus making it appear as if the openvpn executable is not working. Could this happen due to the way you are launching these checks? I actually edited the source code, forcing all checks to return True, and despite that, when running the openvpn command, it returns the same error.  I believe this could be caused by the way you are accessing the shell.

**Comment by Zomboided** [comment]
You should google the error message. You need sudo to be able to run openvpn, killall and pidof without asking for a password. This isn't an issue with the addon, you can't comment away the checks as it'll just lead to the same failure the first time you use the command
