### ISSUE TITLE
Unable to retrieve location information from VPN provider.

### ISSUE THREAD

**Issue by ALink2ThePast** [Zomboided/service.vpn.manager#179]
I'm retrieving the following error when I try to log into NordVPN:

"Unable to retrieve the locatio ninformation from VPN provider. Check network and then try again. Additional information can be found in the log."

I dug into the logs and this seems to relevant part.

```
11:20:11.438 T:1728050080   ERROR: VPN Mgr : (alternative.py) Couldn't write the list of countries for NordVPN to /storage/.kodi/addons/service.vpn.manager/NordVPN/COUNTRIES.txt

11:20:11.438 T:1728050080   ERROR: VPN Mgr : (alternative.py) [Errno 2] No such file or directory: '/storage/.kodi/addons/service.vpn.manager/NordVPN/COUNTRIES.txt'

11:20:12.460 T:1728050080   ERROR: VPN Mgr : (common.py) Unable to retrieve location information from VPN provider. Check network and then try again. Additional information can be $
```

Anyway, the good news is I was able to get it working by manually making a `NordVPN` folder and `COUNTRIES.txt` file in that location, but this seems like it shouldn't be necessary so I'm still reporting the issue.

**Comment by Zomboided** [comment]
What version of code?  Was this a brand new install, or had you come from a
previous version?

**Comment by ALink2ThePast** [comment]
I'll let you know when I get home tonight since I don't know off the top of my head and don't have the info down to ssh from here, but I installed on Monday night so I'd assume pretty new.

**Comment by Zomboided** [comment]
Yup, that would not have the directory required, which I can see would cause the issues you saw.  Installing a proper released build won't have that problem, plus I fixed this now anyway (in a future release)
