### ISSUE TITLE
User Defined Import Wizard is greyed out after creating the first working connection

### ISSUE THREAD

**Issue by Gitarist2018** [Zomboided/service.vpn.manager#187]
Tested on Windows 10:
After creating my first working connection I have no possibilty to manually import further profiles though I'm warned on every import that all existing connection profile files will be overwritten. The Defined Import Wizard is greyed out.

I tried all reset options under "Utilites" - "VPN Connection Reset Options" but it was still greyed out. After deleting the settings.xml file and UserDefinded-Folder in the "AppData\Roaming\Kodi\userdata\addon_data\service.vpn.manager"-folder I was able to do a new import.

**Comment by Zomboided** [comment]
Once you've connected, you can't change any of the ovpn profiles because it's used the metadata that's generated.  You need to reset the VPN (on the first settings tab) to import more profiles.  This is working as designed.  You didn't need to delete stuff.
