### ISSUE TITLE
Lubuntu pidof

### ISSUE THREAD

**Issue by robbiecsmith** [Zomboided/service.vpn.manager#19]
I have Lubuntu 16.04 with Kodi. pidof returns the process id - non-zero with this distro. This seems to be different to another Linux distro, presumably OpenElec.

In def isVPNTaskRunning(): below line 340
 #This horrible call returns 0 if it finds a process, it's not returning the PID number

I replaced "if pid = 0 : return True" with " if pid > 0 : return True"
as a quick fix on my system.

kind regards Robbie

**Comment by Zomboided** [comment]
Fixed in 2.2.9 which I'm about to upload.  Check the settings/debug options for an alternative task option and set it to true.  Close this out if it works...I've no way of testing

**Comment by robbiecsmith** [comment]
The 2.2.9 alternative task option (set to true) fixed the problem. I tested with debug logging on.

Many thanks, Robbie

**Comment by Zomboided** [comment]
Good news, thanks for reporting back
