### ISSUE TITLE
Keeps asking for killall install though it is installed (linux)

### ISSUE THREAD

**Issue by samta0** [Zomboided/service.vpn.manager#190]
Hi, 

The VPN Manager has been broken on my linux boxes for a few weeks. (Ubuntu 14.04 and Ubuntu 18.04) 

Thus, I tried to reinstall it from scratch, but I keep getting the message that it does not find killall after the dialog box informing that it is checking the dependencies. 

However, if I go to the Advanced in the VPN Manager configuration dialog section and perform the "Reset defaults" action, I don't get the killall message the first time I try to configure a VPN connection; I get instead a message about the log of openvpn. 

killall and pidof are installed in /usr/bin and openvpn in /usr/sbin. 

I tried to follow the instructions of the installation on linux that are online; but it did not help. 

I am using version 5.0.7 of the VPN Manager. 

Could you have a look? 

Thanks in advance.

**Comment by Zomboided** [comment]
Shall I guess what's in your log, or will you be providing one, with debug switched on.

**Comment by Zomboided** [comment]
Sudo expects you to use it with a password, you need to switch that off otherwise the commands will never be allowed to execute. I can't remember how to do this as I'm not a big Linux user.

**Comment by samta0** [comment]
Thanks for the advice about sudo. My setup was indeed configured to handle the sudo password for the openvpn command, but not for the killall command. After handling the sudo password also for the killall command, the problem was solved. 

You might perhaps consider enhancing the killall error dialog with a hint to the sudo password, when it is configured to be run using sudo. 

Thanks again for your help. 

Cheers
