### ISSUE TITLE
Hidester VPN supported

### ISSUE THREAD

**Issue by egi78** [Zomboided/service.vpn.manager#193]
Hi,
I have a subscription on Hidester VPN and I'd like to use it also in Kodi. 
I didn't find it scrolling down the list of supported VPN, therefore I understand Hidester is not supported. 
Do you think to add it in the close future?
Can I set up it anyway?
Thanks, Egi

**Comment by Zomboided** [comment]
I've limited interest in adding additional providers because of the effort to maintain.  You can use the User Defined wizard, or read the instructions on the wiki to use unsupported providers.  You'll need to debug any issues yourself.
