### ISSUE TITLE
4-us.cg-dialup.net not resolving to an IP address for CyberGhost

### ISSUE THREAD

**Issue by Rippert** [Zomboided/service.vpn.manager#194]
VPN Manager won't log into my CyberGhost account for the last couple days. The VPN log shows that it is unable to resolve 4-us.cg-dialup.net to an IP address. When I use dig in a terminal I also can't get an IP address. 

The CyberGhost website says to use 1-us.cg-dialup.net, and that does resolve to an IP address using dig. I can't find any way to change the address VPN Manager is using, I suspect it is hard coded somewhere.

**Comment by Zomboided** [comment]
Fixed, you should see a notification telling you there's an update sometime in the next day or so
