### ISSUE TITLE
ExpressVPN don't show all Servers

### ISSUE THREAD

**Issue by lafreak88** [Zomboided/service.vpn.manager#195]
Hallo

I am trying to connect to ExpressVPN to server Nurnberg (germany), it's the only one Netflix Germany is working with. But when i set up this VPN and connect, I can't selct this server, because it's not in the list. 

I can connect to it with their own tool without problems,but with this add on it would be much easier. 

When I Import the openvpn file for this server, i get an error, but thats another topic.

Any idea? or need more info? Let me know

Regards
Christoph

**Comment by Zomboided** [comment]
https://www.expressvpn.com/support/vpn-setup/manual-config-for-dd-wrt-router-with-openvpn/#download

Go here, get me all of the German ovpn files and attach them there and I'll
update.  The German locations I'm using appear to have changed.

**Comment by lafreak88** [comment]
Thanks

Here you can find the file for Nurnberg
http://cloud.jodexnus.de/index.php/s/Ht49zmzR4fc6EEm

The others seem te work, just don't work with netflix.

**Comment by Zomboided** [comment]
Thanks, do all of the others that exist today still connect?

**Comment by lafreak88** [comment]
the german ones seem to work yes. this one was the only one which isn't in the list

**Comment by Zomboided** [comment]
Ok, fixed, you should see an update notification sometime in the next day or so.  And your import problem was with the same ovpn?  I can run that myself and see if it's working if it is

**Comment by lafreak88** [comment]
perfect thanks

yes, was with the same file
