### ISSUE TITLE
repository

### ISSUE THREAD

**Issue by bbypnda** [Zomboided/service.vpn.manager#20]
Attempting to retrieve vpn manager zip to install on kodi Apple TV 4, used repo:

https://github.com/Zomboided/repository.zomboided.plugins/releases/tag/1.0.0

Open this in file manager and no zip to be found, won't open Zomboided folder. What am I doing wrong?

Thank you for your awesome product.

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation#repository-install
