### ISSUE TITLE
Pure VPN servers 

### ISSUE THREAD

**Issue by roar1984** [Zomboided/service.vpn.manager#21]
Hi Zomboided,
recently I have had problems with the connection choice of Italy servers in Pure VPN
Searching in their site I have found new addresses, actually not yet present in your release
Trying to solve I have changed them in Libreelec, editing in stotage\.kodi\addon\service.vpn.manager-master\PureVPN\LOCATIONS.txt and then overwriting in stotage\.kodi\addon\service.vpn.manager\PureVPN\  files ITALY (UDP).ovpn and ITALY (TCP).ovpn with the new files I've found in PureVPN site
It seems to work fine, but I'm afraid of loose them with an automatic addon update, so I've disabled it
Could you please take a look and update PureVPN server connections in your next release deploy?
Many thanks for your splendid and really complete work
Greetings from Italy
Guido

**Comment by Zomboided** [comment]
Yup, I think I was heading towards that in a release in the next couple weeks anyway.

**Comment by Zomboided** [comment]
Checked in latest, will be in next release

**Comment by jeremyj29** [comment]
Hi !

There is also a problem with UK Servers :

**Only one London with several server behind :** 
UDP : ukg1-ovpn-udp.pointtoserver.com 
TCP: ukg1-ovpn-tcp.pointtoserver.com
**Gosport :**
UDP :  ukg1-ovpn-udp.pointtoserver.com	 
TCP : ukg1-ovpn-tcp.pointtoserver.com	
**Maidenhead :** 
UDP : ukm1-ovpn-udp.pointtoserver.com
TCP : ukm1-ovpn-tcp.pointtoserver.com	
**Manchester :** 
UDP : vlus-uk-man1-ovpn-udp.pointtoserver.com 
TCP : vlus-uk-man1-ovpn-tcp.pointtoserver.com
**Leicester :** 
UDP : vlap-ukle1-ovpn-udp.pointtoserver.com 
TCP : vlap-ukle1-ovpn-tcp.pointtoserver.com

Thanks in advance, this addon is so usefull !
Best Regards
Jeremy
