### ISSUE TITLE
failed to find definition for setting labelxxx

### ISSUE THREAD

**Issue by exxelon** [Zomboided/service.vpn.manager#210]
Hello.
When troubleshooting another problem I found the following entries in the log file.
In the user interface I see that I am connected, but the log file irritates me. 

[Log File](https://paste.ubuntu.com/p/kw34wbGm4Q/)

What is it about?

Greetings.

**Comment by Zomboided** [comment]
It's about the re-write of the settings code in the Kodi beta you've chosen to use being unstable.  When the Kodi devs put out a final version of the code, and they describe why the settings that are currently 'legal' are wrong, then I'll look at fixing it.  You should share your irritation with someone else as I'm going to do nothing about this.
