### ISSUE TITLE
Nord VPN provider not in list of supported providers

### ISSUE THREAD

**Issue by peno64** [Zomboided/service.vpn.manager#213]
This is just a small note.

In the wiki (https://github.com/Zomboided/service.vpn.manager/wiki) there is no mention of Nord VPN support in the Supported VPN providers list. However according to the releases Nord VPN support is there (again) from version 5.0.5

So it would be nice to have this provider again added to the wiki.

I have Nord VPN and I can confirm that it works fine with the latest 5.0.7 version.

Thank you and have a good new year

**Comment by Zomboided** [comment]
Thanks! Fixed
