### ISSUE TITLE
[Enhancement] Add support for NordVPN special type servers

### ISSUE THREAD

**Issue by meden** [Zomboided/service.vpn.manager#215]
Hello,

I'm trying to use NordVPN with your (great) plugin, but there is no way to select a server type:
![image](https://user-images.githubusercontent.com/824351/50735415-f726af00-11ae-11e9-8eab-f8888efc02de.png)

It would be great having this ability.

Thank you for your work!

**Comment by Zomboided** [comment]
Hello, Nord supported the integration with their service and what you see is what they wanted. Your use case would be uncommon for kodi streaming I think so I guess this is why they weren't interested in having all of the servers. 

You can work around this by using user defined and downloading the ovpn files for the locations you're interested in from their website

**Comment by meden** [comment]
Thanks for answering. Regrettably, on `ovpn` files made available by NordVPN do not include special servers (and namely obfuscated servers). I'll stick with Android and the official app, rather than Linux.

**Comment by shillshocked** [comment]
his is the official download link for the configs for the obfuscated servers
http://downloads.nordcdn.com/configs/archives/servers/ovpn_xor.zip
there are special options in the config files
like scramble obfuscate

But you have to install a special scrambled version of openvpn to make this work:

https://github.com/search?q=openvpn+scramble

**Comment by meden** [comment]
Thanks again for the valuable information, although It's unlikely that I will recompile OpenVPN. BTW, it would be impossible on Android (well, a PITA...) and LibreElec seems to be quite locked down too. I was looking for something quick and user friendly, but it seems I'll have to wait at least that OpenVPN scrambling support gets up-streamed (if it will ever happen).

But good to know that there is a way to use system VPN software instead of only their proprietary client (which works well, but does not have a GUI, nor an integration with NetworkManager).

Thanks again!
