### ISSUE TITLE
Update-resolv-conf missing

### ISSUE THREAD

**Issue by RichardBeaudelaire** [Zomboided/service.vpn.manager#217]
Hi all,
I'm trying to configure vpn manager with user defined for proton vpn and i'm having an issue at the very end of the vpn connection. Connection fail and when i look the log it's tell the is no such a file as update-resolv-conf.
I'm on libreelec 9 and kodi 18 on Rpi3b+
I've done some research but i can't solve my problem yet, i understand this file ( that solve dns request) is missing but what can i do ? Obviously i'm a linux newbie and that's my very first step with de rpi

**Comment by Zomboided** [comment]
I have no appetite to debug other providers, but good luck.  Here's my thoughts on using this kinda script, on the Github wiki.

https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#dns-issues

https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#potential-dns-fix-linux-only

I have not used LE9, but LE8 did include either script.  You should determine if you need to run it and if not, remove it.  You could also try running it on the command line and getting help from your provider.

**Comment by jarandaf** [comment]
I also faced this issue and solved it by commenting the up/down lines in the OpenVPN config file. The error is caused because `/etc/openvpn/` path does not exist in the LibreELEC file system.

**Comment by FranciscoJoseLeon** [comment]
I noticed Proton OpenVPN user defined files for TCP do not have the script that appears on UDP files:
`script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf`

Using Proton TCP config files instead UDP it works fine
