### ISSUE TITLE
Don’t save connection and can’t choose sexond one

### ISSUE THREAD

**Issue by matxino** [Zomboided/service.vpn.manager#218]
I’ve tried to connect to first vpn cybergosht option and before success it not save the option and can’t introduce secon vpn location in vpn connections. I’m trying in kodi 18.
This is my log.

22:56:43.220 T:1035441008  NOTICE: VPN Mgr : (service.py) Updating systemd, connect before boot is false, location is /storage/.kodi/addons/service.vpn.manager/CyberGhost/Spain (UDP).ovpn
22:56:43.242 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#vpn_provider_update"
22:56:43.243 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#1_vpn_validated_friendly"
22:56:43.245 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#vpn_provider_update"
22:56:43.245 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#1_vpn_validated_friendly"
22:56:43.261 T:1035441008  NOTICE: VPN Mgr : (platform.py) Disabling systemd service with systemctl disable openvpn.service
22:56:48.447 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#vpn_custom"
22:56:53.047 T:1937661968 WARNING: Previous line repeats 1 times.
22:56:53.047 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#vpn_provider_update"
22:56:53.048 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#1_vpn_validated_friendly"
22:56:53.051 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#vpn_provider_update"
22:56:53.052 T:1937661968 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#1_vpn_validated_friendly"

**Comment by Zomboided** [comment]
I'm not interested in debugging problems I'm kodi 18 not storing settings correctly. I'd be happy to look at a FULL debug log and not just the bit you think are important if this is happening on a non beta release
