### ISSUE TITLE
LE9 (stable) LE menu does not open when VPN manager's auto connect on startup is on

### ISSUE THREAD

**Issue by fate8383** [Zomboided/service.vpn.manager#221]
LE9 (stable) LE menu does not open when VPN manager's auto connect on startup is on. Is this LE problem or VPN manager causing it? If I turn off auto connect on startup and reboot RPI then LE menu opens as normal.

**Comment by fate8383** [comment]
[logs.rtf.zip](https://github.com/Zomboided/service.vpn.manager/files/2842186/logs.rtf.zip)
here are the logs when I try to open LE9 settings, it seems like VPN service has some conflict with this based on the window ID. I am totally guessing, of course, you are the expert. When I disable autostart connect VPN on startup then LE9 settings window open as normal. I am on RPI3 LE9. Thanks

**Comment by Zomboided** [comment]
I can't read these logs.  Upload the .log file without zipping them up or processing them in any other way.
