### ISSUE TITLE
Best VPN service 

### ISSUE THREAD

**Issue by jepe63** [Zomboided/service.vpn.manager#223]
Hi , i'm using PureVPN at the moment , but because it's crap on CoreElec i was wondering wich service you recommend ?
Thx for your advise
Werner

**Comment by Zomboided** [comment]
I've not tested the majority of them to any great degree.  I've got a paid subscription to PIA just ebcause it was the one that my mates were using when I started looking at this.  I'm not sure I recommend as it's not great working around geolocking.  I also don't use CoreElec.

You're better off asking on forums for experiences that others have.

You're description of PureVPN is right tho.  Horrendous, clueless service.
