### ISSUE TITLE
Kill switch suggestion

### ISSUE THREAD

**Issue by Gitulu** [Zomboided/service.vpn.manager#224]
Hello,

First your VPN tool is amazing and I use it on my Raspberry Pi 3B+ with Libreelec RR 9.1, thanks a lot.
I tried to add a kill switch directly to the iptables and drop all traffic. Just only allow the VPN provider Input and Outgoing port. But on Libreelec I have no permission to change this.

Liquidvpn goes a different way and remove the gateway during the connection. So if the VPN connection get lost the fallback is to an deactivated gatway. You can find the tool here: "https://www.liquidvpn.com/vpn-kill-switches/" and see the code after download.

So maybe you can find a way to do it via iptables or gateway?

Thanks a lot, I hope we can find a way to make this great tool ultimate.

Cheers
Gitulu

**Comment by Zomboided** [comment]
Why no permission?  Were you trying to do it permanently, or via and up/down script?
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#enable-updown-scripts

**Comment by Gitulu** [comment]
Hello,
I tried to do it directly via SSH ("/etc/iptables/").
Until now I was not aware about the up/down script, thanks.

**Comment by Zomboided** [comment]
If you make it work, post up the recipe and I'll see if it's something I
can incorporate across all providers

**Comment by Zomboided** [comment]
Did you find a way to make this work?
