### ISSUE TITLE
Can't add addons to Add-on Filter in kodi 18

### ISSUE THREAD

**Issue by sonofdibnah** [Zomboided/service.vpn.manager#225]
I've just installed 6.1.0 in CoreElec (Kodi 18). I also use it in Libreelec (Kodi 17.6). In Kodi 18, I'm unable to add any addons to the Add-on Filter. I've cheated by copying the settings.xml from kodi 17.6 and can confirm that the filters work but they are not displayed in the settings panel.

I get the same behaviour if I try the panel in android Kodi 18 on my phone.

**Comment by Zomboided** [comment]
Yeah I raised a Kodi bug for this.  If you have a multi selection, it doesn't display anything, but the settings persist (ie it works).  If you have a single selection list, it also displays the selected value.
I'm not planning on fixing this as I think Kodi need to revert the behaviour to what it was in 17.
You don't need to edit XML, etc, this is just a display problem, filters still work fine.
