### ISSUE TITLE
Display enhanced information doesn't show the connected vpn server anymore

### ISSUE THREAD

**Issue by peno64** [Zomboided/service.vpn.manager#226]
In version 5.0.7 the enhanced information window showed the server to which it was connected. See attached printscreen screenshot014.png (Server is be51.nordvpn.com)
In version 6.0.2 this server isn't shown anymore and that is really a pitty.
It is now more difficult to see to which server the vpn is connected and something I need this info. For example to report a server with a problem or to whitelist it on some services.
Could you please add this information again in the future?

Attached screenshot 14 is with v5 and screenshot 13 is with v6

Thank you

![screenshot014](https://user-images.githubusercontent.com/32430988/53286083-504f9f80-3769-11e9-81cd-fec49bc19983.png)
![screenshot013](https://user-images.githubusercontent.com/32430988/53286087-59407100-3769-11e9-927b-7104e4cd9d8d.png)

**Comment by padraigdoran** [comment]
Yes, I'd vote for this option be reinstated also. Before I could see that the VPN was connected on a specific server and could us my phone/laptop to connect to the very same server to run speed tests and such if I needed to, or to authorise that IP address to connect to services.

**Comment by padraigdoran** [comment]
Putting this here for reference. It is a list of API calls that may be useful for NordVPN server number and IP address matching.


# Detailed info about all servers
https://nordvpn.com/api/server

Snipet of the returned JSON

`{"id":931232,"ip_address":"196.196.193.108","search_keywords":["sha512","P2P"],"categories":[{"name":"Standard VPN servers"},{"name":"P2P"}],"name":"Ireland #34","domain":"ie34.nordvpn.com","price":0,"flag":"IE","country":"Ireland","location":{"lat":53.333055600000002,"long":-6.2488888999999999},"load":23,"features":{"ikev2":true,"openvpn_udp":true,"openvpn_tcp":true,"socks":true,"proxy":true,"pptp":false,"l2tp":false,"openvpn_xor_udp":false,"openvpn_xor_tcp":false,"proxy_cybersec":true,"proxy_ssl":true,"proxy_ssl_cybersec":true,"ikev2_v6":false,"openvpn_udp_v6":false,"openvpn_tcp_v6":false,"wireguard_udp":false,"openvpn_udp_tls_crypt":false,"openvpn_tcp_tls_crypt":false}}`

# Current server load for all servers
https://nordvpn.com/api/server/stats

# Current server load for specified server
https://nordvpn.com/api/server/stats/ie34.nordvpn.com

# List of NordVPN DNS nameservers
https://nordvpn.com/api/dns/smart

# User's IP address reported by NordVPN
https://nordvpn.com/api/user/address

# OpenVPN config files for all servers    
https://api.nordvpn.com/files/zipv2

**Comment by peno64** [comment]
Because it took so long before there is a new version and I really want this feature, I added it again by modifying the code. You can find it on http://users.telenet.be/peno/kodi/addons/zomboided/
Install the addon from the zip found there and it will show the info again.

**Comment by padraigdoran** [comment]
Could you publish the modified code, or push a pull request. I can't seem to connect to the link you gave.

**Comment by peno64** [comment]
The link does work. I just tried it. 
Here is a google drive link to the zip file: https://drive.google.com/file/d/1MTGL-5JqoQNvFwb03EAzbMRtgc9OSNxE/view?usp=sharing

**Comment by padraigdoran** [comment]
Thanks, I got that. I will check it later on.

**Comment by padraigdoran** [comment]
That worked thanks. It's is version 6.0.2 though.
Have you a patch for 6.1.0 - https://github.com/Zomboided/xbmc.zomboided.plugins/tree/master/plugins/service.vpn.manager

**Comment by peno64** [comment]
Strange...

I get my version from
https://github.com/Zomboided/service.vpn.manager/releases

And there 6.0.2 is the latests version.

P

**Comment by padraigdoran** [comment]
Yes, in this repo the latest is 6.0.2 but if you install the Kodi Repository ([here](https://github.com/Zomboided/repository.zomboided.plugins/releases/tag/1.0.0)) from the Zomboided instructions ([here](https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation)) then the version is 6.1.0 (i.e. it points to the link I gave above)

**Comment by peno64** [comment]
Making a difference between the sources of 6.0.2 and 6.1.0 shows some more changes but they are minimal.
I implemented my changes in 6.1.0 and will test it first before posting it.

**Comment by peno64** [comment]
It's looking good with this 6.1.0 version. You can download it here: https://drive.google.com/file/d/17JH0bxrxpYJFD_D32icOVrPHfrolIMV_/view?usp=sharing

**Comment by padraigdoran** [comment]
> 
> 
> Making a difference between the sources of 6.0.2 and 6.1.0 shows some more changes but they are minimal.
> I implemented my changes in 6.1.0 and will test it first before posting it.

That would be great. You could always fork and publish if you wanted to.

**Comment by padraigdoran** [comment]
> 
> 
> It's looking good with this 6.1.0 version. You can download it here: https://drive.google.com/file/d/17JH0bxrxpYJFD_D32icOVrPHfrolIMV_/view?usp=sharing

I have tested this and it seems to be working fine, thanks. I think you should issue a pull request with your code.

**Comment by peno64** [comment]
Then I would have to implement only a part of my changes because I did more than only this. Appart from showing the current connected vpn server in enhanced information, I also changed the following:
- renamed platform.py to oplatform.py because this conflicted with a platform.py on raspberry pi. I had a discussion with the developer about this but he absolutely does not want to make this change.
- added an ignore list. I also use real debrid to have better streams. Unfortunately some vpn server ip addresses are blocked by real debrid. So I added the possibility to specify in a file a list of vpn servers that must be ignored such that it always chooses a whitelisted vpn. This could be a nice addition to this tool, but I implemented it only for NordVPN and the list must be edited outside the tool with a text editor so this is really not general usable at this moment

**Comment by Zomboided** [comment]
Nord change their VPN servers A LOT  (I'm guessing to work around blocking) which is why it was only feasable to implement Nord support via their API.  I'm guessing you're editing the file semi-frequently to work around the blocking?  

That's is a pretty clever solution, but it's also very much a solution mainly for Nord, which addresses a very specific problem.  Most providers seem to manipulate the IP addresses behind URLs, or use other methods to work around the block that I don't understand.  I'm wondering if there's a better more generic approach to do some kinda connection test and if that fails, just drive a retry.  I'm not sure how you'd do this for the other providers though, which would still be fronting servers with the same URL.

I've also added the server info back into the code.  It'll be in 6.2.0, https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#enable-enhanced-vpn-server-information
It also now works across all providers, not just Nord.  6.2.0 will be published soon, I'm still tracking down an unrelated bug before pushing it.

**Comment by padraigdoran** [comment]
For this ticket, specifically related to NordVPN:
The link I mentioned above ( https://nordvpn.com/api/server ) gives you all the current live server details in JSON format. After connecting to the NordVPN server, query that API link and find the node with matching IP address. This then can be used for the server information/name, load, features, etc.
