### ISSUE TITLE
Can't connect to vpn

### ISSUE THREAD

**Issue by AlleSchonWeg** [Zomboided/service.vpn.manager#229]
Hi,
i installed a purevpn as custom a custom provider. All works, but since a few days i can't connect. It looks like vpn manager can't find config files:

> 18:37:01.301 T:1938034704   ERROR: CGUIMediaWindow::GetDirectory(plugin://service.vpn.manager/?list) failed
18:37:03.578 T:1497363312  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : "/usr/sbin/openvpn" > /run/openvpn.log 2>&1 &
18:37:04.933 T:1497363312  NOTICE: VPN Mgr : (platform.py) Testing killall with : killall vpnmanagertest > /run/command_text.txt 2>&1 &
18:37:11.619 T:1497363312  NOTICE: VPN Mgr : (common.py) Creating VPN provider directory /storage/.kodi/addons/service.vpn.manager/UserDefined
18:38:43.245 T:1497363312  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
18:38:43.246 T:1497363312  NOTICE: Options error: --ca fails with '**/storage/.kodi/addons/service.purevpn.monitor/PureVPN/ca.crt**': No such file or directory (errno=2)
18:38:43.246 T:1497363312  NOTICE: Mon Mar  4 18:37:21 2019 WARNING: cannot stat file '/storage/.kodi/addons/service.purevpn.monitor/PureVPN/ta.key': No such file or directory (errno=2)
18:38:43.246 T:1497363312  NOTICE: Options error: --tls-auth fails with '/storage/.kodi/addons/service.purevpn.monitor/PureVPN/ta.key': No such file or directory (errno=2)
18:38:43.246 T:1497363312  NOTICE: Mon Mar  4 18:37:21 2019 WARNING: file '/storage/.kodi/addons/service.vpn.manager/UserDefined/pass.txt' is group or others accessible
18:38:43.246 T:1497363312  NOTICE: Options error: Please correct these errors.
18:38:43.246 T:1497363312  NOTICE: Use --help for more information.
18:38:43.246 T:1497363312  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end
18:38:44.478 T:1497363312   ERROR: VPN Mgr : (common.py) Error connecting to VPN, something unexpected happened. Check log for more information.

Could you help me to correct the wrong paths?
Thank you

**Comment by Zomboided** [comment]
I think it’s described on the wiki how to use user defined. Or you can add all of the files at the same time using the wizard which sort this all out.

What I can’t fix is the crap service you’ll get from PureVPN when you do connect...
