### ISSUE TITLE
How does one "validate" a vpn connection?

### ISSUE THREAD

**Issue by kmudrick** [Zomboided/service.vpn.manager#23]
I'm pretty confused here.

I'm using PIA.  I chose it in the `VPN Provider` section of the `VPN Configuration` tab in Settings.  I entered my username and password.

Under the `VPN Connections` tab, it says "Click the boxes below to validate primary VPN connections".  The first entry in the list is `First VPN connection (optionally used to auto connect during boot)`.  If I select that - it simply exits the Settings menu.

Am I missing something else?  This is on a raspberry pi (raspian / retropie) and openvpn is indeed installed:

```
pi@retropie:~ $ which openvpn
/usr/sbin/openvpn
```

**Comment by Zomboided** [comment]
Badness.  Selecting first VPN should throw up a connection dialog.
Switch on debug https://github.com/Zomboided/service.vpn.manager/wiki/06.-Debug-Options#enable-debug-just-for-vpn-manager
Get me a log.

**Comment by kmudrick** [comment]
```
14:31:35 10219.404297 T:1944474176   ERROR: ExecuteAsync - Not executing non-existing script special://home/addons/service.vpn.manager/connect.py
14:31:35 10219.466797 T:1719178160    NONE: VPN Mgr Debug: Requested update to service process via settings monitor
14:31:35 10219.485352 T:1719178160    NONE: VPN Mgr Debug: Update service requested KodiMonitor
14:31:36 10221.064453 T:1719178160    NONE: VPN Mgr Debug: VPN monitor service was requested to run an update
14:31:36 10221.081055 T:1719178160    NONE: VPN Mgr Debug: Update primary VPNs from settings
14:31:36 10221.107422 T:1719178160    NONE: VPN Mgr Debug: Found no VPNs, setup is invalid
14:31:36 10221.115234 T:1719178160    NONE: VPN Mgr Debug: Update filter lists from settings
```

FWIW, this seems to have installed in `service.vpn.manager-master`, not `service.vpn.manager` - if I rename the directory to match, then I can no longer launch the program.

**Comment by kmudrick** [comment]
Ahh, I think I know the problem.  I will try installing the repository from the zip on `https://github.com/Zomboided/repository.zomboided.plugins/releases` - looks like I just installed from a zip of master previously.

**Comment by kmudrick** [comment]
Okay, installing from release works a little better, but I think something is not right FS-permissions wise

```
14:54:36 11600.904297 T:1787331504  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : sudo /usr/sbin/openvpn > /run/openvpn.log &
14:54:47 11612.077148 T:1787331504   ERROR: VPN Mgr : (platform.py) Ran openvpn command and VPN log didn't appear
```

If I try running that same command as my pi user it fails as well:

```
pi@retropie:~/.kodi $ sudo /usr/sbin/openvpn > /run/openvpn.log
-bash: /run/openvpn.log: Permission denied
```

The `/run` directory currently looks like this, permissions-wise:
```
drwxr-xr-x 20 root  root
```

**Comment by kmudrick** [comment]
FWIW, I temporarily got past this by making `/run` writeable by all, but that's really not appropriate moving forward.

The redirect does not inherit the permissions of sudo the way it is currently written.  Maybe it should be `sudo sh -c '/usr/sbin/openvpn > /run/openvpn.log'` instead?

sudo sh -c 'ls -hal /root/ > /root/test.out'

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/06.-Debug-Options#always-use-kodi-log-directory-for-openvpn-log

**Comment by Zomboided** [comment]
Closing this as have also added a warning message for bad installs.  There's also a dialog message that's displayed after the error trace you shared telling you to change the setting I pointed you at.

**Comment by Mik3ssv** [comment]
I am having the same problem with the latest version of Retropie trying to use a vpn with kodi 17.1
