### ISSUE TITLE
All Addon settings getting erased

### ISSUE THREAD

**Issue by peno64** [Zomboided/service.vpn.manager#230]
As  requested a new issue when this problem occurs again.

I use the latest version (6.0.2) and today while experimenting with my libreelec kodi (v 18.1) I got this issue again. I started the box and everything was ok. vpn manager connected to my vpn as espected. I didn't go into your vpn addon at all at any time. I did some small things in kodi and then rebooted my rpi. While vpn manager was saying is was making a connection to my vpn, I rebooted the device again.
And then I had the problem that all settings of vpn manager were gone.

Although this is not a big issue for me and I will for sure not reboot the device anymore while it is connecting to the vpn, it may help you to find a reason how this problem can occur.

**Comment by Zomboided** [comment]
Are there any logs?

**Comment by Zomboided** [comment]
Can you get me /storage/.kodi/userdata/addon-data/service.vpn.manager/settings.xml?
Assuming the box is in the same state and you've not edited stuff

**Comment by peno64** [comment]
The file/storage/.kodi/userdata/addon_data/service.vpn.manager/settings.xml is 0 bytes!

LibreELEC:~/.kodi/userdata # ls -l /storage/.kodi/userdata/addon_data/service.vp
n.manager/settings.xml
-rwxr--r--    1 root     root             0 Mar  4 21:27 /storage/.kodi/userdata/addon_data/service.vpn.manager/settings.xml

And I didn't edit any settings.

I already rebooted the rpi again so no kodi anymore unfortunately

**Comment by Zomboided** [comment]
Yup, I've seen this after installs/updates (not after a reboot).  Something
is killing the settings.xml.  I had hoped it was a Kodi bug that was fixed
in 18, but I guess not.
I'll probably dupe this back to the existing issue on this now.  Thanks for
flagging it up though.

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/issues/170
