### ISSUE TITLE
disconnect via terminal

### ISSUE THREAD

**Issue by chwba** [Zomboided/service.vpn.manager#233]
could you hint me regarding how to disconnect the current connection by command in the terminal?

**Comment by Zomboided** [comment]
The addon basically starts, stops and monitors openvpn from within the kodi environment. If you stop openvpn by killing it and kodi is running then the addon will restart it.

There is an api documented on the wiki which controls the addon by doing things with kodi windows properties. I put that it so I could control the addon from other addons but had half considered that I might want to do what you’re doing anyway. I’ve never tried to call it outside of kodi, but maybe it kodi is running it’d work.

The other alternative is to fake the connection, so even if you do kill openvpn, it’ll not restart it, but choose to pretend it has. This is managed by the existence of a file or not. I think this is documented on the wiki, in the API section but maybe not. I had thought this was probably he easiest way to stop the addon from managing openvpn.

Ultimately, you need to choose whether to let the addon manage openvpn or do it outside of kodi. Trying to make both work is effort but probably achievable

**Comment by Zomboided** [comment]
Closing issue as this isn’t a problem. Happy to continue the conversation using this issue tho

**Comment by chwba** [comment]
kodi-send --action="RunScript(/storage/.kodi/addons/service.vpn.manager/api.py, Disconnect)" did the job just fine
