### ISSUE TITLE
Mullvad VPN has switched to new CA and config files

### ISSUE THREAD

**Issue by nemesis1337** [Zomboided/service.vpn.manager#235]

**Comment by Zomboided** [comment]
Need you to supply these files, I don't have an account.

**Comment by nemesis1337** [comment]
Hi! yes i will send them right away, thanks for fast reply and a great vpn addon :+1:

**Comment by nemesis1337** [comment]
I think they also changed their connection port to 1195 if compare then with the old connection files

[mullvad.zip](https://github.com/Zomboided/service.vpn.manager/files/2998306/mullvad.zip)

**Comment by Zomboided** [comment]
This is done, you'll see a notification telling you when they're available to download
