### ISSUE TITLE
VPN Manager for OpenVPN - IPVanish - intermittent disconnecting/connecting while streaming

### ISSUE THREAD

**Issue by Flakalaka** [Zomboided/service.vpn.manager#236]
Hello,

Just wondering if there's something wrong with VPN Manager for OpenVPN these days or if anyone else is having some issues with it lately?

It's been a week that when I stream, I keep getting disconnected randomly and then it would re-connect right away. 

I contacted one of my friend who's also using Open VPN manager with IPVanish and he's experiencing the same exact problem as me.

As a test, I ran OpenVPN through command line with Putty and connected to a server close to my region (The same one that I usually choose with VPN Manager for OpenVPN)  and I didn't get disconnected for 3 hours.

I contacted IPVanish and they said there was nothing wrong on their end as I am also not getting disconnected when connected with my PC with IPVanish.

Thank you.

**Comment by Zomboided** [comment]
There had been some IP Vanish server changes, which I've made, but it looks like everything else is constant so unless you were using an old server, I don't know what would cause this.

Pick up the changes, make sure you're running the latest version of the addon (which I think is 6.1.0, in the repo) and if it keeps happening, I need to see a FULL DEBUG log (ie switch on debug using the VPN Mgr Settings/Advanced option)
