### ISSUE TITLE
Cant Connect

### ISSUE THREAD

**Issue by NellyJelly** [Zomboided/service.vpn.manager#237]
Dont seem to be able to connect anymore until I dissconnect VPN. Get this in my log repeated with different label no. Help please.
07:31:21.567 T:140313268045568   DEBUG: CAddonSettings[service.vpn.manager]: failed to find definition for setting label1008. Creating a setting on-the-fly...
07:31:21.567 T:140313268045568   DEBUG: CSettingsManager: requested setting (label101) was not found.

**Comment by Zomboided** [comment]
Let me put as much effort into helping you as you've put into reporting this.  Go read the trouble shooting guide on the wiki.
