### ISSUE TITLE
Private Internet Access Certificate error

### ISSUE THREAD

**Issue by jimmyboy10101** [Zomboided/service.vpn.manager#24]
Hi There, 

having some issues setting up Private Internet Access VPN, Looking at the logs it looks like its not happy with the VPN Certificate? I have downloaded the correct ones from pia's website but i cant seem to find where to install them to test if they are the issue. 

Any ideas?

`00:01:30 192.835999 T:1777071008  NOTICE: Thu Jun 23 00:01:29 2016 VERIFY ERROR: depth=0, error=certificate is not yet valid: C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private I$
00:01:30 192.836075 T:1777071008  NOTICE: Thu Jun 23 00:01:29 2016 TLS_ERROR: BIO read tls_read_plaintext error: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify fail$
00:01:30 192.836166 T:1777071008  NOTICE: Thu Jun 23 00:01:29 2016 TLS Error: TLS object -> incoming plaintext read error
00:01:30 192.836243 T:1777071008  NOTICE: Thu Jun 23 00:01:29 2016 TLS Error: TLS handshake failed
`

**Comment by Zomboided** [comment]
Certificate is fine assuming you're on a newer version (I use PIA). This looks like a firewall/network issue to me.

**Comment by jimmyboy10101** [comment]
Hmm strange, I use it on other devices on the same network and i have a pretty basic libreELEC setup so i dont think its anything in there. 

Im using the Melbourne AU location, what location are you using?

**Comment by Zomboided** [comment]
I use UK and US servers. I just tried connecting my LibreELEC box to Melbourne UDP and it worked just fine (v2.2.9 of VPN Mgr).

This is why I think it's a network issue somewhere for you https://openvpn.net/index.php/open-source/faq/79-client/253-tls-error-tls-key-negotiation-failed-to-occur-within-60-seconds-check-your-network-connectivity.html

**Comment by Zomboided** [comment]
You can see the ovpn file and certs in use at /storage/.kodi/addons/service.vpn.manager/PIA if you want to compare with what you downloaded

**Comment by jimmyboy10101** [comment]
Hi Zomboided, 

Just letting you know i figured out the issue. 

I had my Time and Date wrong, and Certificates didnt appreciatte being 6 months in the past!

**Comment by Zomboided** [comment]
That's interesting feedback thanks for posting.  I'll add that to the debug page.
