### ISSUE TITLE
Osmc DNS

### ISSUE THREAD

**Issue by edgarok** [Zomboided/service.vpn.manager#240]
DNS error please help 

Wed Jun 19 22:41:09 2019 WARNING: file '/home/osmc/.kodi/addons/service.vpn.manager/UserDefined/pass.txt' is group or others accessible
Wed Jun 19 22:41:09 2019 OpenVPN 2.4.0 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Oct 14 2018
Wed Jun 19 22:41:09 2019 library versions: OpenSSL 1.0.2r  26 Feb 2019, LZO 2.08
Wed Jun 19 22:41:09 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Wed Jun 19 22:41:09 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]217.182.77.177:1194
Wed Jun 19 22:41:09 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
Wed Jun 19 22:41:09 2019 UDP link local: (not bound)
Wed Jun 19 22:41:09 2019 UDP link remote: [AF_INET]217.182.77.177:1194
Wed Jun 19 22:41:09 2019 TLS: Initial packet from [AF_INET]217.182.77.177:1194, sid=fb1afb7a 6ee6386a
Wed Jun 19 22:41:09 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Jun 19 22:41:09 2019 VERIFY OK: depth=1, C=PL, ST=PL, L=Swinoujscie, O=MyDevil, CN=MyDevil CA, emailAddress=admin@mydevil.net
Wed Jun 19 22:41:09 2019 VERIFY OK: depth=0, C=PL, ST=PL, L=Swinoujscie, O=MyDevil, CN=mydevil.net, emailAddress=admin@mydevil.net
Wed Jun 19 22:41:10 2019 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
Wed Jun 19 22:41:10 2019 [mydevil.net] Peer Connection Initiated with [AF_INET]217.182.77.177:1194
Wed Jun 19 22:41:11 2019 SENT CONTROL [mydevil.net]: 'PUSH_REQUEST' (status=1)
Wed Jun 19 22:41:11 2019 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,route-gateway 172.30.0.1,ping 10,ping-restart 120,ifconfig 172.30.0.6 255.255.0.0,peer-id 4'
Wed Jun 19 22:41:11 2019 OPTIONS IMPORT: timers and/or timeouts modified
Wed Jun 19 22:41:11 2019 OPTIONS IMPORT: --ifconfig/up options modified
Wed Jun 19 22:41:11 2019 OPTIONS IMPORT: route options modified
Wed Jun 19 22:41:11 2019 OPTIONS IMPORT: route-related options modified
Wed Jun 19 22:41:11 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Jun 19 22:41:11 2019 OPTIONS IMPORT: peer-id set
Wed Jun 19 22:41:11 2019 OPTIONS IMPORT: adjusting link_mtu to 1656
Wed Jun 19 22:41:11 2019 Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
Wed Jun 19 22:41:11 2019 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Wed Jun 19 22:41:11 2019 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jun 19 22:41:11 2019 Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
Wed Jun 19 22:41:11 2019 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Wed Jun 19 22:41:11 2019 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jun 19 22:41:11 2019 WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.
Wed Jun 19 22:41:11 2019 ROUTE_GATEWAY 10.0.0.1/255.255.255.0 IFACE=wlan0 HWADDR=b8:27:eb:78:8c:79
Wed Jun 19 22:41:11 2019 TUN/TAP device tap0 opened
Wed Jun 19 22:41:11 2019 TUN/TAP TX queue length set to 100
Wed Jun 19 22:41:11 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Wed Jun 19 22:41:11 2019 /sbin/ip link set dev tap0 up mtu 1500
Wed Jun 19 22:41:11 2019 /sbin/ip addr add dev tap0 172.30.0.6/16 broadcast 172.30.255.255
Wed Jun 19 22:41:11 2019 /sbin/ip route add 217.182.77.177/32 via 10.0.0.1
Wed Jun 19 22:41:11 2019 /sbin/ip route add 0.0.0.0/1 via 172.30.0.1
Wed Jun 19 22:41:11 2019 /sbin/ip route add 128.0.0.0/1 via 172.30.0.1
Wed Jun 19 22:41:11 2019 Initialization Sequence Completed

**Comment by Zomboided** [comment]
From the log that youv'e decided is interesting, it all looks fine.

If you've having trouble, read the trouble shooting on the wiki
