### ISSUE TITLE
UPnP Device discovery does not use tun0 interface in Kodi18

### ISSUE THREAD

**Issue by king10002** [Zomboided/service.vpn.manager#245]
After a successful connection to my private OpenVPN, Kodi apparently uses wlan0 network interface to detect UPnP devices. I would like Kodi 18 to detect UPnP device via the tun0 interface. Is this configurable? Let me know if more information are needed.

Operating System: LibreELEC (official): 9.0.1
Version info:
  Build: Kodi 18.1 Git:newclock5_18.1-Leia
  Compiled: 2019-02-21

Kernel IP routing table:
> Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
> default         10.8.0.1        128.0.0.0       UG    0      0        0 tun0
> default         fritz.box       0.0.0.0         UG    0      0        0 wlan0
> 10.8.0.0        *               255.255.255.0   U     0      0        0 tun0
> 128.0.0.0       10.8.0.1        128.0.0.0       UG    0      0        0 tun0
> 134.101.147.142 fritz.box       255.255.255.255 UGH   0      0        0 wlan0
> 192.168.178.0   *               255.255.255.0   U     0      0        0 wlan0

**Comment by Zomboided** [comment]
You can try and use the up/down scripts discussed somewhere on the wiki to modify the routing table, but this isn’t something that’s supported directly from the addon, or that I’ve any clue about doing
