### ISSUE TITLE
openvpn command for Mac OS X

### ISSUE THREAD

**Issue by GeoffatMM** [Zomboided/service.vpn.manager#248]
I have never done this before so not sure if this is the right place.

I have tried to install the VPN Manager to my Kodi on a Mac running OSX.  The wizard fails as it asks for Killall, pidof and openvpn to be available.

Killall is already available and I successfully used home-brew to install pidof.  Both commands are recognised in the terminal.  However, I also used home-brew to install openvpn but it did not appear to install the commands.  Instead (I suspect) it installed the openvpn package.  

Terminal (bash) does not recognise openvpn as a command.  How do I install the openvpn command so that the wizard will acceppt it and allow me to add a vpn provider?

Geoff

**Comment by Zomboided** [comment]
I think you mean pidof, no idea what piron is or why you’d use it. I’ve also no clue how to install anything on a Mac, I don’t use one. And even then I’m not sure it’ll work or not as there’s a bunch of platform dependent code that at the moment only recognises Windows and Linux. 

So if you were able to debug the code and fix the issues I’d be happy to help here, but I sense from your questions that this isn’t your skill set and therefore I’m just gonna close this as unsupported
