### ISSUE TITLE
stuck on 2.2.9

### ISSUE THREAD

**Issue by sgiannulli** [Zomboided/service.vpn.manager#25]
hi,
don't know why version is stuck on 2.2.9 and it doesn't update to new 2.3.0
any check to do?
thanks

**Comment by Zomboided** [comment]
Same issue on my Kodi boxes actually.  I've rebooted, checked the repo (still shows 2.2.9) checked what's on Github is correct (2.3.0).  I've uninstalled 2.2.9 and installed the version of 2.3.0 I uploaded to the repo and no problems, upgrade was fine.

I don't appreciate when updates to a repo get noticed by Kodi, but what's in the repo is fine.  It should upgrade sometime soon but if you're desperate to use the newer features uninstall 2.2.9 and install 2.3.0.  All of your settings should stay the same.
