### ISSUE TITLE
Shortut key to disable/enable vpn

### ISSUE THREAD

**Issue by peno64** [Zomboided/service.vpn.manager#250]
This is a request. 
It would be nice if I could assign a shortcut key (ex F6) to disable and back enable vpn connection.
I know there is a shortcut key to loop over the predefined connections and it allows also to disable vpn. But I have assigned 5 connections so I have to press several times on that hotkey to disable the first connection.

Thx

**Comment by Zomboided** [comment]
You can already do this by using the API https://github.com/Zomboided/service.vpn.manager/wiki/11.-API

It's just up to you to manipulate the keymap file manually vs having the addon do it for you.

**Comment by peno64** [comment]
Great!
Works perfectly. 
Thx
