### ISSUE TITLE
Same OVPN file, vpnmanager (Kodi) always connects to different IPs compared to Mac (Tunnelblick)

### ISSUE THREAD

**Issue by u3473u** [Zomboided/service.vpn.manager#253]
Hi

I have an OVPN file from my provider (PrivateVPN)

When using just this file on my Mac (Tunnelblick), after entering my username + password, it connects to the IPs that allow me to access my service

Using this exact same OVPN file on vpnmanager, it seems to always connect to completely different IPs, despite how many times I disconnect/reconnect. Interestingly the "isp provider" also appears as a different name, compared to what is shown on my Mac. On these different IPs, I cannot access my service

Cannot figure out why different IPs are being connected to on Kodi vs OSX, with the same OVPN file. I have tried playing around with the ports, but no change

-----
Interestingly, I also tried this with my other VPN (Windscribe). Using the same OVPN file, Kodi seems to connect to different IPs (e.g 350.xxx.xx.xxx) compared to OSX (e.g 100.xxx.xx.xxx)

Any ideas what could be causing this? Thanks

**Comment by Zomboided** [comment]
Don’t use a Mac, don’t use the VPN providers you mentioned. Look for the Linux ovpn files, as it’s just a wrapper around calling openvpn for Linux.

You can also look at the trouble shooting and try connecting via the command line.

Can’t really help you tho
