### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by MuchAnnoyed** [Zomboided/service.vpn.manager#254]
Unable to do anything because I'm in a "VPN is not set up and authenticated." loop.

Would love to uninstall / disable or change settings, however every-time I select any button in Kodi I get the "VPN is not set up and authenticated." and have no obvious solutions, besides starting Kodi from scratch.

**Comment by Zomboided** [comment]
Did you try reading the instructions on the wiki on how to use this?
DId you want me to guess at what's wrong from this sparce description you've provided?

**Comment by MuchAnnoyed** [comment]
Followed the instructions and found myself in a situation that required a total reboot of Kodi.

Wasn't able to properly diagnose the problem because of the previously describe issue, obviously I'd made a mistake somewhere in the settings, however the issue is not being able to correct the mistake once made.

The "user error" angle gets old very quickly when your unable to correct your mistake and that is your mistake.

Suggest you look at /libs/common.py, line: 717 if / else statement that continues the loop

**Comment by Zomboided** [comment]
Attitude and no log gets you no support. Good luck fixing this yourself
