### ISSUE TITLE
VPN Manager won't connect

### ISSUE THREAD

**Issue by amsterreynolds-123** [Zomboided/service.vpn.manager#255]
[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/3643562/kodi.log)

Hello Zomboided,

VPN Manager stopped working recently. Running Kodi 18.4, LibreELEC 9.1.501. Any pointers appreciated.

**Comment by Zomboided** [comment]
Thanks for the log.  I don't see anything obvious here.  Can you go the VPN Mgr settings/advanced menu, switch on debug and reboot so I can see more info please?

**Comment by Zomboided** [comment]
It's a problem connecting to the VPN, I suspect something has changed
recently with Torguard.  I can't see any evidence of code problems (yet...)
Are you able to do things like SSH into your Kodi box and replace files if
I try and give you some things to try?

**Comment by amsterreynolds-123** [comment]
TorGuard did make changes in prep for ipv6.

Have ssh access and appreciate your assistance.


________________________________

**Comment by Zomboided** [comment]
Here are a couple files.  Download them and rename the ca.crt.txt to ca.crt
Assuming you've left the system in the state that it was in when you sent me the log, you should be able to go to /storage/.kodi/userdata/addon_data/service.vpn.manager/Downloads/Torguard and deposit these files over the existing ones.
Go to the addon GUI and Settings/Utilities and select ''Reset VPN Provider'
Then try and connect...let me know the results and if it works I'll commit the the change.  If it doesn't I need a debug log again please.

[TEMPLATE.txt](https://github.com/Zomboided/service.vpn.manager/files/3649159/TEMPLATE.txt)

[ca.crt.txt](https://github.com/Zomboided/service.vpn.manager/files/3649160/ca.crt.txt)

**Comment by amsterreynolds-123** [comment]
Followed your instructions and reset the provider but still unable to connect. Attached is the log. Thanks for your assistance.
[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/3654337/kodi.log)

**Comment by Zomboided** [comment]
Can you share this file please
/storage/.kodi/addons/service.vpn.manager/TorGuard/Germany (UDP).ovpn
Have you/can you try other locations other than Germany?
Can you try a TCP connection rather than UDP please?

**Comment by amsterreynolds-123** [comment]
File attached. When I try other locations, I get the same result (connection error). Although there are TCP opvn files in /storage/.kodi/addons/service.vpn.manager/TorGuard/, none of the TCP profiles are listed in the vpn connections list, only udp profiles...
[Germany (UDP).zip](https://github.com/Zomboided/service.vpn.manager/files/3654703/Germany.UDP.zip)

**Comment by Zomboided** [comment]
Go to the first menu on settings and scroll down...you should be able to
select 'TCP', which will show you the TCP locations when you try and connect

**Comment by Zomboided** [comment]
Just checked the UDP - you've not regenerated the files to test the fix so let's try again.
Do this :
Go to /storage/.kodi/addons/service.vpn.manager/TorGuard/ and delete everything.

Check that the updated TEMPLATE.txt and ca.crt are in the right place - in /storage/.kodi/userdata/addon_data/service.vpn.manager/Downloads/Torguard (ie, a different directory to previously!).

The in the GUI, try and reconnect.

You'll see /storage/.kodi/addons/service.vpn.manager/TorGuard/ get repopulated.

You can check to see if the TEMPLATE.txt and ca.crt in that directory are the new ones.  If they are, and it's still not working, I'll take a new log from you, along with one of the *(UDP).ovpn files.

**Comment by amsterreynolds-123** [comment]
1. Went to /storage/.kodi/addons/service.vpn.manager/TorGuard/ and deleted everything.
2. Confirmed that the updated TEMPLATE.txt and ca.crt are in the right place.
3. Reconnected - same error, couldn't connect.
4. /storage/.kodi/addons/service.vpn.manager/TorGuard/ did get repopulated.
5.  TEMPLATE.txt and ca.crt in /storage/.kodi/addons/service.vpn.manager/TorGuard/ were new ones (I've included in the udp zip file).

*.UDP file and fresh log attached.
[udp_files.zip](https://github.com/Zomboided/service.vpn.manager/files/3659440/udp_files.zip)
[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/3659441/kodi.log)

**Comment by Zomboided** [comment]
The ovpn files supplied have these entries in them:
remote gr.torguardvpnaccess.com 1912
remote 93.177.73.90 1912

The one that  you're using (again for Germany) has just the second.
Can you change the IP address for the URL, using the same port (1912) in
the generated files you sent me and just try to connect to Germany again?

If this fails i'm going to have to spend a bunch of time debugging myself
which isn't going to happen anytime soon (family + work + travel...)

**Comment by amsterreynolds-123** [comment]
That's done the trick :) Thanks a lot... so it's the IP address that's an issue? Will this be the same for the other udp files?

**Comment by Zomboided** [comment]
Ha, so you're telling me that without DNS, and with a direct reference it
doesn't work...the irony :-)
Go and update the ones you need based on the template i've given you.  I'll
push out an update when I get some time.
Can you try a TCP connection for me as well please?

**Comment by amsterreynolds-123** [comment]
The irony indeed. Will the port be 1912 for TCP, same as UDP?

**Comment by Zomboided** [comment]
yep, same port, you'll need to edit the TCP version tho rather than just
change the proto parameter tho as there are a couple other changes for TCP.

Here's what the provider ovpn says, I think it's the same as the UDP
version for the remote param.
remote gr.torguardvpnaccess.com 1912
remote 93.177.73.90 1912

**Comment by amsterreynolds-123** [comment]
TCP is working as well. If you need me to do more testing, happy to help. Amazing app - thanks!

**Comment by Zomboided** [comment]
Ok thank you...you'll see an update notification when you connect when I
get round to fixing this properly.  Thanks for your help

**Comment by amsterreynolds-123** [comment]
Sorry – one last questions. How do I address this warning: WARNING: file '/storage/.kodi/addons/service.vpn.manager/TorGuard/pass.txt' is group or others accessible

**Comment by amsterreynolds-123** [comment]
Sorry – one last questions. How do I address this warning: WARNING: file '/storage/.kodi/addons/service.vpn.manager/TorGuard/pass.txt' is group or others accessible

**Comment by Zomboided** [comment]
You don't....everything is being run as admin anyway with unencrypted
passwords stored on your Kodi box.  It's not the most secure environment
ever...

**Comment by Zomboided** [comment]
Committed this change, please pick up the changes when you're notified

**Comment by john22-prog** [comment]
using LibreELEC 9.2.0 with Kodi 18.5 Leia, with VPN Manager for OpenVPN version 6.3.1
Trying to setup VPN via "User defined" option as my VPN provider is not in the list. and this error i receive https://we.tl/t-3NmlWVbhLx
What could be the issue?
and moreover what's the process to add a new VPN provider to the VPNs list? so users do not need to set it up manually?

**Comment by Zomboided** [comment]
Go read the troubleshooting page on the wiki for words on how to get a debug log. Whatever it is you’re showing me is not helpful at all.

And I’m not interested in adding more VPN providers, there are too many of them already to keep up to date and user defined is now the answer (when it works....)
