### ISSUE TITLE
some information might help or it might not

### ISSUE THREAD

**Issue by grant2258** [Zomboided/service.vpn.manager#258]
I was having issues with a pi3 vpn just locking up with the script.  So I ran it manually to see what was going on now I reproduce this if i disconnect my network then reconnect the openvpn is running but not responding at all until i restarted it after reconnecting to the network. The client doesnt seem to keep alive properly so needs some help. 

I made a script to run on cron but the ping never timed out I found I was using the ping wrong in my script.
 
was using PING -c 8 -q -W 8 (this locks when you disconnect and reconnect the network)
PING -c 8 -q -w 8 (this times out even when you disconnect and reconnect the network)

If my isp disconnects and reconnects i have to restart to openvpn client 

so with that in hand ive created a simple bash script to keep it on until this addon works for me. 

```
#!/bin/bash
NEXTHOP=www.virginmedia.com
OPEN_VPN_CMD="/usr/bin/systemctl restart openvpn.service"
PING=/bin/ping
thedate=`date +"%Y-%m-%d %T"`
pckts_rcvd=`$PING -c 8 -q -w 8 $NEXTHOP | /usr/bin/grep transm | /usr/bin/awk '{print $4}'`

if [ $pckts_rcvd -eq 0 ]
then
    echo "$thedate Connection with $NEXTHOP lost, resetting"
    $OPEN_VPN_CMD
else
    wanip=`wget -T 4 -qO - icanhazip.com`
    wanlookup=$(nslookup $wanip | grep "ipvanish" | awk '{print $3 $4}' )
    iplookup=`nslookup $wanip`

    if echo "$iplookup" | grep -q "ipvanish";then
         echo  "$thedate Connection with vpn is active $wanlookup"
    else
        wanlookup=$(nslookup $wanip | grep "ipvanish" )
        echo  "$thedate Connection with vpn or isp is inactive restarting vpn $wanlookup"
        $OPEN_VPN_CMD
    fi

fi
```

**Comment by Zomboided** [comment]
I really like your ingenuity here but you’re kinda fixing the cause, not the symptom (I think).  If that’s ok with you, thanks for sharing, otherwise here’s some input

All providers use a default ping value to keep the connection alive. If it fails, then openvpn should exit and my addon will do the rest.

If openvpn is not exiting, then you should probably change the openvpn parameters by adding your own and turning off the keep alive option.

Instructions are spread through the wiki on doing both of these things and it’d be cleaner than running a job to keep alive something that should be keeping itself alive

**Comment by grant2258** [comment]
yea I was struggling with what options to put in as the restart doesnt seem to work for me. My isp disconnects a lot ts kinda frustrating.  Ill try going through the wiki I would prefer the addon to get it to restart ect just using this as stop gap for now until i get this working. 
Thanks for the info ill try a few things on the wiki. You can feel free to close this ill post any info if i get it fixed.

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#check-connection-with-ping

This is the relevant tab, you can switch this off and over ride with your own as per here 

https://github.com/Zomboided/service.vpn.manager/wiki/10.-Updating-VPNs#extending-existing-templatetxt-and-ovpn-files

**Comment by grant2258** [comment]
Well I had some time to see what was going wrong seems the default systemd script for openvpn doesnt restart fully and it needs too on a network reconnect/disconnect on libreelec.

I have made a modified systemd script for it so it restarts when the network goes down. Does your script monitor the up/down status of the network because if the network goes down the vpn client needs restart to set all the routing up again after the network comes up.  Everything works as it should with the new systemd script.

the SIGUSR1[soft,ping-restart] received, process restarting just locks anything happening. 

```
Oct 22 04:06:17 LibreELEC systemd[1]: Stopping OpenVPN Autorun Service...
Oct 22 04:06:17 LibreELEC openvpn[5858]: /sbin/ip route del 81.171.71.27/32
Oct 22 04:06:17 LibreELEC openvpn[5858]: ERROR: Linux route delete command failed: external program exited with error status: 2
Oct 22 04:06:17 LibreELEC openvpn[5858]: /sbin/ip route del 0.0.0.0/1
Oct 22 04:06:17 LibreELEC connmand[473]: tun0 {del} route 0.0.0.0 gw 172.21.20.1 scope 0 <UNIVERSE>
Oct 22 04:06:17 LibreELEC openvpn[5858]: /sbin/ip route del 128.0.0.0/1
Oct 22 04:06:17 LibreELEC openvpn[5858]: Closing TUN/TAP interface
Oct 22 04:06:17 LibreELEC openvpn[5858]: /sbin/ip addr del dev tun0 172.21.20.160/23
Oct 22 04:06:17 LibreELEC connmand[473]: tun0 {del} route 128.0.0.0 gw 172.21.20.1 scope 0 <UNIVERSE>
Oct 22 04:06:17 LibreELEC connmand[473]: tun0 {del} address 172.21.20.160/23 label tun0
Oct 22 04:06:17 LibreELEC connmand[473]: tun0 {del} route 172.21.20.0 gw 0.0.0.0 scope 253 <LINK>
``` 
as you can see with the network coming back up the route we need is gone. so we need to either add the route back or kill the vpn client and restart it.

**Comment by grant2258** [comment]
here is my modified openvpn script that works for the restart might explain why some people are getting lockups.

```
[Unit]
Description=OpenVPN Autorun Service
After=network-online.service
Requires=network-online.service
Wants=network-online.target

[Service]
Type=notify
ExecStart=/usr/sbin/openvpn --daemon --config /storage/.config/openvpn.config
Restart=always
RestartSec=15
LimitNPROC=10
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw
ProtectSystem=true
ProtectHome=true
KillMode=process
RestartSec=5s
Restart=on-failure
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE

[Install]
WantedBy=kodi.target
```

**Comment by grant2258** [comment]
ok some good news sorry about all the posts but i found a solution that will work with the script add this to the config remap-usr1 SIGHUP and it all works like is should even with a network disconnect

**Comment by Zomboided** [comment]
The issue with modifying the systemd service is that it’s only used on initial boot if the option to establish vpn before kodi boots is enabled. Once booted everything is managed from the python script running within kodi. This is by design because I need control over what openvpn is doing and where it’s connecting to.

I’m more interested in your latest post...this is an openvpn parameter which changes the way openvpn works on disconnect? The desired fix to the problem is to get openvpn to exit on disconnect and let the reconnect logic all do it’s thing (which is what you’re not seeing)

Can you try seeing if just adding this extra parameter to the ovpn works through a disconnect without your script please and if so I’ll code that solution

**Comment by grant2258** [comment]
Yes this is doing all the logic it makes it do a restart itself. I tested it with systemd disabled. The default usr1 doesn't add the route when a connection  is lost.

**Comment by Zomboided** [comment]
ok, thanks for the clarification...I'll do some more testing on my home
machines over the next few days and think about how to add this parameter.

**Comment by grant2258** [comment]
Well ive been running two days not the service has not been restarted internal restart mechanism takes care of it all with the signal change in the config file. Ive been monitoring for a day so far and its been fine on ping reset.  Im using this code below check my connection status. The timestamps give me information to check the journel to see what happened on a connection status fault and what is happening.

 At the weekend ill remove the service completely and run it in the background like the script would.

```#!/bin/bash
NEXTHOP=www.virginmedia.com
OPEN_VPN_CMD="/usr/bin/systemctl restart openvpn.service"
PING=/bin/ping
thedate=`date +"%Y-%m-%d %T"`
pckts_rcvd=`$PING -c 8 -q -w 8 $NEXTHOP | /usr/bin/grep transm | /usr/bin/awk '{print $4}'`

if [ $pckts_rcvd -eq 0 ]
then
    echo "$thedate  ___FAIL___ external ping with $NEXTHOP not working"
else
    wanip=`wget -T 4 -qO - icanhazip.com`
    if [ $? -ne 0 ]
    then
       echo "$thedate ___FAIL___ failed to get external ip"
       exit
    fi

    iplookup=`nslookup $wanip | grep "Address 1:" | grep -v "192.168.1.1"`

    if echo "$iplookup" | grep -q "ipvanish";then
        echo  "$thedate ___PASS___ Connection with vpn is active $iplookup"
    else
        echo  "$thedate ___FAIL___ Connection with vpn is inactive £iplookup"
    fi

fi
```

**Comment by Zomboided** [comment]
Just reading about remap-usr1 so I can do this fix.
Why SIGHUP rather than SIGTERM?  If you go SIGTERM it should kill the process and my addon should restart it.  This gives you the ability to stop any stream if the connection goes away (handy as there's generally no kill switch here).  If you go SIGHUP then it'll restart the openvpn as before but there might be a period during the reconnection where the stream will go over an unsecure connection?

**Comment by grant2258** [comment]
either one will do sigup just done what i needed it too either one should do. I can understand using the sigterm makes more sense. I used sighup because im running it as a daemon to see if the service totally restarted it didnt.

**Comment by Zomboided** [comment]
6.3.1 just pushed to fix this.  It has an option to change the remap to an an UP or a TERM (or nothing).
Thanks for your help here, really appreciate you making this addon better

**Comment by grant2258** [comment]
H thanks for all the updates. I have just installed this and all the options default. If i change to sigterm will the it automatically restart?

I can see the advanced options have changed. There is only one slight bug I see in the settings advanced menu there is a potential DNS fix option but has no toggle on it.

**Comment by Zomboided** [comment]
You'll need to reset the vpn provider to pick up the new setting.
Unfortunately it's not automatic, but once you've done it it'll be fine.
DNS fix is fine, that was never a toggle.  If you click on it, it goes off
and runs some stuff.
Hopefully this will work for you just fine.

**Comment by grant2258** [comment]
Well just some feedback here all went well as far as the connection goes. I had intermittent problems with seren running slow. I uninstalled your script and ran it as a vpn daemon and everything worked again. Ill need to try narrow down if its seren or this script or the version if libreelec  (official 9.1.501)  im using.
