### ISSUE TITLE
Problems connecting on Win10

### ISSUE THREAD

**Issue by lafreak88** [Zomboided/service.vpn.manager#259]
Hello

Still have problems connecting to Express VPN in Windows 10. Windows 7 is working without problems, using the Windows OpenVPN GUI is working without problems, too.

I know, in the description you wrote, that it is tested in Win7. Is there any experience with Windows 10?

The error Attached I get from VPN in Kodi.

Thanks in advance for any help. Maybe from other users.
Christoph

![62010205-fd3ea600-b167-11e9-942f-6ca0b6452464](https://user-images.githubusercontent.com/43384104/67162822-41f16c00-f368-11e9-8a37-0aa91bbda4ee.png)

**Comment by Zomboided** [comment]
There’s an option to turn off block dns in the settings *somewhere*. Find and try that, you’ll need to regenerate the ovpn files using reset provider. More help on the wiki where this stuff is written up, I just can’t look right now

**Comment by lafreak88** [comment]
thanks a lot. Can be really simple if you know where to search. its working :)
