### ISSUE TITLE
PureVPN UK's Servers

### ISSUE THREAD

**Issue by jeremyj29** [Zomboided/service.vpn.manager#26]
Hi ,

UK Servers for PureVPN are not right in the AddOn.
These are the right values :

**Only one London with several server behind :**
UDP : ukg1-ovpn-udp.pointtoserver.com
TCP: ukg1-ovpn-tcp.pointtoserver.com
**Gosport :**
UDP : ukg1-ovpn-udp.pointtoserver.com
TCP : ukg1-ovpn-tcp.pointtoserver.com
**Maidenhead :**
UDP : ukm1-ovpn-udp.pointtoserver.com
TCP : ukm1-ovpn-tcp.pointtoserver.com
**Manchester :**
UDP : vlus-uk-man1-ovpn-udp.pointtoserver.com
TCP : vlus-uk-man1-ovpn-tcp.pointtoserver.com
**Leicester :**
UDP : vlap-ukle1-ovpn-udp.pointtoserver.com
TCP : vlap-ukle1-ovpn-tcp.pointtoserver.com

Thanks in advance, this addon is so usefull !
Best Regards
Jeremy

**Comment by Zomboided** [comment]
The locations are automatically generated using the ovpn files from the provider (so I don't have to maintain lists of servers).  Pure was updated in 2.3.0 using the set of ovpn files just before Christmas.  I checked the Gosport and Leicester servers I'm using and they're the same as what you're saying.  I didn't bother checking the rest (as I said, it's generated)

**Comment by Zomboided** [comment]
If you have a particular issue with a server on 2.3.0, then please do post it up
