### ISSUE TITLE
How does one go about installing "killall" and "pidof" on a Jailbroken ATV 4K?

### ISSUE THREAD

**Issue by SemoTech** [Zomboided/service.vpn.manager#260]
Looks like VPN Manager for KODI needs OpenVPN and that can be installed from Github here, but no idea how to get the OpenVPN executable on KODI 17.6 to write out a log (message from the VPN Manager wizard, or how to install "killall" & "pidof" on the jailbroken ATV 4K?

Any suggestions?

**Comment by Zomboided** [comment]
Yes, all of the instructions say that....I’ve no idea what device you’re running or what OS it’s running, that’s for you to figure out. Instructions for different OSes are on the wiki

**Comment by SemoTech** [comment]
Hi @Zomboided and thanks for the prompt reply.  I am running a Jailbroken ATV 4K but there is nothing in the instructions about how to go about installing these pre-requisites on ATV, just Linux and Windows.  I would not have asked otherwise.  If I missed something I would appreciate a link.  Thanks in advance.

**Comment by SemoTech** [comment]
In case anyone cares, seems the ATV 4K with tvOS 12.4 already comes with "killall", it's located in the /usr/bin folder!
-rwxr-xr-x   1 root   wheel   52416 Dec 20  2017 killall

However "pidof" is not present and "apt-get install pidof" yields "Unable to locate package pidof"

If anyone has any idea how to get "pidof" to install, please let me know...
