### ISSUE TITLE
translation patch

### ISSUE THREAD

**Issue by BlackGlassSkin** [Zomboided/service.vpn.manager#261]
**I have partly translated into another language, but it doesn't work only after adding**

msgctxt "# 32008"
msgid "Show password"
msgstr "my lang"

**not working**
**==============================**
msgctxt "# 32008"
msgid "my lang"
msgstr "my lang"

**work**
**==============================**
not posible to ad custom language folder
- English
     - strings.po
**work**
**==============================**
--MYLANG
     --- string.po
**not work**

**Comment by Zomboided** [comment]
There’s so much hard coding of strings in the code, and I’ve no intentions to 
change this so there’s no point in doing a translation unfortunately
