### ISSUE TITLE
Connecting to PIA no longer works with kodi openVPN

### ISSUE THREAD

**Issue by Nizzrah** [Zomboided/service.vpn.manager#262]
when connecting to any of the private internet access vpn tunnels, it errors out with the following error:

Option Error: Unrecognized option or missing or extra parameter(s) in /storage/.kodi/addons/service.vpn.manager/PIA/<vpn tunnel>.ovpn:24:remap_usr1(2.4.7)
Use --help for more information.

Any idea how this all the suddens happens? Never had issues with openvpn before.

![OpenVPNError](https://user-images.githubusercontent.com/32925191/67973246-74288680-fc10-11e9-9510-c6dde907ed92.jpg)

**Comment by Zomboided** [comment]
I've not published a build with that change in, it's still in development in github.  Use a build that I've published if you want me to support it.

**Comment by Nizzrah** [comment]
Hi,

Where to find this build? I am using your repository now and it installs this build.

**Comment by Zomboided** [comment]
I've not committed this change to my repository...that build is still
6.3.0.  If you really are using my repository you can go and install that
level.
You're seeing changes in a level of code which is later than 6.3.0 so
you're getting this build from somewhere else.  If you're using some shitty
wizard build thing then who knows where you're picking stuff up from, or
where they get stuff from.

**Comment by Nizzrah** [comment]
Hi,

After reinstalling kodi again and using your official repo it started working again. Sorry for the inconvenience and thanks for pointing me in the right direction. Hope I did help you a bit with the error message I got when connecting to PIA.

Regards.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
