### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by ProposIanto** [Zomboided/service.vpn.manager#268]
Have been struggling for a day now to get this working on my Kodi (Raspberry/Linux).
Go through the wizard, try to connect and nope. Get the same error every time about checking my credentials (which are 100% correct, from the specific Windscribe page for it) or to check my connectivity. (?)
Here's the pertinent part of the log. Hope it's enough to get some clarity. If not, please let me know. I'm quite new to all this.
`19:07:45.345 T:1324524448  NOTICE: VPN Mgr : (vpnplatform.py) VPN log file start >>>
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 WARNING: file '/storage/.kodi/addons/service.vpn.manager/Windscribe/ta.key' is group or others accessible
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 WARNING: file '/storage/.kodi/addons/service.vpn.manager/Windscribe/pass.txt' is group or others accessible
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 OpenVPN 2.4.1 armv7ve-openelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [EPOLL] [AEAD] built on May 29 2017
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 library versions: LibreSSL 2.4.5, LZO 2.10
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]185.253.96.3:443
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 UDP link local: (not bound)
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 UDP link remote: [AF_INET]185.253.96.3:443
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 VERIFY ERROR: depth=1, error=format error in certificate's notAfter field: C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 OpenSSL: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 TLS_ERROR: BIO read tls_read_plaintext error
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 TLS Error: TLS object -> incoming plaintext read error
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 TLS Error: TLS handshake failed
19:07:45.345 T:1324524448  NOTICE: Wed Nov 27 19:03:38 2019 SIGTERM[soft,tls-error] received, process exiting
19:07:45.346 T:1324524448  NOTICE: VPN Mgr : (vpnplatform.py) <<< VPN log file end
19:07:45.372 T:1324524448  NOTICE: VPN Mgr : (managefiles.py) Copying log file to /var/media/sda1-usb-SanDisk_Ultra_4C/kodi_19-11-27_19-07-45.log.  Using version 6.3.1
`

**Comment by Zomboided** [comment]
it's really not easy to read a log which is word wrapped.
This says auth error though.  Either you're not supplying the correct user ID/password, or you're not passing in the right keY (I think Windscribe uses a key, I can't remember without looking at the code).
If it is keys, delete the keys using the option in settings/utilities and then use the wizard, reading the words on the screen carefully.

**Comment by ProposIanto** [comment]
Apologies for the code. 
Thanks for the suggestion. I'll try this.
I'm 100% sure ID/PW are correct, so it must be that other setting then. Thanks for your prompt reply. :)
