### ISSUE TITLE
CyberGhost LOCATIONS.txt not working anymore

### ISSUE THREAD

**Issue by onepopcorn** [Zomboided/service.vpn.manager#271]
Recently CyberGhost changed their servers and now the configuration for CyberGhost is not working anymore.

I really don't know if there's anything else that needs to be fixed but LOCATIONS.txt file is sure outdated now.

Hope this helps to get if up and running again.

**Comment by Zomboided** [comment]
Need the ovpn files for locations that have changed. I have no cyberghost account so can’t get these myself

**Comment by onepopcorn** [comment]
I've manage to collect all the new servers and rebuild the LOCATIONS file with a couple of scripts. Let me know if this works or you need anything else. 

[LOCATIONS.txt](https://github.com/Zomboided/service.vpn.manager/files/3957437/LOCATIONS.txt)

**Comment by Zomboided** [comment]
This is great thanks!  I'll do some checking and push this out soon.

**Comment by Zomboided** [comment]
This has been committed, thanks for supplying this.  Please let me know if there are issues with it....looks fine to me but I can't test.

**Comment by onepopcorn** [comment]
> This has been committed, thanks for supplying this. Please let me know if there are issues with it....looks fine to me but I can't test.

Thank you for the amazing plugin! I'll try to test it out when I have time.
