### ISSUE TITLE
Cannot filter addons

### ISSUE THREAD

**Issue by pooploaf** [Zomboided/service.vpn.manager#272]
im running coreelec and the filtering of addons doesn't appear to be working. It highlights the addon blue when clicked on but never moves the addon into the excluded list.

**Comment by Zomboided** [comment]
Same issue on LibreELEC and Windows. Fixed in Kodi 19 (ie it’s not my problem to fix). The selection works on LE tho, and the subsequent filtering, it just doesn’t look like it’s selectsd
