### ISSUE TITLE
Addonsignals timeout error

### ISSUE THREAD

**Issue by pooploaf** [Zomboided/service.vpn.manager#273]
Im using coreelec and when i try to filter netflix so i can watch a show i get this error
Exeption: Addonsignals call timed out.

**Comment by Zomboided** [comment]
Amazing debug log...if the VPN is connected by Netflix isn’t working then it’s likely Netflix doesn’t work with your VPN provider

**Comment by pooploaf** [comment]
> Amazing debug log...if the VPN is connected by Netflix isn’t working then it’s likely Netflix doesn’t work with your VPN provider

https://tenor.com/view/nerd-ackchyually-actually-gif-11156171
