### ISSUE TITLE
Kodi on enigma2

### ISSUE THREAD

**Issue by ismailiabderrahim** [Zomboided/service.vpn.manager#274]
I try to install the VPN addon on Kodi running on Enigma2 but it doesn't work because killall and another plugins are missing and couldn't get installed

Is there any cgance to have a solution for this problem 

Thanks

**Comment by Zomboided** [comment]
Go read pages 1, 2 and 13 on the wiki.  I've no idea what an Enigma2 is, but the requirements for this addon are clearly stated on the pages I mentioned.
