### ISSUE TITLE
VPN dissconnecting

### ISSUE THREAD

**Issue by NellyJelly** [Zomboided/service.vpn.manager#276]
Having problems with my VPN dissconecting very often. I use Smart DNS Proxy VPN, Have tried resetting my Kodi install to see if it was a certain addon that was causing problem but it still seems to happen. Have attatched the log file, Is the problem related to the error in the log about the "cipher block size". Appreciate if you have time to look 

https://pastebin.com/1AkvaA4n

**Comment by Zomboided** [comment]
I've pushed some new definitions based on their latest config files.  If that doesn't solve it you'll need to see the troubleshooting section and take it up directly with their support as I'm basically just running what they supply
