### ISSUE TITLE
Kodi on Windows without running as administrator

### ISSUE THREAD

**Issue by gahujipo** [Zomboided/service.vpn.manager#278]
https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation#windows
says 
> When you run Kodi, you must run it as administrator (otherwise updating the routing table will fail during VPN connection). You can change the properties of the Kodi executable to always run it as administrator.

This works, but when you use the Windows Store Version of the App, the path changes with every update and the compatibility setting "run as administrator" gets lost. I also have linked Kodi to a button on my wireless keyboard which doesn't allow me to run as admin.  

But since OpenVPN 2.4 there is a way to avoid that: 
https://community.openvpn.net/openvpn/wiki/OpenVPNInteractiveService
OpenVPN GUI is doing it that way.

Is there a way to implement that method in this project too?

**Comment by Zomboided** [comment]
It’s a reasonable request but I’ve little interest or motivation in significantly changing the way everything is monitored and logged.  There are other things I’d rather spend time working on.
