### ISSUE TITLE
Cuberghost disconnect/reconnect automatically

### ISSUE THREAD

**Issue by coincoin73** [Zomboided/service.vpn.manager#279]
Hi,

I have already done an install of LibreElec and VPN.Manager and it worked fine, but few weeks ago, I encountered problem of deconnection.
The fact is it start connecting to the VPN and few seconds after it disconnects and it reconnects and so on...
I have done several fresh install and always the same.
In the openVPN log, I can read this:
"OpenVPN ROUTE6: OpenVPN needs a gateway for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
OpenVPN ROUTE: failed to parse/resolve route for host/network:2000::/3"
Someone can help me, please ?

Thanks in advance

**Comment by Zomboided** [comment]
Get a log with debug switched on

**Comment by coincoin73** [comment]
Thanks for you fast answer
This is my log
[kodi_20-01-13_15-38-34.log](https://github.com/Zomboided/service.vpn.manager/files/4054415/kodi_20-01-13_15-38-34.log)

**Comment by Zomboided** [comment]
Can you download and attach an example Cyberghost ovpn - you'll need to get
them from the Cyberghost site, with a working ID.
I'll check it against the template which I changed recently based on what
someone else sent me.

**Comment by Zomboided** [comment]
ovpn = config file for openvpn, you should be able to get these in some
kinda help section for installing Linux or routers...I don't know how
Cyberghost lay their site out.

**Comment by coincoin73** [comment]
My ID : gSQdx653ER

[openvpn.zip](https://github.com/Zomboided/service.vpn.manager/files/4055074/openvpn.zip)

**Comment by Zomboided** [comment]
in /storage/.kodi/addons/service.vpn.manager/CyberGhost (I think.....)
there will be a bunch of ovpn files.  Can you share a UDP and TCP example
please?
The thing I think it's generating is pretty much exactly what they're
supplying.  If I can validate the generation is happening correctly then
it'd be up to you to take it to CyberGhost support after running it via the
command line to eliminate the addon.

**Comment by eddi51212** [comment]
I can also confirm this behavior. When dialing into a European server e.g. Switzerland (UDP) I don't even get a successful connect.
When dialing in to a server in Albania (UDP), there is a repeated login and logout as described. My VPN provider is Cyberghost. I saw that the server address 4-1-ch.cg-dialup.net is stored in the opvn file, but in the Location.txt 87-1-ch.cg-dialup.net (changed on 23. December). Could this be the reason?

**Comment by Zomboided** [comment]
Someone else gave me an updated list of servers.  Maybe there were errors
in it.

If someone with Cyberghost wants to download an ovpn for each location, I'd
be happy to run an update to make sure all of the servers are correct.  I
cannot do this myself as I have no ID

**Comment by Antelox** [comment]
I guess @cristianaghe can help out solving this issue.

**Comment by coincoin73** [comment]
Finally, I found time to do it !!
I extract the UDP and TCP for France; but the UDP is empty (see into the zip file).

[CyberGhost.zip](https://github.com/Zomboided/service.vpn.manager/files/4082790/CyberGhost.zip)

**Comment by Zomboided** [comment]
Can you try and get UDP again please?  I want to see if the server is the same or not.  This is currently more interesting than pulling other countries.

**Comment by coincoin73** [comment]
[CyberGhost.zip](https://github.com/Zomboided/service.vpn.manager/files/4082907/CyberGhost.zip)
This is the new file, and this time the UDP file is not empty

**Comment by Zomboided** [comment]
Can you connect to France please, UDP, and then attach /storage/,kodi/addons/service.vpn.manager/Cyberghost/France (UDP).ovpn (or the file that's similarly named....)

The zip you've shared shows that I'm using the right server both for TCP and UDP, so I'd like to see how their ovpn files differ to the one that I generate.

**Comment by coincoin73** [comment]
I probably found the problem.
In your file the address of server is **remote 87-1-fr.cg-dialup.net 443**.
In the ovpn file provided by Cyberghost the address is **remote 4-1-fr.cg-dialup.net 443**
I have modified yours with this one and it seems to be correct now.
I will check deeper and I will tell you.

**Comment by coincoin73** [comment]
> 
> 
> I can also confirm this behavior. When dialing into a European server e.g. Switzerland (UDP) I don't even get a successful connect.
> When dialing in to a server in Albania (UDP), there is a repeated login and logout as described. My VPN provider is Cyberghost. I saw that the server address 4-1-ch.cg-dialup.net is stored in the opvn file, but in the Location.txt 87-1-ch.cg-dialup.net (changed on 23. December). Could this be the reason?

For me it is working

**Comment by Zomboided** [comment]
You said : "In the ovpn file provided by Cyberghost the address is remote 4-1-fr.cg-dialup.net 443"
But in the zup you posted, it's 87-1-fr-blah for UDP and 97-1-fr-blah for TCP.  Which seems to not work.

So where are you seeing 4?  This is what I had it as previously...but I'm so confused right now, it was changed on 23rd Dec because it generally wasn't work/the servers had been updated.

**Comment by Zomboided** [comment]
When you get the ovpn files, are their options for Windows or for Linux or for routers?  Or is there nothing like that?

**Comment by eddi51212** [comment]
When you set a new device in the Cyberghost account you have to choose the server. In my case when I choose the 87-1... server it does not work. Only the 4-1... works. I think you have to order a special premium dns subscription that allows to connect to the servers with a local DNS server. Mine is called "CyberGhost Premium 7 devices" When I prepare the Locations.txt and the ovpn files I have no issues. 
![Screenshot_20200119-214344_Chrome](https://user-images.githubusercontent.com/59914249/72688335-5c251c80-3b06-11ea-8bf4-d7dff1519bbd.jpg)

**Comment by Zomboided** [comment]
This is helpful, so all servers within the selected list start with
4-1-xxxx or 87-1-xxxx for UDP and, 9-1-xxxx and 97-1-xxxx?
And what about non-Europe?

**Comment by Zomboided** [comment]
Meantime, the changes I made which apparently are for LocalDNS are being reverted.  This should stop connection problems for most people.  If I understand (ie get all of the ovpn files) for LocalDNS, I'll set up an alternative locations file.

**Comment by coincoin73** [comment]
> 
> 
> When you get the ovpn files, are their options for Windows or for Linux or for routers? Or is there nothing like that?

I use it on Librelec on a raspberry.
The files I sent to you were in the service.vpn.manager\CyberGhost directory. So I assume that is your files.

**Comment by coincoin73** [comment]
Sorry to ask the question, but I am not a network specialist.
What is the difference between the standard server address and the LocalDNS one ?

**Comment by Zomboided** [comment]
Ah understand what you've posted now.  It's all good, I'm happy that I've
correctly reverted the changes and I understand why there are differences
thanks to another post in this thread.

I don't know the difference...when you connect it'll push a DNS address for
you to use.  Maybe there are issues getting to the 'standard' Cyberghost
DNSes from some countries and local DNSes overcomes this?

**Comment by Zomboided** [comment]
Closing this. If someone wants to send all of the ovpn files for the LocalDNS connections, I’ll add them, otherwise you can use the normal connections or User Defined
