### ISSUE TITLE
Autostart with addons

### ISSUE THREAD

**Issue by yomatzi** [Zomboided/service.vpn.manager#28]
Hi Zomboided,

thanks for the great addon! The autostart function with certain addons is nice, but doesn't work when using favorites. For example, starting a youtube video set as a favorite doesn't let the vpn connect. The same issue happens when working with Yatse. Navigating through Kodi with Yatse and starting a video in an addon that is set as an autostart addon for the vpn doesn't let the vpn connect.

Have you plans for future versions to handle this?

**Comment by Zomboided** [comment]
No is the short answer.  I've looked at this before.  The addon relies on a "window" being activated.  If that's not activated (ie when you direct play something via favourites or your library), I don't know what's going on.  I looked at intercepting the play event, but that happens _after_ play starts, and if the content is geo locked it doesn't start playing and therefore the play event isn't triggered.  Only way this is getting fixed is if Kodi provides a pre-play hook.

**Comment by yomatzi** [comment]
Okay, thank you for clarification!

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


--- Original Nachricht ---
Von: Zomboided <notifications@github.com>
Datum: 2. Januar 2017 11:51:29
Betreff: Re: [Zomboided/service.vpn.manager] Autostart with addons (#28)
An: Zomboided/service.vpn.manager <service.vpn.manager@noreply.github.com>
CC: yomatzi <yomatzi@gmx.de>, Author <author@noreply.github.com>
