### ISSUE TITLE
NordVPN - 429 Too many Requests

### ISSUE THREAD

**Issue by lotniak** [Zomboided/service.vpn.manager#280]
Hi

Two days ago I installed on Odroid N2 - CoreELEC (Kodi 18.5) native NordVPN app downloaded from here:

https://support.nordvpn.com/General-info/SmartPlay/1061376672/How-can-I-use-Kodi-with-NordVPN.htm

it worked couple of times - so great.

Yesterday I tried to connect and there was a problem. So I tried to redownload app from NordVPN website but above link does not exist any more:

https://support.nordvpn.com/General-info/SmartPlay/1061376672/How-can-I-use-Kodi-with-NordVPN.htm

So I found that this app is rly your app so I installed it from your repo. NordVPN app was 5.0.0 and your app I installed is 6.3.4. Still I can't connect.

Kodi log says error 429 - too many request but I don't know what that means anyway.

Any help will be any help will be appreciated.

**Comment by Zomboided** [comment]
Well if it fails with Nord's app (which I wrote anyway...) and it fails with my app, then I'd guess it a problem with Nord's service.  You should get proper debug rather than trying to relate what was in the log and take it up with their support folk.

Right now, you're the only person saying this doesn't work, and given the popularity of Nord there are a lot of people using it.  Ironically I don't have a Nord account any more to test this out.

**Comment by facakente** [comment]
I am also experiencing this issue, it worked fine until yesterday since then I am unable to connect to vpn via this addon. I can though connect on other devices, anyway I did open a support ticket with nordvpn.

**Comment by facakente** [comment]
After so many attempts at least I am able to connect to another server , by default now it connects me to Albania , which is the first country in the list , I have uninstalled and installed it again but the option to set up the first vpn connection with UK for example is no longer showing , I have ran the wizard etc but still connecting by default to Albania , then manually I can connect to uk , is there a way to force to first vpn to UK ?

**Comment by Zomboided** [comment]
The list of countries is shown to you. If you only see albania, then Nord is not returning the list of countries as expected. You need to talk to nord, not me, I’m not running their service

**Comment by facakente** [comment]
I see the list of countries , though when doing the wizard or running my first vpn connection by default it selects me Albania , there is no option to set another country.
But in the addon if changing manually I can see all countries and connect to them.

**Comment by peno64** [comment]
I am also a nordvpn user using VPN Manager for OpenVPN on libreelec on a raspberry pi and I have no problem at all.  I tried connecting to Belgium, The Netherlands, the UK, the US and South Africa and has no problems at all. All is working fine here.

**Comment by lotniak** [comment]
Ok so I isolated the problem to passwords.

If I set up password 12345678 - I can connect without any problem. If I set ie: JzXZ7su5 I can't connect.

Moreover - NordVPN deleted yesterday article about connecting through your app on Kodi:

https://support.nordvpn.com/General-info/SmartPlay/1061376672/How-can-I-use-Kodi-with-NordVPN.htm

So it's a problem either with NordVPN API or smth with passwords.

I know there was a problem couple of weeks ago with specials chars in password.

Anyway - thats all what I got.

**Comment by facakente** [comment]
I can access different servers , that is not the problem , since yesterday it stopped to work , it worked fine until then. Currently every time I try to set up my first connection , I don’t see the servers option , it connects automatically to Albania . Only way to connect to another country is changing server manually , here I do see the list of different servers, my problem is on the setup for first connection. Hope makes sense

**Comment by peno64** [comment]
Nordvpn didn't delete the article about kodi.

Go to this page: https://support.nordvpn.com/FAQ/1087246372/How-can-I-reach-NordVPN-customer-support.htm

Then in the input box type kodi and the match gives how to setup nordvpn in kodi on raspberry pi

**Comment by lotniak** [comment]
Well, this link:

https://support.nordvpn.com/General-info/SmartPlay/1061376672/How-can-I-use-Kodi-with-NordVPN.htm

does not work and it worked 2 days ago. In the article there was a link to service.vpn.manager 5.0.0.

**Comment by Zomboided** [comment]
@facakente if you’ve previously installed the nord version, go to settings/utilities and reset provider and clear downloaded files.

@peno64 if you’re bored, can you do the same and run the wizard please?

@lotniak the password issue was about using non alphanumeric passwords, both of your examples should work.  A fix was done for this weeks ago.

I definitely don’t care about nord support articles tho, discuss that with them.

**Comment by lotniak** [comment]
Thank you for answer. Well, the fact is 12345678 work and the others don't.

**Comment by facakente** [comment]
@Zomboided thanks for feedback, I have done it several times didn’t work. Anyway finally I sorted it out , just changed skin back to default osmc one and now I got the list of servers.

Resuming very weird what happened , I haven’t changed anything on my setup , likely some problem on nordvpn end, looks fine now.
