### ISSUE TITLE
vyprVPN time-out 

### ISSUE THREAD

**Issue by worldaccordingtojim** [Zomboided/service.vpn.manager#281]
I am having a problem connecting with Zomboided/service.vpn.manager. I just get a timeout error, I have port 1194 forwarded, I choose vyprVPN, I enter my email and password, it connects and pulls down a new UDP server list, I try to connect to any server, for example new York and it times out.

![IMG_8808](https://user-images.githubusercontent.com/62408748/77127013-6473d800-6a21-11ea-987b-4444b05faa88.jpeg)

**Comment by worldaccordingtojim** [comment]
Is there another VPN service that works without issue? I tried it from the command line and got this.
pi@retropie:~/.kodi/addons/service.vpn.manager/TestVPNmod $ openvpn Mexico.ovpn
Fri Mar 20 16:49:25 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Fri Mar 20 16:49:25 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Enter Auth Username: ********
Enter Auth Password: ********
Fri Mar 20 16:49:50 2020 TCP/UDP: Preserving recently used remote address: [AF_INET6]::ffff:146.112.61.106:443
Fri Mar 20 16:49:50 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Mar 20 16:49:50 2020 UDP link local: (not bound)
Fri Mar 20 16:49:50 2020 UDP link remote: [AF_INET6]::ffff:146.112.61.106:443
Fri Mar 20 16:50:50 2020 [UNDEF] Inactivity timeout (--ping-restart), restarting
Fri Mar 20 16:50:50 2020 SIGUSR1[soft,ping-restart] received, process restarting
Fri Mar 20 16:50:50 2020 Restart pause, 5 second(s)
Fri Mar 20 16:50:55 2020 TCP/UDP: Preserving recently used remote address: [AF_INET6]::ffff:146.112.61.106:443
Fri Mar 20 16:50:55 2020 TCP/UDP: Preserving recently used remote address: [AF_INET6]::ffff:146.112.61.106:443
Fri Mar 20 16:50:55 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]
Fri Mar 20 16:50:55 2020 UDP link local: (not bound)
Fri Mar 20 16:50:55 2020 UDP link remote: [AF_INET6]::ffff:146.112.61.106:443
Fri Mar 20 16:50:55 2020 write UDP: Address family not supported by protocol (code=97)
Fri Mar 20 16:50:57 2020 write UDP: Address family not supported by protocol (code=97)
Fri Mar 20 16:51:01 2020 write UDP: Address family not supported by protocol (code=97)
^CFri Mar 20 16:51:04 2020 event_wait : Interrupted system call (code=4)
Fri Mar 20 16:51:04 2020 SIGINT[hard,] received, process exiting

**Comment by Zomboided** [comment]
Maybe the VyprVPN settings are out of date, I don't use that provider so I
need to check.  They all should work.  People whine at me when they don't.
Or you can use the User Defined wizard with whatever you can download from
VyprVPN (or any other provider)  It's all documented on the wiki how to do
it.

**Comment by worldaccordingtojim** [comment]
Here are the current files from VyprVPN settings.

[GF_OpenVPN_10142016.zip](https://github.com/Zomboided/service.vpn.manager/files/4361891/GF_OpenVPN_10142016.zip)
