### ISSUE TITLE
up.sh and down.sh scripts for LibreElec - DNS Leakage

### ISSUE THREAD

**Issue by GewoonGijs** [Zomboided/service.vpn.manager#282]
Hi Zomboided,

I use your VPN manager on my LibreElec raspberry Pi box. The recipe you provide to protect against potential DNS leakage, is not working for this configuration, since DNS resolving is done by  connmand. 

Therefore I made my own up.sh and down.sh to process the DNS paramaters as they are provide by the DNS server.

**Comment by Zomboided** [comment]
Can you attach these as files please and I'll link to them from wiki page
that talks to this stuff.
I'm sure they'll be very useful to those that need them, thanks for sharing.

**Comment by GewoonGijs** [comment]
Sorry, I tried, but Github doesn't accept .sh files as attachment. And now there is a second issue with the same content, Sorry. I am not so experienced with Github yet.

**Comment by Zomboided** [comment]
can you attach them as .txt?

**Comment by GewoonGijs** [comment]
[down.sh.txt](https://github.com/Zomboided/service.vpn.manager/files/4361544/down.sh.txt)
[up.sh.txt](https://github.com/Zomboided/service.vpn.manager/files/4361545/up.sh.txt)

**Comment by Zomboided** [comment]
Thanks, will tidy this issue up and then reference it.  Appreciate it.
