### ISSUE TITLE
DNS Leakage on LibreElec raspberry Pi - up.sh and down.sh

### ISSUE THREAD

**Issue by GewoonGijs** [Zomboided/service.vpn.manager#283]
Please use this issue for any continued discussion with the scripts shared in [issue 282](https://github.com/Zomboided/service.vpn.manager/issues/282)

This issue is being closed because it's not a problem with the add-on, but it's still useful to share the knowledge on how to address DNS leakage across different platforms

**Comment by GewoonGijs** [comment]
[up.sh.txt](https://github.com/Zomboided/service.vpn.manager/files/4361681/up.sh.txt)

Sorry, I noticed that the connmanctl creates an unwanted route to the DNS server via eth1, so I have to remove these as well.  Corrected script is attached

**Comment by Zomboided** [comment]
Thanks, can you confirm the right one is attached in this issue please
https://github.com/Zomboided/service.vpn.manager/issues/282

**Comment by GewoonGijs** [comment]
Yes, it si the one attached in the comment above in this issue.

**Comment by GewoonGijs** [comment]
The attached file in #282 doesn't contain the removal of the routes.

**Comment by davideraghz** [comment]
> 
> 
> The attached file in #282 doesn't contain the removal of the routes.

would you mind creating a tutorial or something similar to a step by step guide to follow for newbies with linux in general? my expressvpn setup  on ovpnmanager keeps on dns leaking and i  cant seem to resolve it; your post seems would meet my needs but don't know which steps to make

im on libreelec.
Thanks!

**Comment by davideraghz** [comment]
If you change your down scripts like this, it will connect without fail after a reboot, without leaking still.
connmanctl config ethernet_"mac"_cable --nameservers DNSSEC allow-downgrade DOMAIN-ROUTE

**Comment by davideraghz** [comment]
If you modify your down.sh like this it will autoconnect after a reboot.

`connmanctl config ethernet_dca632501a95_cable --nameservers DNSSEC allow-downgrade DOMAIN-ROUTE`

**Comment by davideraghz** [comment]
If you modify your down.sh like this it will autoconnect after a reboot.

`connmanctl config ethernet_yourmacad_cable --nameservers DNSSEC allow-downgrade DOMAIN-ROUTE`

**Comment by davideraghz** [comment]
If you modify your down.sh like this it will autoconnect after a reboot.

`connmanctl config ethernet_yourmacad_cable --nameservers DNSSEC allow-downgrade DOMAIN-ROUTE`

**Comment by Zomboided** [comment]
You don’t want to force an auto connect, the addon takes care of that. If you do force an auto connect then it’s likely the addon will kill it anyway (or get confused and things might behave unexpectedly)

**Comment by davideraghz** [comment]
> 
> You don’t want to force an auto connect, the addon takes care of that. If you do force an auto connect then it’s likely the addon will kill it anyway (or get confused and things might behave unexpectedly)
> […](#)
> On 26 Mar 2020, at 14:10, davideraghz ***@***.***> wrote: ﻿ If you modify your down.sh like this it will autoconnect after a reboot. connmanctl config ethernet_yourmacad_cable --nameservers DNSSEC allow-downgrade DOMAIN-ROUTE — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

i explained my self wrongly, yeah i have that option enabled in the addon and it's way it autoconnect on boot; but before i changed the down script adding this lines for my DNS " DNSSEC allow-downgrade DOMAIN-ROUTE" i had inserted them manually like  @GewoonGijs  did in his down script and every time i rebooted vpn would fail to connect now it doesnt

**Comment by davideraghz** [comment]
i think in my case it would fail to connect beacouse after a reboot it was forcefully trying to connect to my vpn IP that was places inside the down script but since the IP changes every time i reconnect to the VPN they were different and so the fail, now i guess it autogets on every boot the new IP to connect to

**Comment by mflorezm** [comment]
Hi GewoonGijs, do you have a complete tutorial on how to use your up and down scripts? how to write the scripts? i found that we have to replace the mac address on it, right? (it is not explained anywhere) I'm using LibreELEC 9.2.5 (Leia 18.8). I wrote both scripts on /storage/.kodi/userdata/addon_data/service.vpn.manager/ and i gave execute permisions, but VPN Manager don't use them even as i have the check box on true state on Enable up/down scripts (settings). Nevertheless, The scripts can be run by SSH, and changes the the etc/resolv.conf file accordly. So, the up scripts works well and the VPN connects and I can stream geo block media (stopping DNS leaking), but once vpn is disconnected and run the down.sh thru ssh console, other add-ons still don't work even as the etc/resolv.conf is changed again, so, it seem that something is not comming back to the original state. Any help will be welcome. Thanks. MFM

**Comment by spooker** [comment]
Documentation about how to use the scripts 
https://github.com/Zomboided/service.vpn.manager/issues/282
is very poor.

Here is what I did to make it work with
LibreElec 10.0.2 and surfShark

add the attached up.sh and down.sh 
under 
~/.kodi/userdata/addon_data/service.vpn.manager/UserDefined

decompress the files first
[up.zip](https://github.com/Zomboided/service.vpn.manager/files/8891418/up.zip)
[down.zip](https://github.com/Zomboided/service.vpn.manager/files/8891419/down.zip)

both files have references to "ethernet_dca632be9ffa_cable"
you need to change that with the string that the following command outputs
connmanctl services 
In my case the output was
"*AO Wired                ethernet_dca632be9ffa_cable"
so this is what I use.

you need to make the scripts executable
chmod +x up.sh
chmod +x down.sh

up.sh runs when vpn connects. It will change the dns entries.
You can verify that with 
cat /etc/resolv.conf

down.sh runs when vpn disconnects and resets the dns entries to the desired values.
In my case I use google dns 8.8.8.8 8.8.4.4 in down.sh
so after a disconnection you would be able to verify with 
cat /etc/resolv.conf
that you now see 
google dns in there.

go to Vpn Manager setting in "Advanced" tab and enable
"Enable up/down scripts (reset VPN after updating)"

go to VPN Configuration Tab and 
Click here to update VPN setting. A popup will notify to reset all VPN connections. Press Yes.
Then press OK
Go to the VPN connections tabs and configure your First Vpn Connection and press OK and you should be all set
