### ISSUE TITLE
How to add command "killall" and "pidof" using OpenVPN in Kodi 18.6

### ISSUE THREAD

**Issue by Psunabudes** [Zomboided/service.vpn.manager#284]
I am not able to get OpenVPN started in Kodi18.6 all .ovpn files provided, but service manager request command "killall" and "pidof" to be installed from command line. HOW??? Can someone help with simple wording?

**Comment by Zomboided** [comment]
There are some words in the wiki, or you could just use google...these are not related to this add on and I don't want to spend time documenting how to use standard Linux features

**Comment by nicofirk** [comment]
Hi Zomboided, I have the exact same issue and found no answer anywhere.
I'm running Kodi on an Android Smart TV (beamer), and cannot get an addon to run because of KillAll and Pidof commands not installed.
It's not like you can sudo/apget them.
There's no command line to my knowledge.
Is there a repo where KillAll and Pidof can be fetched?
Thanks!

**Comment by peno64** [comment]
@nicofirk 
Very unlinkely. repos/addons contain *kodi* addons. Not  binary addons on os level.
I don't know how it is with an android system but with any linux system you can make a connection with for example putty to get a command line window...

**Comment by Zomboided** [comment]
It doesn't work with Android.  There are no plans to change this.

**Comment by nicofirk** [comment]
Ah, great, now I get it..
This is clear
Many thanks

**Comment by smart20172017** [comment]
Is it possible to directly use python API to get pid and kill by pid, instead relying on shell commands? majority of kodi users are on android, which doesn't have these commands.

**Comment by Hping3-hope** [comment]
I got the same problem on Raspberry PI OS. Just install OpenVPN Client, than it worked for me. libreElec does include this already.
