### ISSUE TITLE
Connexion tap0 : Fix IP Adress or MAC Adress

### ISSUE THREAD

**Issue by osmoze06** [Zomboided/service.vpn.manager#287]
Hello,
I want to set the MAC address of the tap0 connection generated during the OpenVPN connection, I cannot. (It changes with each connection and impossible to define a fixed local IP address via DHCP).

I tried changing the MAC address in my client file (.ovpn) but it doesn't work.
I wanted to set an IP address but I end up with two IPs on Freebox Server Open VPN (one address defined by DHCP and the other that I put in my .ovpn file.

I also tried with a startup.sh file to change the MAC address in LibreElec, but it doesn't work either.

Or can I force the MAC address in the plugin before connection or the IP address?

Thanks for your help !

**Comment by Zomboided** [comment]
This add-on “just” calls openvpn, it doesn’t manipulate any part of the network. If the tools are available to do what you want then you can look in the wiki to understand how to call them using up and down scripts as you make and break connections.  I’ve no idea to how you’d achieve what you want, never needed to do this.
