### ISSUE TITLE
CyberGhost netherlands (UDP)

### ISSUE THREAD

**Issue by donseba** [Zomboided/service.vpn.manager#288]
Hi, not sure why though BUT i had to manually alter the Netherlands (UDP).ovpn file and change the host from 

`remote 4-1-nl.cg-dialup.net 443` to `remote 87-1-nl.cg-dialup.net 443` 

full file contents of the cyberGhost vpn file 

```
client
remote 87-1-nl.cg-dialup.net 443
dev tun 
proto udp
auth-user-pass


resolv-retry infinite 
redirect-gateway def1
persist-key
persist-tun
nobind
cipher AES-256-CBC
auth SHA256
ping 5
ping-exit 60
ping-timer-rem
explicit-exit-notify 2
script-security 2
remote-cert-tls server
route-delay 5
verb 4


ca ca.crt

cert client.crt

key client.key
```

**Comment by Zomboided** [comment]
Just pushed a Cyberghost update that they provided
