### ISSUE TITLE
PureVPN Problems

### ISSUE THREAD

**Issue by sllem** [Zomboided/service.vpn.manager#29]
Hi, i tried 10 hours to run OpenVPN in LibreElec with your VPN Manager. What ever i tired it fails and fails and fails. PLEASE, can anyone help me?

Wed Jan  4 04:39:16 2017 OpenVPN 2.3.14 armv7ve-libreelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [EPOLL] [IPv6] built on Dec 22 2016
Wed Jan  4 04:39:16 2017 library versions: LibreSSL 2.4.4, LZO 2.09
Wed Jan  4 04:39:16 2017 WARNING: file '/storage/.kodi/addons/service.vpn.manager/PureVPN/pass.txt' is group or others accessible
Wed Jan  4 04:39:16 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Wed Jan  4 04:39:16 2017 WARNING: file '/storage/.kodi/addons/service.vpn.manager/PureVPN/ta.key' is group or others accessible
Wed Jan  4 04:39:16 2017 Control Channel Authentication: using '/storage/.kodi/addons/service.vpn.manager/PureVPN/ta.key' as a OpenVPN static key file
Wed Jan  4 04:39:16 2017 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jan  4 04:39:16 2017 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jan  4 04:39:16 2017 Socket Buffers: R=[163840->163840] S=[163840->163840]
Wed Jan  4 04:39:16 2017 UDPv4 link local: [undef]
Wed Jan  4 04:39:16 2017 UDPv4 link remote: [AF_INET]172.111.233.2:53
Wed Jan  4 04:39:16 2017 TLS: Initial packet from [AF_INET]172.111.233.2:53, sid=5f557226 e533912f
Wed Jan  4 04:39:16 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Jan  4 04:39:17 2017 VERIFY OK: depth=1, C=HK, ST=HK, L=HongKong, O=PureVPN, OU=IT, CN=PureVPN, name=PureVPN, emailAddress=mail@host.domain
Wed Jan  4 04:39:17 2017 VERIFY OK: depth=0, C=HK, ST=HK, L=HongKong, O=PureVPN, OU=IT, CN=PureVPN, name=PureVPN, emailAddress=mail@host.domain
Wed Jan  4 04:40:16 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Jan  4 04:40:16 2017 TLS Error: TLS handshake failed
Wed Jan  4 04:40:16 2017 SIGUSR1[soft,tls-error] received, process restarting
Wed Jan  4 04:40:16 2017 Restart pause, 2 second(s)
Wed Jan  4 04:40:18 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Wed Jan  4 04:40:18 2017 Socket Buffers: R=[163840->163840] S=[163840->163840]
Wed Jan  4 04:40:18 2017 UDPv4 link local: [undef]
Wed Jan  4 04:40:18 2017 UDPv4 link remote: [AF_INET]172.111.233.2:53

I tried with "User Defined" and on and on, i dont get it work. On my PC with one klick all is running, will mean the Account him self is working.

**Comment by Zomboided** [comment]
This is your issue:
Wed Jan 4 04:40:16 2017 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Jan 4 04:40:16 2017 TLS Error: TLS handshake failed

Google suggests this : https://openvpn.net/index.php/open-source/faq/79-client/253-tls-error-tls-key-negotiation-failed-to-occur-within-60-seconds-check-your-network-connectivity.html

Assuming that this happens with all Pure connections, and you've not found one that doesn't work (other people are using Pure without issue), then your network is the issue.
