### ISSUE TITLE
VLAN issue

### ISSUE THREAD

**Issue by libolt** [Zomboided/service.vpn.manager#292]
I have a file server which is on a different VLAN than my LibreElec box. The problem is that when I use the VPN Manager service and connect to my NordVPN account I lose access to this service which I have mounted NFS shares on that I need for Kodi. Is it possible to still route the traffic for this network? Right now the inter-VLAN routing is handled by my linux based router with a custom IP Tables setup.

I have another linux box that uses open vpn directly and to get to the server network I add the following to my .ovpn files to work around it.

route 192.168.44.0 255.255.255.0 net_gateway

**Comment by Zomboided** [comment]
I can’t advise on how to route...you need to trawl openvpn forums for advice on that. The wiki details how you can use up/down scripts or add additional lines to the ovpn connection files to issue the relevant route commands once you understand what they are
