### ISSUE TITLE
Add Astrill VPN

### ISSUE THREAD

**Issue by x9t9** [Zomboided/service.vpn.manager#295]
First of all - superb Add-on and super usefull..

It would be very helpful if  Astrill VPN service would be added to VPN manager. service list.
This is a very popular ( and strong ) VPN service.

**Comment by Zomboided** [comment]
No, user defined is the way forward for new providers . It’s too much effort to just maintain the ones that are there

**Comment by x9t9** [comment]
Ok, I understand, a and this is how I operate now, If I would implement this via PR would you consider merging it ? Astrill is quite a popular and large provider.

**Comment by Zomboided** [comment]
No, no more providers period.  User defined works fine.
