### ISSUE TITLE
Settings Window empty / Settings file gone

### ISSUE THREAD

**Issue by x9t9** [Zomboided/service.vpn.manager#296]
I know that this issue is somewhat related or even a Dupe of ( #170, #230 ) but it seems that it is not totally resolved so I am posting my own issue description that is related .

I have an issue with this excellent add-on which I could not resolve for a long time.
The issue is that the setting window appears Blank ( screenshot below ) and because of that, the setting wizard window appears every time at reboot.

This problem appears only with this addon ( which otherwise is really excellent ) - I have tried to uninstall / install the add-on many times but no success.

Strange thing is that I have 3 different boxes with more or less same config and the problem appears on all of them .

Screenshot is below :

![screenshot000](https://user-images.githubusercontent.com/23067248/83938458-fa402780-a806-11ea-990e-a4e58d2bae0a.png)

Kodi in on rPi , Librelec :
![screenshot001](https://user-images.githubusercontent.com/23067248/83938503-56a34700-a807-11ea-8a7c-a7a306112514.png)

Add-On version 6.3.4

![screenshot002](https://user-images.githubusercontent.com/23067248/83938508-63279f80-a807-11ea-9d00-52adc42087da.png)

After reading #230 and #170 I can confirm that my `settings.xml` located at `/storage/.kodi/userdata/addon_data/service.vpn.manager/` is also `0` byte.

I have tried to remove this file completely an re-install but again few times - to no avail.

I also have a feeling that the problem initiated on the same time more or less of installing the `Zomboided tools` plugin ( could they be somehow related ? ) but I have no way of verifying that because on the same day I have made some other tweaks and installs....

**Comment by Zomboided** [comment]
The general kodi settings code changed a lot with v18 and you’re running a pretty old version.  You should upgrade Kodi to something less broken, delete everything in the userdata directory for VPN Mgr and reinstall it.

Generally I think the problem that was being seen before is closed but this can still happen if something corrupts the settings file (power down, bad Sdcard, etc)

If you recreate this with a log against the latest version reopen this and I’ll take a look
