### ISSUE TITLE
"route add" command failed for Hide.me VPN

### ISSUE THREAD

**Issue by iz8mbw** [Zomboided/service.vpn.manager#3]
Hi.
I have tried VPN Manager with IPVanish without problem.
Now I'm trying Hide.me VPN, but with Hide.me VPN Manager can connect to Hide.me and bring up the "tun0" interface but all traffic will go through eth0, so not via VPN.
Looking into log the problem is the command "route add" that fails:
`ERROR: Linux route add command failed: external program exited with error status: 2`

I'm using the last version of VPN Manager on OpenELEC 6.0.3 on a Raspberry Pi 2.

See here full log from Kodi:

![route_failed](https://cloud.githubusercontent.com/assets/3474082/18048105/87052900-6de0-11e6-9fe9-8fb83062e335.jpg)

![vpn_log](https://cloud.githubusercontent.com/assets/3474082/18013330/cac5f4be-6bbd-11e6-8c9a-0c20bbab5fc4.png)

From shell:

OpenELEC:~ # **ifconfig -a**
**eth0**      Link encap:Ethernet  HWaddr B8:27:EB:C0:46:11
          inet addr:192.168.1.65  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::ba27:ebff:fec0:4364%1994934592/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          **RX packets:1745 errors:0 dropped:0 overruns:0 frame:0**
          **TX packets:1630 errors:0 dropped:0 overruns:0 carrier:0**
          collisions:0 txqueuelen:1000
          **RX bytes:893468 (872.5 KiB)  TX bytes:260123 (254.0 KiB)**

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%1994934592/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:18 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:3690 (3.6 KiB)  TX bytes:3690 (3.6 KiB)

**tun0**      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.3.164.96  P-t-P:10.3.164.96  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          **RX packets:0 errors:0 dropped:0 overruns:0 frame:0**
          **TX packets:0 errors:0 dropped:0 overruns:0 carrier:0**
          collisions:0 txqueuelen:100
          **RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)**

OpenELEC:~ # **route**
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
**default         192.168.1.1   0.0.0.0         UG    0      0        0 eth0**
**10.3.164.0      *               255.255.255.0   U     0      0        0 tun0**
146.185.16.54   192.168.1.1   255.255.255.255 UGH   0      0        0 eth0
192.168.1.0   *               255.255.255.0   U     0      0        0 eth0
192.168.1.1   *               255.255.255.255 UH    0      0        0 eth0

**Comment by iz8mbw** [comment]
Hi.
This problem can be workarounded by adding "redirect-gateway def1" to the .ovpn client configuration file, but the routing table will no be "perfect".
I find a solution with a shell script, se here:  http://openelec.tv/forum/unofficial-openelec-addons/79666-vpn-manager-for-openvpn?start=555#166378

I hope my script will be implemented.
Thanks!

**Comment by Zomboided** [comment]
This is a problem with the base platform, and the solution outlined does not fix the issue, it works around it.  No changes required in this code to properly support Hide.Me
