### ISSUE TITLE
Permissions issue with sudo options using 2.2.9 on Lubuntu 16.04

### ISSUE THREAD

**Issue by cotman** [Zomboided/service.vpn.manager#30]
Hi,

Apologies in advance if I'm doing something silly here...

I'm using Kodi 17 on Lubuntu 16.04, and Kodi is running as the user "generic".

In the Debug settings I have "Use sudo with openvpn and killall" selected as "Always", but when I do that I get the "The OpenVPN executable isn't working" dialogue, and the following in the logs:

    18:39:13.262 T:139774274828032    NONE: VPN Mgr Debug: Requested update to service process via settings monitor
    18:39:13.263 T:139774274828032    NONE: VPN Mgr Debug: Update service requested KodiMonitor
    18:39:13.265 T:139774148937472    NONE: VPN Mgr Debug: Requested update to service process via settings monitor
    18:39:13.267 T:139774148937472    NONE: VPN Mgr Debug: Update service requested KodiMonitor
    18:39:13.330 T:139774140544768 WARNING: CPythonInvoker(30): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
    18:39:13.522 T:139774140544768    NONE: VPN Mgr Debug: Entered connect.py with parameter 1
    18:39:13.527 T:139774140544768    NONE: VPN Mgr Debug: Checking openvpn can be run
    18:39:13.531 T:139774140544768    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
    18:39:13.546 T:139774140544768  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : sudo /usr/sbin/openvpn > /home/generic/.kodi/temp/openvpn.log &
    18:39:14.346 T:139774274828032    NONE: VPN Mgr Debug: VPN monitor service was requested to run an update
    18:39:14.350 T:139774274828032    NONE: VPN Mgr Debug: Update primary VPNs from settings
    18:39:14.355 T:139774274828032    NONE: VPN Mgr Debug: Found no VPNs, setup is invalid
    18:39:14.357 T:139774274828032    NONE: VPN Mgr Debug: Update filter lists from settings
    18:39:14.558 T:139774140544768   ERROR: VPN Mgr : (platform.py) Ran openvpn command and it failed
    18:39:14.560 T:139774140544768  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
    18:39:14.560 T:139774140544768  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end

I also get the same behaviour with "Platform default".

If I switch the setting to "Never", then I get to select a profile and all looks good, but (after a long delay) I then get the following error, amongst the informational log output.

    18:45:21.295 T:139774107535104  NOTICE: Sat Jan  7 18:44:07 2017 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
    18:45:21.295 T:139774107535104  NOTICE: Sat Jan  7 18:44:07 2017 Exiting due to fatal error

If I run `openvpn` on the command line, using `sudo`, with the service.vpn.manager generated `.ovpn` file, then all is well and there's no `TUNSETIFF` error.

Thanks.

**Comment by Zomboided** [comment]
Try running openvpn with "sudo /usr/sbin/openvpn > /home/generic/.kodi/temp/openvpn.log &"

The second error isn't one I'm issuing and you've chopped out the rest of the log, but I suspect it's related to an inability to inquire whether a task is runnig or kill a running task without sudo, both of which need to work.

**Comment by cotman** [comment]
Ah - with backgrounding, the log was empty...then I twigged ;) - the user has a password, so no means of entering it with backgrounding.

Updating the user to have passwordless sudo rights and all is well - working a treat now.

Thanks.
