### ISSUE TITLE
VPN Unlimited not working

### ISSUE THREAD

**Issue by Nigel1992** [Zomboided/service.vpn.manager#300]
Hello,

I am trying to use my VPN Unlimited account with the latest version of the OpenVPN Manager.
I followed the guide provided by VPN unlimited, but it did not work.
[https://www.vpnunlimitedapp.com/blog/how-to-setup-vpn-on-kodi-devices/]

Things I've tried:
- Followed the official guide made by VPN Unlimited for Kodi [see above].
- Setup wizard and selecting VPN Unlimited + Selecting the .ovpn file.
- Editing the .ovpn files as mentioned @ https://github.com/Zomboided/service.vpn.manager/issues/8#issuecomment-269908668
- Using both device and global config credentials.
- A few Addon-reset's [but I forgot on what part I was haha]+ 1 addon-reinstall.

Logfile: https://paste.kodi.tv/ixototupeb.kodi or https://pastebin.com/2CrrvYCW
This is the page for Manual Configurations on VPN Unlimited's website.
![image](https://user-images.githubusercontent.com/5491930/88471489-8b2fa700-cf0a-11ea-8684-82dea7bdb692.png)

Any help would be appreciated =)

@Zomboided I am willing to give you my credentials so you can debug it more easily if you'd like.

**Comment by Zomboided** [comment]
"it did not work" is not helpful.
See the troubleshooting guide on the wiki

**Comment by Nigel1992** [comment]
Fixed by disabling my local port forward for my own OpenVPN server in router.
