### ISSUE TITLE
Support Batocera Kodi

### ISSUE THREAD

**Issue by superxuxin** [Zomboided/service.vpn.manager#301]
Cannot make openvpn work due to lack of sudo on batocera. It does have openvpn installed under root. I do not see an option to disable sudo in the plugin advanced setting. Please make it available. Thanks!

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#use-sudo-with-openvpn-and-killall-linux-only

**Comment by superxuxin** [comment]
Maybe the addon does not recognize batocera is a linux system so the "use-sudo-with-openvpn-and-killall-linux-only" option does not show up at all. I guess this is the specific issue.

**Comment by superxuxin** [comment]
@Zomboided

**Comment by Zomboided** [comment]
Get a log, I'm not installing this to test it myself

**Comment by superxuxin** [comment]
What log are you referring to? Where to download from the addon?

**Comment by Zomboided** [comment]
It's all in the wiki.....

**Comment by superxuxin** [comment]
Got this working. For anyone who has the same issue, here is a very simple solution.
1. create a file: vim /bin/sudo
2. put this content inside: 
#!/bin/sh
"$@"
3. chmod +x /bin/sudo

It basically gets around the sudo command. Then everything else should work.

I was motivated by the arrogance and ignorant replies from Zomboided. The wiki is not helpful by the way.

**Comment by Zomboided** [comment]
I’m sorry you can’t read simple instructions. I’m happy you got this working
