### ISSUE TITLE
how to setup with  a vpn that has only a user and password

### ISSUE THREAD

**Issue by peno64** [Zomboided/service.vpn.manager#305]
This is more a question and not a problem report.
At home, I have setup a vpn in my router such that I can connect from anywhere in the world to that vpn and then it is as if my device is at home. This is important for geolocked streams I want  to watch but do not work with a payed vpn because they are blocked.
This own vpn only needs a user name and a password. I do not have ovpn file or so.

How do I connect to this vpn withvpnmanager?

**Comment by Zomboided** [comment]
The ovpn contains the different parameters that are expected by the server
that you've set up - such as the connection method, the URL, the port, the
security requirements (ie username/pass).  If you've set this up in your
router then you need to go google or understand the defaults for that
server and then just copy an ovpn file that already exists.  When you have
that ovpn you can feed it into the user defined wizard and it will probably
just set it up for you based on that.  What it can't do is guess at what
it's connecting to...there are literally 100s of options on openvpn - go
look at the manual - probably 10-15 are commonly used for sure, but pretty
much every provider (ie server implementation) is different.

**Comment by peno64** [comment]
Ok I can try this, but what should I do with the certificate section (<ca> ... </ca>) and the static key (<tls-auth> ... </tls-auth>) or are these also optional and maybe not needed in my case?

**Comment by Zomboided** [comment]
See previous reply...I don't know how your server is set up or what
authentication it needs.
