### ISSUE TITLE
Unable to connect to PIA

### ISSUE THREAD

**Issue by DanielLBarlow** [Zomboided/service.vpn.manager#306]
Hi
I am currently trying to set up a PIA VPN onto libreELEC and seem to be having an issue doing so. 
I have followed through the wiki you have provided on this github but when I go through the wizard and choose the country to connect to for the first point of connection the loading bar will go across and then it will fail and time out. I have tried to use a couple different countries but still had the same result. 
I have provided the initial error after it fails and the log that is attached but to me I do not see anything directly obvious for the issue. Let me know if you need something else provided
Thanks
![error_1](https://user-images.githubusercontent.com/58518273/96494636-88f59400-123e-11eb-9c57-f5ede8a7a272.jpg)
![error_2](https://user-images.githubusercontent.com/58518273/96494648-8bf08480-123e-11eb-8e71-f6b766b20498.jpg)

**Comment by Zomboided** [comment]
I pushed out a change that PIA checked in without testing it, and then
reverted it sometime yesterday.  I found I could not connect to Southampton
for reasons that weren't clear, so I switched to London and it worked
fine.  Which locations did you try?  Assuming you're using LibreELEC or
similar, can you share an ovpn example from
/storage/.kodi/addons/service.vpn.manager/PIA

**Comment by DanielLBarlow** [comment]
I tried to use the London connection actually as well as Southampton. I also tried Melbourne and Chicago too just to see if they worked as well.
The below text is the output from when I have gone to `cd /storage/.kodi/addons/service.vpn.manager/PIA` and then entered `openvpn UK\ London\ \(UDP\).ovpn`

`Mon Oct 19 21:02:12 2020 WARNING: file '/storage/.kodi/addons/service.vpn.manager/PIA/pass.txt' is group or others accessible
Mon Oct 19 21:02:12 2020 OpenVPN 2.4.7 armv7ve-libreelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [AEAD] built on Jul 29 2020
Mon Oct 19 21:02:12 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Mon Oct 19 21:02:12 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]81.99.162.48:1197
Mon Oct 19 21:02:12 2020 UDP link local: (not bound)
Mon Oct 19 21:02:12 2020 UDP link remote: [AF_INET]81.99.162.48:1197
Mon Oct 19 21:02:42 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting
Mon Oct 19 21:02:42 2020 SIGTERM[soft,ping-exit] received, process exiting
`

The information here looks to be identical to what is in the photos I have in my original post

**Comment by Zomboided** [comment]
Can you show me the contents of the London ovpn file you see in that
directory...I saw what you see before I reverted the change and I'm wanting
to see what the ovpn file looks like you're using.

**Comment by DanielLBarlow** [comment]
I'm sorry, you'll have to excuse my ignorance. I thought the output I provided was what you were asking for, as it is the output I got for UK London....
I was able to nano into the file if this is what you mean but if not then I'm unsure
`client
dev tun
proto udp
remote uk-london.privateinternetaccess.com 1197
resolv-retry 30
nobind
persist-key
persist-tun
cipher aes-256-cbc
auth sha256
tls-client
remote-cert-tls server
auth-user-pass /storage/.kodi/addons/service.vpn.manager/PIA/pass.txt
compress
verb 1
reneg-sec 0
crl-verify /storage/.kodi/addons/service.vpn.manager/PIA/crl.rsa.4096.pem
ca /storage/.kodi/addons/service.vpn.manager/PIA/ca.rsa.4096.crt
disable-occ
ping 5
ping-exit 30
ping-timer-rem
script-security 2
remap-usr1 SIGTERM
`

**Comment by Zomboided** [comment]
Go to settings, then under utilities delete the downloaded files and reset
the VPN provider.  Try again but select the default encryption (not
strong).  Same result?
I've just tested this and have connected to London and Argentina.  I'll
look at strong encryption meantime.

**Comment by Zomboided** [comment]
@DanielLBarlow Sorry for the hassle, PIA have been changing their service and keeping up with the changes has been a challenge...I use this service and up until today it's been pretty painless.

For reference, and anyone else having the same issue, PIA now requires you to use the same ID you log onto the account area with - it used to require the SOCKS/PPTP/L2TP user and password be used.  Using the SOCKS/etc user and password will not work when you pick up the latest update so you'll need to revalidate.

If you're having issues with PIA, go to the Settings GUI in the add-on, reset the VPN and clear the downloaded files.  Then using the correct user and pass, try and reconnect again.  If it still doesn't work, then open an new issue with a full debug log as per the instructions on the troubleshooting page on the wiki.

**Comment by DanielLBarlow** [comment]
Thank you for the help you have provided. I much appreciate it.
I have just followed the instructions you gave above in relation to deleting the downloaded files and then using default encryption and connecting with the London connection I have no gotten a successful connection it looks like...So hopefully, fingers crossed it's all good for now.
Once again thank you for the quick help provided
