### ISSUE TITLE
[hide.me] not working since updating vpn connections

### ISSUE THREAD

**Issue by bierbaron2** [Zomboided/service.vpn.manager#307]
Since I updated the VPN connections yesterday, just because I was told to do so in the pop up, nothing works anymore. I have no idea what the reason could be, I've been experimenting a bit, but my expertise is not sufficient enough. The log is attached..

[openvpn.log](https://github.com/Zomboided/service.vpn.manager/files/5434827/openvpn.log)

**Comment by Zomboided** [comment]
The log says the connection worked.  Why do you think it didn't?

**Comment by bierbaron2** [comment]
When the connection is displayed (no matter which virtual network I connect to), it shows my IP address and not the one of the VPN service. I can upload a photo right away.

**Comment by Zomboided** [comment]
The connections were refreshed in mid September because someone sent me an
updated set and checked that they worked (apparently).  Can you go and get
me an example of a Linux UDP ovpn file from the Hide.me webset to one of
the connections you've tried and I'll compare.  I can't cross check that
with what was there before - which you're saying worked fine?

**Comment by bierbaron2** [comment]
client
dev tun
proto udp
remote amsterdam.xxxxxxxxxxx.net 3000
cipher AES-256-CBC
auth SHA256
resolv-retry 30
nobind
persist-key
persist-tun
mute-replay-warnings
verb 1
auth-user-pass /storage/.kodi/addons/service.vpn.manager/HideMe/pass.txt
reneg-sec 900
remote-cert-tls server
verify-x509-name "*.hide.me" name
tls-version-min 1.2
ca /storage/.kodi/addons/service.vpn.manager/HideMe/ca.crt
tls-crypt /storage/.kodi/addons/service.vpn.manager/HideMe/ta.key
ping 5
ping-exit 30
ping-timer-rem
script-security 2
remap-usr1 SIGTERM

![IMG_0157](https://user-images.githubusercontent.com/73430843/97218086-7cd27f00-17c8-11eb-9e10-3910c7c9a7be.JPG)

**Comment by Zomboided** [comment]
That’s an ovpn downloaded from your service provider or one that’s downloaded by my addon? I need to see what your service provider thinks is a valid ovpn file

**Comment by bierbaron2** [comment]
This is a good point. I got the ovpn file via ssh from Pi, so this one is from you. Hide.me itself referred to your add-on during configuration with LibreELEC. 
What I found in the router configuration is the following:
Settings will expand and you need to fill the following information
\n\n Input your desired "Server Address/Port" ie. "xx.hide.me".
\n\n *You can find the list of all available locations in the members area.
\n\n Set "Port" to "3000"
\n\n Set "Tunnel Device" to "TUN"
\n\n Set "Tunnel Protocol" to "UDP"
\n\n Set "Encryption Cypher" to "AES-256 CBC"
\n\n Set "Hash Algorithm" to "SHA256"
\n\n Set "User Pass Authentication" to "Enable" and enter your hide.me username and password.
\n\n * If this option does not exist you will need to add it in Step 3.
\n\n Set "Advanced Options" to "Enable"
\n\n Set "TLS Cipher" to "None"
\n\n Set "Compression" to "Disable"
\n\n Set "NAT" to "Enable"
\n\n Set "Firewall Protection" to "Enable"
\n\n Tick (enable) "\Verify Server Cert"
\n\n Set "TLS Key choice" to "TLS Crypt"

Copy the whole contents of hide.me static key file into "TLS Key"

Copy the following into "Additional Config";

mute-replay-warnings
reneg-sec 0
verify-x509-name *.hide.me name
tls-version-min 1.2

Copy the whole contents of hide.me CA cert file into "CA Cert"

Click "Save" at the bottom

3
Go to "Administration" > "Commands"
Copy the following text into "Commands" field.
Please change USERNAME and PASSWORD to your hide.me credentials.
* You only need to set up following two lines if you don't have "User Pass Authentication" in your OpenVPN settings.

echo USERNAME > /tmp/credentials.txt
echo PASSWORD >> /tmp/credentials.txt

Click on "Save Startup"
Now copy the following text into "Commands" field:

iptables -I FORWARD -i br0 -o tun1 -j ACCEPT
iptables -I FORWARD -i tun1 -o br0 -j ACCEPT
iptables -I INPUT -i tun1 -j REJECT
iptables -t nat -A POSTROUTING -o tun1 -j MASQUERADE

Click on "Save firewall".

**Comment by Zomboided** [comment]
This isn't an ovpn, this is an approximation of one so maybe there are
things I'm not seeing here, but this looks roughly the same as the ovpn
files that were shared with me last month from this provider.  The only
difference is the regen-sec parameter which would just trigger a
renegotiation every 900 seconds, which is not what you're seeing.

What's more likely here is that you're in the realm of either the last set
of commands not modifying the IP tables (which defines your routing), or
something not getting refreshed.  You're free to go read here
https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#dns-issues
and/or understand the use of the up/down scripts to add the iptables
commands.

I've very little clue why this seems to be an issue for some people and not
others - it appears to be more prevalent with OSMC over LibreELEC, but I
have personally never experienced it across trying to use ~20 VPN providers
(with LE).

Given that you're showing as connecting, and the errors in the log appear
to be around routing, and the ovpn files supplied by the VPN provider being
similar to what I'm using, I don't think there's anything more I can add.
If all else fails, get a real ovpn from your provider and use the openvpn
command directly on your Kodi box (this is all VPN Mgr does) to see if that
yields the same behaviour.  Once you've established a connection that way,
you'll be able to use the Kodi GUI to see if the same thing happens.

**Comment by bierbaron2** [comment]
Excuse me, I have now attached the ovpn files. I don't know why I am failing to connect, I already suspected IPv6, but I had no success after after I have tried out some things.
[amsterdam.hideservers.net.zip](https://github.com/Zomboided/service.vpn.manager/files/5451851/amsterdam.hideservers.net.zip)
[amsterdam.hideservers.net (legacy).zip](https://github.com/Zomboided/service.vpn.manager/files/5451852/amsterdam.hideservers.net.legacy.zip)

**Comment by Zomboided** [comment]
Thanks, confirming that the addon is using exactly the same as what they're
generating.

And you are connecting.  In the log it says Initialization Sequence
Complete.  What's failing are the routing commands, or the DNS is not being
refreshed.  The routing commands can fail because you've not giving Kodi
the right level of authority to update them.  The DNS issues are documented
on the wiki and in multiple issues.  I'd start with the authority issues -
look at the back issues, I'm 90% sure someone posted something about this.
