### ISSUE TITLE
Blockind dns failed

### ISSUE THREAD

**Issue by gree303** [Zomboided/service.vpn.manager#308]
hi zomboided, 
thanks for providing this neat extension.
I'm having issues to connect to any vpn location, no matter which vpn configs. 

the actual openVPN does work within windows. 
the problem happens back in kodi. No matter what I tried; it's always the same error log. 

Link to Log: [https://ibb.co/SB1zm7t](url)

any clue what i'm missing out?

many thanks.

**Comment by Zomboided** [comment]
You're not running Kodi as administrator.
If you don't do this, then when it launches openvpn then openvpn doesn't
have the ability to go alter ip tables

**Comment by gree303** [comment]
oh man, thank you! can't tell how much pain i had because of this.
