### ISSUE TITLE
BBC iPlayer won't work, even when connected to VPN

### ISSUE THREAD

**Issue by gree303** [Zomboided/service.vpn.manager#309]
I'm having some issues getting iPlayer Addon to work with VPN Manager.
When starting the iPlayer, VPN is setting up a connection, for example London. This works fine.
But when I try using iPlayer app, it just tells me I'm not in UK.

Any idea if this is related to some VPN Manager settings?

Thank you.

**Comment by Zomboided** [comment]
No, this is because your VPN is being blocked.  This is a common problem
across a bunch of different geo locked services.

**Comment by gree303** [comment]
thank you. what a bummer...
