### ISSUE TITLE
Need commands "Killall and pidof" for install a VPN (Cyberghost or other)

### ISSUE THREAD

**Issue by nelsius** [Zomboided/service.vpn.manager#311]
Hello,

I installed the openvpn addons on my Pi4 under Libreelec

When installing VPN (in this case Cyberghost, but also necessary with other VPNs), after filling in the arguments, I get a message from "VPN Manager for Open VPN"
"This add-on uses the openvpn, killall and pidof commands to make and manage the VPN connections You will nedd to install these ....."
I haven't found an add-on containing these commands, nor the psmisc package that seems to contain them.
The command line Llibreelec doesn't allow to enter a command like "sudo apt-get l ......".
How do I install these commands?
thank you for your help

**Comment by Zomboided** [comment]
LE already has them, I'm not sure why you're seeing that message

**Comment by nelsius** [comment]
I have searched a lot on the web, this problem is often cited but without a stated solution. If I understand you well these commands "killall and pidof" are already integrated in libreelec. I am in version LibreElec (official):9.2.6 kernel linux 4.19.127 Kodi leia18.9

**Comment by peno64** [comment]
I have VPN Manager running on a PI4 with LibreElec and have no issues.

**Comment by peno64** [comment]
Both commands are under /usr/bin

**Comment by peno64** [comment]
also openvpn is under /usr/bin

**Comment by Zomboided** [comment]
I don't understand why he's seeing the message.  Uninstall, reinstall.
Then turn on settings/debug in the VPN Mgr setting GUI (do not turn on LE
general debug) and then share the log via pastebin.

**Comment by nelsius** [comment]
thank you for your answers, I'll review this tomorrow and keep you posted.

**Comment by nelsius** [comment]
by typing "which kill killall pidof" I actually have these 3 commands under /usr/bin
So why this message from VPN Manager for OpenVPN?
I continue my research and come back to you afterwards.

**Comment by peno64** [comment]
According to me, you don't see this message of missing commands because they are missing, but because the setup of your vpn was not  successful.

**Comment by Zomboided** [comment]
Get a log...........

**Comment by nelsius** [comment]
I reinstalled VPN Manager for OpenVPN, and Zomboided Tools. Now it crashes at the end of the CyberGhost installation. The log shows
 "Cannot load private key file /storage/.kodi/userdata/addon_data/service.vpn.manager/CyberGhost/user.key"
then 
"Error:private key password verification failed"

Since he can't find the file it's normal that he can't check the key. But the file is present at the given address?! 
I put 2 pictures, I hope you can see them.
Thank you

![image](https://user-images.githubusercontent.com/74980080/100267462-c0e5aa80-2f53-11eb-86cd-0ccd45d27467.png)
![image](https://user-images.githubusercontent.com/74980080/100272062-cabedc00-2f5a-11eb-9463-d8a760aee1a3.png)

**Comment by Zomboided** [comment]
Go to the trouble shooting page on the wiki and understand how to get a
log, with debug turned on.  This is nowhere close to being a full log.
I'm not spending time guessing at your problem from these descriptions.

**Comment by nelsius** [comment]
I did not know this kodi log. I generated the log (see attached file), on line 66976 you can see the message mentioned above. 
Line66976: 2020-11-30 19:43:37.704 T:2880512880 NOTICE: My Nov 30 19:43:34 2020 Cannot load private key file /storage/.kodi/userdata/addon_data/service.vpn.manager/CyberGhost/user.key
However after checking the user.key file exists there !?!
[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/5618949/kodi.log)

**Comment by Zomboided** [comment]
The log says this : OpenSSL: error:0B080074:x509 certificate
routines:X509_check_private_key:key values mismatch
The message on the screen tells you that it's an authentication error.
You're giving it the wrong key/cert.  It's got nothing to do with whether
the key exists or not.
I don't know how your VPN provider works, whether you get a separate
key/cert or whether you download an ovpn with them all in.  Either way,
delete the key and cert, download the right things from your provider and
try again using the wizard.  If it still doesn't work then you'll need to
trouble shoot following the wiki instructions and then engage with your
provider support team.  Right now I can see nothing wrong with the add-on.

**Comment by nelsius** [comment]
Thanks, I'll check with the provider

**Comment by Vidrep** [comment]
Here’s your answer:
%sysadm ALL=(ALL) NOPASSWD: ALL

**Comment by nelsius** [comment]
J'ai envoyé le kodi.log au support Cyberghost mais je n'ai pas encore de réponse. Concernant votre réponse si-dessus (Here’s your answer:
%sysadm ALL=(ALL) NOPASSWD: ALL)
je ne comprend pas ce que vous voulez m'indiquer !
Cordiamement
I have sent the kodi.log to Cyberghost support but I still don't get an answer. Here's your answer:
%sysadm ALL=(ALL) NOPASSWD: ALL)
I don't understand what you want to tell me!
Yours sincerely

**Comment by Zomboided** [comment]
Doesn’t look like an addon issue, closing
