### ISSUE TITLE
Issues using VPN Manager with Kodii on Lubuntu 20.04

### ISSUE THREAD

**Issue by vik748** [Zomboided/service.vpn.manager#312]
I am trying to setup VPN Manager with IPVanish for Kodi on Lubuntu 20.04.  I understand that I need to setup killall, pidof and openvpn to run without requiring sudo. 
I did this by creating a file in `/etc/sudoers.d/` with `ALL ALL=NOPASSWD: /usr/bin/killall,/bin/pidof,/usr/sbin/openvpn`
However even with this, I am unable to run `openvpn --config xxx.ovpn` without sudo.
I have looked all over the internet for ideas on how to make openvpn work without sudo, but I haven't found a clean solution.

Could you please advise what would be the best way to make this work on an Ubuntu based system.
Thanks in advance.

**Comment by Zomboided** [comment]
Dunno, I use LibreELEC which does need sudo and Windows as a dev box.  There has been some other issues with people running on full Linux systems, maybe ask how they solved by asking in those issues?
