### ISSUE TITLE
PrivateVPN

### ISSUE THREAD

**Issue by betatester3016** [Zomboided/service.vpn.manager#314]
No issue.

This to let you know service.vpn.manager 6.93 works with PrivateVPN under CoreELEC 19.0-Matrix Beta 2 and to thank you for your continuous efforts to maintain this addon.

**Comment by Zomboided** [comment]
Great, thank you for letting me know.

**Comment by betatester3016** [comment]
I have 1100+ days remaining on my PrivateVPN subscription. If I encounter
any issues I can let you know.
Also, the matrix pre release works just fine with CoreELEC Matrix Beta 2.
