### ISSUE TITLE
ExpressVPN connection issues 

### ISSUE THREAD

**Issue by Rorqualx** [Zomboided/service.vpn.manager#316]
Hi Zomboided,

Thanks for creating this add-on! I had been using it no problem with IPvanish and recently switched over to ExpressVPN. At first I was getting a ton of errors around the certificates and keys and using an OVPN file instead also errored out before making a connection. Eventually I figured out what the certificates and keys needed to look like and I think I have all the correct certificates and keys but I'm still running into errors in connecting right at the last moment. I’m using ExpressVPN, on a raspberry pi 3 model b v1.2 running OSMC, VPN Manager for OpenVPN 6.3.7 

Any idea what's going on?

Tue Dec 29 20:35:53 2020 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Tue Dec 29 20:35:53 2020 WARNING: file '/home/osmc/.kodi/userdata/addon_data/service.vpn.manager/ExpressVPN/user.key' is group or others accessible
Tue Dec 29 20:35:53 2020 WARNING: file '/home/osmc/.kodi/addons/service.vpn.manager/ExpressVPN/ta.key' is group or others accessible
Tue Dec 29 20:35:53 2020 WARNING: file '/home/osmc/.kodi/addons/service.vpn.manager/ExpressVPN/pass.txt' is group or others accessible
Tue Dec 29 20:35:53 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Tue Dec 29 20:35:53 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Tue Dec 29 20:35:53 2020 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Failed to query password: Timer expired

**Comment by Zomboided** [comment]
I can't guess at what you're doing from this tiny fragment of the log.  See
the trouble shooting page on the wiki and get a debug log.  Do not get a
full Kodi debug log.

**Comment by Rorqualx** [comment]
I didn't see a OVPN debug log, just the kodi log it was to long to save but I think this is the relevant part. Let me know if I got it wrong.

https://paste.kodi.tv/obotemetiy.kodi

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#gathering-logs

**Comment by Zomboided** [comment]
No log, no problem...
