### ISSUE TITLE
TypeError: attribute of type 'NoneType' is not callable

### ISSUE THREAD

**Issue by bepsx** [Zomboided/service.vpn.manager#317]
It happens when I try to open the Kodi log file from the Add-On settings Advanced panel. Tested on LibreElec latest installation.

2021-01-02 13:18:40.400 T:1454351232 WARNING: CPythonInvoker(9): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
2021-01-02 13:18:40.663 T:1454351232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: attribute of type 'NoneType' is not callable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.vpn.manager/logpopup.py", line 35, in <module>
                                                popupOpenVPNLog("")
                                              File "/storage/.kodi/addons/service.vpn.manager/libs/logbox.py", line 87, in popupOpenVPNLog
                                                log_file = open(getVPNLogFilePath(), 'r', errors='backslashreplace')
                                            TypeError: attribute of type 'NoneType' is not callable
                                            -->End of Python script error report<--

**Comment by Zomboided** [comment]
I have no clue what levels of code you’re running....proper log please

**Comment by peno64** [comment]
Do you mean with  latest installation kodi 19? Then you also need the latest release 6.9.3
https://github.com/Zomboided/service.vpn.manager/releases/tag/6.9.3

**Comment by bepsx** [comment]
Hi, Thanks for the feedback. I was using the 6.4.2 on Kodi 18.9 (LibreElec 9.2.6).That version was suggested to me by VPN provider. Inviato da Posta per Windows 10 Da: peno64Inviato: sabato 2 gennaio 2021 14:32A: Zomboided/service.vpn.managerCc: bepsx; AuthorOggetto: Re: [Zomboided/service.vpn.manager] TypeError: attribute of type 'NoneType' is not callable (#317) Do you mean with latest installation kodi 19? Then you also need the latest release 6.9.3https://github.com/Zomboided/service.vpn.manager/releases/tag/6.9.3—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Zomboided** [comment]
You should stick to 6.3.7 in the repo.  6.4.2 mirrors the changes needed
for Python 3 for Kodi 19.  This bug has been fixed there...I don't think
I've released 6.4.3 because I'm not happy with any 6.4.x releases on Kodi 18
