### ISSUE TITLE
update-resolv-conf: no such file or directory error

### ISSUE THREAD

**Issue by mentaluproar** [Zomboided/service.vpn.manager#318]
I get the error in the title when I try to set up the VPN manager with protonVPN.  I tried a fresh install of jcoreelec and it didn't help.  ideas?

--up script fails

**Comment by Zomboided** [comment]
The ovpn file you're ingesting has up and maybe down parameters which are
calling for a script which doesn't exist.
Without the referenced script, the DNS may not get set up correctly and
you'll not be able to resolve domain names.
This is touched on here
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#potential-dns-fix-linux-only
Either remove the up parameter or add the script.  Either thing is not an
issue with the add-on.
