### ISSUE TITLE
Updated Config Files for LimeVPN

### ISSUE THREAD

**Issue by JonBenNoah** [Zomboided/service.vpn.manager#319]
Hello Zomboided,

As always, thank you for this excellent software.

I attach new configuration files for LimeVPN. I have been using them with UserDefined, but I would be grateful if you could update the database.

The same files can be dowloaded directly from LimeVPN, by clicking the link "openvpn config files" at the bottom of their home page. No login needed.

I'll be happy to test that it works. 

With Best Wishes,

Jon
[OpenVPN-Config.zip](https://github.com/Zomboided/service.vpn.manager/files/5792886/OpenVPN-Config.zip)

**Comment by Zomboided** [comment]
Done...thanks for supplying the config
