### ISSUE TITLE
IPVanish security changes to Config files from 10/01/17

### ISSUE THREAD

**Issue by Trilton** [Zomboided/service.vpn.manager#32]
Hi,

Could you advise if the manager will be updated with the new config files from 10/01/17 since IPVanish are making mandatory security improvements to the files which will void any connections using the current files.

If not immediate, is there a guide on how to update these manually?

Many thanks for your continued support and providing this wonderful solution.

**Comment by Zomboided** [comment]
Fixed in 2.4.1 using the files they have available today.  You can install directly over what you're currently using and it should just work if you don't wnat to wait for the random repository update

**Comment by danmlee** [comment]
I'm getting a cert error trying to connect to IPVanish via 2.4.1. Any ideas? Let me know if you need a more detailed error message.

**Comment by Zomboided** [comment]
Well I can't test this because I don't have an account.  You're telling me that they're changing something tomorrow, so maybe it'll work after they've done this - I'm using the files they supply.  If it doesn't work tomorrow, then i'll just revert the change and not alter anything until someone tells me it has actually stopped working.

**Comment by Trilton** [comment]
That was was another user reporting the error not the OP. I will have a go
tomorrow once the IPVanish service has altered from their side then we know
for sure. Cheers

**Comment by Zomboided** [comment]
Good point, I'd not noticed that, sorry...I've pulled the release for now, but I'll put it up again if it works tomorrow.

**Comment by Trilton** [comment]
I can connect stable using 2.4.0 with a confirmed IPVanish - London 01 IP address. Not sure how else to confirm the current configs are correct? I guess nothing to fix at this stage? Would be good to know if @danmlee can too.

**Comment by danmlee** [comment]
I tried again on 2.4.1 but got the same error. I uninstalled and reverted to 2.4.0 but now I'm getting a certificate expired error.

**Comment by Zomboided** [comment]
Open the 2.4.1 zip, navigate to the IPVanish directory, extract the ca.crt and copy that into the /storage/.kodi/addons/service.vpn.manager/IPVanish directory. Then try and connect.

If you're not running LibreELEC, you'll need to find the equivalent directory for the path before /addons. This is the new cert they're using. If it works I'll put that out as an update

**Comment by danmlee** [comment]
Yep, that worked, I'm up and running again. Thanks again for your help and ongoing support.

**Comment by Zomboided** [comment]
Thanks, I'll put that out as 2.4.1.

**Comment by Trilton** [comment]
Interesting how i was able to connect after the updates using 2.4.0 today, does the system cache?

**Comment by Zomboided** [comment]
The addon only has the cert in one place, so no.  Maybe there's some caching elsewhere.
When I was testing yesterday I got the same auth failure for the user and password for both certs.
When I used the new ovpn, it didn't recognise the cert (danmlee's problem).  It's weird tho as I'm just using the ovpns that they're supplying....

**Comment by Trilton** [comment]
Indeed, well it made me nervous that i was able to connect after 'D-Day' so messed around again and got the auth failure with 2.4.0 finally, so in weird way i was happy...
_VERIFY ERROR: depth=1, error=certificate has expired_

I've overridden with the cert.ca from 2.4.1 dump / direct from IPVanish and connected again fine via 2.4.0, now just a case of waiting the repro to propagate to fully update the client.

Thanks
