### ISSUE TITLE
Issue setting up User Defined VPN connection

### ISSUE THREAD

**Issue by WizardKnight** [Zomboided/service.vpn.manager#320]
Hello.
I am having an issue connecting my device running CoreElec (branched from liberelec with other users reporting that Zomboided works) using Zomboided to my OpenVPN server.
I am running the latest stable version of CoreElec and Zomboided as of 1/13/21.

I have OpenVPN Server running on my router (FreshTomato firmware). I am able to connect to it from both inside and outside of my home network using the same key/ovpn files on my laptop and phone for testing (not at the same time obviously). So I think the key/ovpn files are fine.

I have tried using the wizard and manually adding my VPN. 
The error log at the time of failure, from Zomboided, shows a read only error for the client.key file. 
```
WARNING: file ‘/storage/.kodi/addons/service.vpn.manager/UserDefined/client.key’ is group or others accessible
NOTICE: Options error: --status fails with ‘status’: Read-only file system (errno=30)
NOTICE: Options error: Please correct these errors.
```
I tried chmoding the client.key file to 777 to force it to be read/write-able, but I was still unable to connect.

Here are my logs. If it doesn't have what you need, please let me know. I will try to get it for you.
http://ix.io/2LUt

Thank you.

**Comment by Zomboided** [comment]
2021-01-13 07:25:00.163 T:3802108800  NOTICE: Wed Jan 13 07:23:38 2021
WARNING: file '/storage/.kodi/addons/service.vpn.manager/UserDefined/client.key'
is group or others accessible
2021-01-13 07:25:00.163 T:3802108800  NOTICE: Options error: --status
fails with 'status': Read-only file system (errno=30)
2021-01-13 07:25:00.163 T:3802108800  NOTICE: Options error: Please
correct these errors.

You added "status status" to your ovpn config file.  I don't know what it
does or what it requires, let alone why it's causing this.  This is for
your to solve, I don't have the energy to learn openvpn parameters for
everyone.

**Comment by Zomboided** [comment]
Good luck solving this, not a VPN Mgr issue

**Comment by WizardKnight** [comment]
The ovpn file was generated by the router, and it works with both my windows laptop and my android phone so I don't know why it wouldn't work with kodi.

I removed the status status line from the ovpn file, and I was able to connect.
