### ISSUE TITLE
cannot get cyberghost vpn working

### ISSUE THREAD

**Issue by mrpg99** [Zomboided/service.vpn.manager#324]
Dear Sir/Madam,

I can connect to cyberghost using cli using my .ovpn file, and username and password provided by cyberghost when i added a device on their site.

when i try and setup this using zomboided

i provided the files downloaded from cyberghost .key .ovpn & .crt files

typed my username and password in (pasted to make sure i do not make any spelling mistakes)

when i select : First VPN connection
i choose sweden as the country (which i also chose when i added my device on the cyberghost page)
i then get "Error connecting to VPN authentication failed, check your user name and password or crt and key file)

i get this in /home/myusername/.kodi/temp/openvpn.log 
Sun Feb 14 14:10:56 2021 WARNING: file '/home/mrpg/.kodi/userdata/addon_data/service.vpn.manager/CyberGhost/user.key' is group or others accessible
Sun Feb 14 14:10:56 2021 WARNING: file '/home/mrpg/.kodi/addons/service.vpn.manager/CyberGhost/pass.txt' is group or others accessible
Sun Feb 14 14:10:56 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Sun Feb 14 14:10:56 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Sun Feb 14 14:10:56 2021 OpenSSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
Sun Feb 14 14:10:56 2021 Cannot load private key file /home/mrpg/.kodi/userdata/addon_data/service.vpn.manager/CyberGhost/user.key
Sun Feb 14 14:10:56 2021 Error: private key password verification failed
Sun Feb 14 14:10:56 2021 Exiting due to fatal error

these two files exists in /home/mrpg/.kodi/userdata/addon_data/service.vpn.manager/CyberGhost/
user.key & user.crt

I am not sure what i am missing here? please help

Best Regards
Patric

**Comment by Zomboided** [comment]
Is the key file in a directory that has the right level of permissions?
Otherwise this looks like an issue with authentication which I cannot help
you with.

Cyberghost updated the files to make this work, you'll need to go through
their support channels.  When they say they don't know about this add-on
you can reference this pull request
https://github.com/Zomboided/service.vpn.manager.providers/pull/52 which
comes from their crack team.
