### ISSUE TITLE
Problem with LimeVPN update

### ISSUE THREAD

**Issue by JonBenNoah** [Zomboided/service.vpn.manager#325]
Thank you for updating with the LimeVPN configuration files a few weeks ago.
Unfortunately none of the servers which I tried connected. I got a time-out error message for all I tried. 

I noticed from the VPN log that the attempted connections were to port 1195, while the LimeVPN config files specify port 1194. Is this the problem?
I tried editing the LOCATIONS.txt file, replacing 1195 with 1194, but this didn't resolve the issue.

When use these config files with "User Defined", the wizard succesfully converts the files, so the config files are OK.

Please let me know what I need to do to help you debug the problem.

**Comment by Zomboided** [comment]
You're right.  Fixed.

**Comment by JonBenNoah** [comment]
Works now. Thanks for the very quick response.
