### ISSUE TITLE
Allow VPN configuration reload on command line

### ISSUE THREAD

**Issue by mhhoeper** [Zomboided/service.vpn.manager#327]
Having KODI boxes at distant places makes it necessary to update vpn settings and reload them via command line. Currently, this is only possible through the GUI, e.g. VNC. But opon VPN reload the connection is not automatically reestablished and the KODI box is lost.

**Comment by peno64** [comment]
All settings are in a file settings.xml
You can edit that at command line, no?

**Comment by Zomboided** [comment]
Maybe you can make the api work via a script but I don’t know how you’d hook into a running kodi instance.  The api is documented on the wiki.   There’s no plan to grow the api to allow connections or other settings to be redefined tho, it just too much effort and way too niche even if you solved the problem of hooking into Kodi
