### ISSUE TITLE
expressvpn geo-unlocking not working

### ISSUE THREAD

**Issue by mrpg99** [Zomboided/service.vpn.manager#329]
Dear Sir/Madam,

I can connect to all servers provided by expressvpn using zomboided.

When i start a browser and check my location/ip using whatismyipaddress.com , it correctly shows my new ip address & ip address location.

However, netflix, bbc and other services are still geoblocked.

If i use the app provided by expressvpn, the geo-unlocking works fine.

Any suggestions on how i can get this working? , i would love to be able to control this by just using kodi, and skip using ssh to control my vpn connections.

many thanks in advanced for any help!

Br
Patric

**Comment by Zomboided** [comment]
This is a question for ExpressVPN support.  You can eliminate VPN Mgr by
downloading one of their ovpn files and connecting using the command line.
I imagine you'll get the same result as you do with VPN Mgr.  You can then
ask them why their provided files don't behave in the same was as the app.
