### ISSUE TITLE
Credentials from pass.txt are not passed into openvpn

### ISSUE THREAD

**Issue by mparuzel** [Zomboided/service.vpn.manager#33]
When using a User Defined profile and an accompanying pass.txt, the credentials are not passed into OpenVPN using the `--auth-user-pass` command line option. The following command is given:

```
23:08:51 3068.979980 T:1426060192    NONE: VPN Mgr Debug: (Linux) Starting VPN with /usr/sbin/openvpn "/storage/.kodi/addons/service.vpn.manager/UserDefined/Reykjavik.ovpn" > /storage/.kodi/temp/openvpn.log &
```

OpenVPN requires the credentials and eventually errors out. A work around is to manually add this to your ovpn file:
```
auth-user-pass /path/to/UserDefined/pass.txt
```

My ovpn files all had `auth-user-pass` in them, but with no path. That's how I got them from the VPN provider. If the code checks for this parameter, it should also checks that a path is given.

**Comment by Zomboided** [comment]
Yes, that's how user defined works. 

Prior to 2.4.0 it was up to you to make sure all the paths were good or tell the add on for keys/certs and user/passwords that you wanted to enter them via the GUI.

In 2.4.0 on, if you use the import wizard and you supply a file (pass.txt in this case) it'll work out that it needs to update the tag with the full path.

If you've used the import wizard, attach the ovpn you're using, blanking any keys then I'll look at why it didn't do this
