### ISSUE TITLE
Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:11: dhcp-renew (2.4.7)

### ISSUE THREAD

**Issue by rafhtl** [Zomboided/service.vpn.manager#331]
I have this error when using hide.me
Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:11: dhcp-renew (2.4.7)

Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:12: dhcp-release (2.4.7)
2021-04-03 17:40:51.446 T:6992     INFO <general>: Sat Apr  3 17:39:35 2021 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:13: register-dns (2.4.7)
2021-04-03 17:40:51.446 T:6992     INFO <general>: Sat Apr  3 17:39:35 2021 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:14: block-outside-dns (2.4.7)
2021-04-03 17:40:51.446 T:6992     INFO <general>: Sat Apr  3 17:39:35 2021 GDG6: NLMSG_ERROR: error Operation not supported

can you help me please?

**Comment by Zomboided** [comment]
I need a current ovpn file for hide.me here
https://hide.me/en/knowledgebase/where-can-i-download-openvpn-configuration-files/

**Comment by rafhtl** [comment]
Is this ok?
thank you



Il giorno sab 3 apr 2021 alle ore 18:53 Zomboided ***@***.***>
ha scritto:

> I need a current ovpn file for hide.me here
>
> https://hide.me/en/knowledgebase/where-can-i-download-openvpn-configuration-files/
>

**Comment by Zomboided** [comment]
Can't see a file?

**Comment by rafhtl** [comment]
Sorry
was a zip
now do you have it?
thank you




Il giorno sab 3 apr 2021 alle ore 19:45 Zomboided ***@***.***>
ha scritto:

**Comment by Zomboided** [comment]
no, you might need to paste in the ovpn or open the ovpn and paste the text in directly

**Comment by rafhtl** [comment]
client
dev tun
proto udp
remote de.hideservers.net 3000
cipher AES-256-CBC
auth SHA256
resolv-retry infinite
nobind
persist-key
persist-tun
mute-replay-warnings
verb 3
auth-user-pass userpass.txt
reneg-sec 900
remote-cert-tls server
verify-x509-name "*.hide.me" name
tls-version-min 1.2

<ca>
-----BEGIN CERTIFICATE-----
MIIKJDCCBgygAwIBAgIQVc9ekKx5ZIkHcGchmaaVEzANBgkqhkiG9w0BAQ0FADCB
kTELMAkGA1UEBhMCTVkxHDAaBgNVBAgME1dpbGF5YWggUGVyc2VrdXR1YW4xDzAN
BgNVBAcMBkxhYnVhbjEZMBcGA1UECgwQZVZlbnR1cmUgTGltaXRlZDEeMBwGA1UE
CwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRgwFgYDVQQDDA9IaWRlLk1lIFJvb3Qg
Q0EwHhcNMTYwMTE3MjExMDI0WhcNNDYwMTA5MjExMDI0WjCBkTELMAkGA1UEBhMC
TVkxHDAaBgNVBAgME1dpbGF5YWggUGVyc2VrdXR1YW4xDzANBgNVBAcMBkxhYnVh
bjEZMBcGA1UECgwQZVZlbnR1cmUgTGltaXRlZDEeMBwGA1UECwwVQ2VydGlmaWNh
dGUgQXV0aG9yaXR5MRgwFgYDVQQDDA9IaWRlLk1lIFJvb3QgQ0EwggQiMA0GCSqG
SIb3DQEBAQUAA4IEDwAwggQKAoIEAQDX8zVTP6FQ4gJ+4e06bxvxifNHK8ht0RZn
zCNrrwkekpB4ojXDghNfS38oK80RfygC8LXN7SnLv+0xw5dRZ3QVIZJnd/DtX2EF
ZVxMyccJkLj8IEZv4Yx7zPnKI9EcQwo64O7npz28JZAGwexmK1W7ohm9VaAAtUPY
6Ej7k/wsJi2d5BeHzYRrfJX3nEft8hbotwsFLPsngDciS3yE2B5zH/PJOZ5uzr/5
djAbeFktfHR6ywbxE2CYjz2pVUfqvzjzwNj5BJPp3K5iTL/oL1xrAkQ5xSPtHbP0
ZCMmR//PC73cqkI6bAw8YAjvq0CG7wSC3rCfzgz3RGGPHMVUmB+GGu1KZoGisexm
9Y3ovmgubM+eE23aMBObf6tcRp1hSv7+EenlqAbyqQ5JqltWgsjEcV6THRKFmlSS
CP84kZK+nLnoto6MEG8sK9d02+iYWPQbVQ9X7O6pMHgVj7vnOLuW6i+hKT/pcsnU
8yhu2495Q07NDAAeX12dMbHhfLAs+DMtxjkj9SxejCS3Gi/XxON0E1NVVNEcl4yu
TODIJVfh/+uDdUn6v8tP7XmIFlKlfyQzfxND/VlRAep1Tt4i04KAhW0SG5/qaXoP
YROoP7eA0igKI5PxGbUZw/ym0i+1iXHR5XqfavZRM6gpOlDH2D9Mo64JfJTWT8J0
AQ9apVXQZlC9raY5fulvX3TqZ5NDbm4z/hOawDFOmWWjOe2guTj+aMyDS13mpppz
JF5h9JPlvvyb1Z0cjWv5zkW00pcO5qrk2l0kbL4kSoYia+URdpi/pbF30W27JwhQ
oQqjdEcvr7qSYNkpnGSO57qZKS0Rjsnbgk2c8X1gHWqhECCoExBxT55bSKBPvrAw
1jxdct9ZTROcU0Cz39jYT9stYEaozXhzHJmMZReunh1G2sWDqYQST33ljIcqtsDI
DYu6KZorc3jioTHWnd8d/iCwz+vQcnNlyBIqqB9L0i07iQcTUGJ6lcm144JkfTEP
2xY2mFuu14KXq9tI90PzxtodBhu7DodBTtARtwRwJ7O5goME8T29UTDQbjIvZegf
eK3pzlPxdv7X+6jVl4a7Mx8S4FNAnwPa2Dz/y2uEOozRzMSmpjZb7qiVXipoe7aK
QB4oc2kK2oEfWfnF/HcFf3QZSe2fCQKp3DOGk6n9fpPFbR7PFu1Ng16HpoA6l+F3
Pamo4O6v0AxvDavj804dfyykN66Er3bfFVJu3wF/s7lrqjSQa+uGiIQ+TYehCBJY
jzQsFtuKU3/GE4L8xlfgnSUASWkmOVEDwgPon9DUbcLR2fIM9O45Xkhmbq/2YPVw
BlNCu3ScU3Y6lJ3QRNanOrfMIg1l3DZ/jeZmMDlINJvA7arx4XD5AgMBAAGjdjB0
MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMB0GA1UdDgQWBBTqzyLU
H5gO8ud/EfET7E92x/rJuTAfBgNVHSMEGDAWgBTqzyLUH5gO8ud/EfET7E92x/rJ
uTARBglghkgBhvhCAQEEBAMCAAcwDQYJKoZIhvcNAQENBQADggQBAEs7gwuhUOxo
rVCWcG0lKLWbgj0w/KqTwgAwyIN8Muth3SLF750iQ+U6AWDKY2sBRibYRmM5UUgq
CVL2XShwN7SkuAnkitYU7NDEFr/gQsoEObMo1s7cNtelVcOTKYBqvIHsSw9SX7mr
EoDVWCOW5Gx8/z6luexo6P5iSVvr4xbechQ6SKxpFIrhnE5k+MRDfvRLUyCbCQMg
0zIteC1kVL6Lrfx/JiDjMpDz7zPUFh/gXuqA3FAFN/oaQkhpHroiwgMi6X1qFB7m
/y1Qctb7Tw+h8SfzapRBq1EOxqZ86bGjI35MRxbEgP9SD7fRpo86jpejKS2JXnsf
q1agSSw90H95nzX4ck6DGtKGNiDeNcDrsj98vCImsvO0X6T2eX/sx2ZRANEHcmHt
J+tcdLo+UqoCUkdvCxxnNMYgnlhGhXbfzxeKsgQz5zQDg2XA2uZCNtgg6lQLgvmM
xD+wPVY+ewGnJuz9reSxR9SyMxmpkAA7zqxpdG8HKRKupFxpnoyt17PAilsawMD/
vtCTw1CNbo56oA635MZiNzb/5GO8vp0VDsS5nErL/DP/MEHmt/qZqLCoiStjTE1j
QQsggyl/EH8NbIYQDAQweUMSmvdVBa1qwXSnbSd9xX3AE7RE34gZ1abS1zhXjTkY
C16mj3nkCzCbax3eC5BKctxd4GB7JcpctAzvhWAfKAHAFsc8DLAUM+/S1+UWwOP1
Lq5Z/+ZdXBiMiXbzyyAPILOp89hoF1c4BTmAmpFNCPQTa/kwC4pdSJCXRljfpMBE
pkaKNteAJQZkWC2ACi2tuD6z34uS/yputnLMahyJvTiVa35NvG7yVc/h3/GDanHK
f9h2CSlKc6FrtJNtysXWaVioATSjHLe0AXFLMuFBwlhyivrJaHjVneUOiG2EERVv
TsaQT04Kqschl9tiqvlsXSrqKi2dLvDWEkG3F+nmNCUE4E6VrHCTk3X9Gs/d2AbP
MfcxPbrIt1TLRN+OFG2ivpJtWyHROqWXQG85GVwpplaa4sg80OrX9bu4MYlg5MFk
4RHBAPLe5eJ8YobwPOAD4vnl2yqpgxbEBAiPlX/mXsfbBYLXHsDS/EMPecJ3aqZ3
Wv7y9IeWz9x6h4/AGM2pSbL+FHy4i55o4486CTKuB/6PEnlLAiVfPDkhDpJo0/ta
n+p25b79tbI2iIoa4VqhkFAXpCdujNc/j7f+5wT+PsandEi3vckAvvZjhmTdreev
+nB/J2uzyFLr+6MUrYkPlOEUOnNImqDeXE/ocPFsTHiigV1I+1CUUgLr2MGuFTFm
ZpQyQ6V9oqNU6av+hsD11GYpV8wi4QqWjeBOQayXJ7vcwqE3igyoBI2vMrpwfLlJ
K127pRfgZn0=
-----END CERTIFICATE-----
</ca>

<tls-crypt>
-----BEGIN OpenVPN Static key V1-----
8d25d82e75abbcdd73fb17b2ba5d1af2
2d0e026ac8608ec8e51ecb0b3b1b5dba
8ac1f6e556e4b4e3545e979dd26e2d9d
5bc28c1d75b4e37531aabf5da3cba671
1f8998eb66aa290daab6122bdfcb1aa3
b9b428e722ea6e7edd9b878a5161c555
14e6233d18b5cc34e859ecb5852b34ed
6e539d64676edf9ad79470795ae73184
05d93554de1063aec1df6420709c2dcc
79511fa9c5e82de09d560f7d92001ea2
75e4b3e9b6ce19687968b4813d6a9d61
a48311658de88d651edb4eab447d73f6
b209d144a3343a2c992b09c7501cad77
cdf5c6b3be5f9919854bb10182c86794
9df929173b8e98aeea9ffe277eddd7f7
936232e1e44c9feb7a3a2753ed05c90b
-----END OpenVPN Static key V1-----
</tls-crypt>


Raffaello Maria Del Re
-----------------------------------------
www.softesolution.com
www.htlapp.net


Il giorno sab 3 apr 2021 alle ore 19:48 Zomboided ***@***.***>
ha scritto:

**Comment by Zomboided** [comment]
dhcp-renew and dhcp-release look current in 2.4, and I think you're using 2.4.7 right?  If not, be at 2.4.7 or later.
And anyway they're pushed form your provider so I'm not sure why there appears to be an error there.

The ovpn you shared is consistent with the version I'm using so if you're using the built in definitions, I don't think I'm doing anything your provider is not expecting.

And finally, the register-dns and block-outside-dns are Windows only.  If you're on Linux, these should just be ignored with that message.  If you're on Windows, you'll need to run Kodi in admin mode, but I don't see the usual set of messages associated with it being run in user mode.

The "NLMSG_ERROR: error Operation not supported" message is related to ipv6.  I'm not familiar with this so can't really help there.

Not terribly helpful.  You could try using the ovpn you've provided with the command line to see if you can get it to connect directly.  If you can, I'd be happy to look at a log from that.

**Comment by rafhtl** [comment]
Thank you
I am using kodi in linux
Matrix
so your latest version6.9.3
"dhcp-renew and dhcp-release look current in 2.4, and I think you're using 2.4.7 right? If not, be at 2.4.7 or later."

how do I check this?
I am on debian

I am going to try  using the ovpn you've provided with the command line
have you any link that I can copy commands from ssh?
thank you for your help

**Comment by rafhtl** [comment]
this is what the actual log says after those statements
maybe this can be of use?

Sat Apr  3 19:26:10 2021 TUN/TAP device tun0 opened
2021-04-03 19:27:11.794 T:13850    INFO <general>: Sat Apr  3 19:26:10 2021 /sbin/ip link set dev tun0 up mtu 1500
2021-04-03 19:27:11.794 T:13850    INFO <general>: Sat Apr  3 19:26:10 2021 /sbin/ip addr add dev tun0 10.129.202.238/23 broadcast 10.129.203.255
2021-04-03 19:27:11.794 T:13850    INFO <general>: Sat Apr  3 19:26:10 2021 /sbin/ip -6 addr add fd00:6968:6564:e5:c11e:1c62:d544:c404/64 dev tun0
2021-04-03 19:27:11.794 T:13850    INFO <general>: RTNETLINK answers: Operation not supported
2021-04-03 19:27:11.794 T:13850    INFO <general>: Sat Apr  3 19:26:10 2021 Linux ip -6 addr add failed: external program exited with error status: 2
2021-04-03 19:27:11.794 T:13850    INFO <general>: Sat Apr  3 19:26:10 2021 Exiting due to fatal error
2021-04-03 19:27:11.794 T:13850    INFO <general>: VPN Mgr : (vpnplatform.py) <<< VPN log file end
2021-04-03 19:27:13.722 T:13850   ERROR <general>: VPN Mgr : (common.py) Error connecting to VPN, something unexpected happened. Check log for more information.

**Comment by rafhtl** [comment]
Sat Apr  3 19:25:53 2021 WARNING: file '/home/xbian/.kodi/addons/service.vpn.manager/HideMe/ta.key' is group or others accessible
Sat Apr  3 19:25:53 2021 WARNING: file '/home/xbian/.kodi/addons/service.vpn.manager/HideMe/pass.txt' is group or others accessible
Sat Apr  3 19:25:53 2021 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Sat Apr  3 19:25:53 2021 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Sat Apr  3 19:25:53 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Apr  3 19:26:08 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]91.199.118.73:3000
Sat Apr  3 19:26:08 2021 UDP link local: (not bound)
Sat Apr  3 19:26:08 2021 UDP link remote: [AF_INET]91.199.118.73:3000
Sat Apr  3 19:26:08 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Apr  3 19:26:09 2021 [*.hide.me] Peer Connection Initiated with [AF_INET]91.199.118.73:3000
Sat Apr  3 19:26:10 2021 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:11: dhcp-renew (2.4.7)
Sat Apr  3 19:26:10 2021 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:12: dhcp-release (2.4.7)
Sat Apr  3 19:26:10 2021 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:13: register-dns (2.4.7)
Sat Apr  3 19:26:10 2021 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:14: block-outside-dns (2.4.7)
Sat Apr  3 19:26:10 2021 GDG6: NLMSG_ERROR: error Operation not supported

Sat Apr  3 19:26:10 2021 TUN/TAP device tun0 opened
Sat Apr  3 19:26:10 2021 /sbin/ip link set dev tun0 up mtu 1500
Sat Apr  3 19:26:10 2021 /sbin/ip addr add dev tun0 10.129.202.238/23 broadcast 10.129.203.255
Sat Apr  3 19:26:10 2021 /sbin/ip -6 addr add fd00:6968:6564:e5:c11e:1c62:d544:c404/64 dev tun0
RTNETLINK answers: Operation not supported
Sat Apr  3 19:26:10 2021 Linux ip -6 addr add failed: external program exited with error status: 2
Sat Apr  3 19:26:10 2021 Exiting due to fatal error

**Comment by Zomboided** [comment]
The log has the command being used, you can copy that to recreate this via
the CLI and adjust for your ovpn you downloaded.

See the RTNETLINK error though, that's where I'd start looking (as someone
who knows little about Linux)....eg:
https://stackoverflow.com/questions/62356581/wireguard-vpn-how-to-fix-operation-not-supported-if-it-worked-before

**Comment by rafhtl** [comment]
The RPi log shows that I have IPv6 disabled on my device. 
I enabled and its solved
thank you

ipv6
https://www.hpc.mil/program-areas/networking-overview/2013-10-03-17-24-38/ipv6-knowledge-base-ip-transport/enabling-ipv6-in-debian-and-ubuntu-linux

sudo modprobe ipv6
add ipv6 to /etc/modules

**Comment by rafhtl** [comment]
Thank you for all your work
It now works perfectly!

**Comment by rafhtl** [comment]
Can you tell me please if there is a way via another script python to
suspend VPN (no VPN Connection if there is one active)
and
activating connection 1 or 2 etc 
Is it via a ?arg=  
thank you

**Comment by Zomboided** [comment]
There’s an api you can use, that’s documented on the wiki

**Comment by rafhtl** [comment]
thank you

**Comment by rafhtl** [comment]
runscript(/storage/.kodi/addons/service.vpn.manager/api.py, Connect 1)
runscript(/storage/.kodi/addons/service.vpn.manager/api.py, Disconnect)

thank you
