### ISSUE TITLE
matrix

### ISSUE THREAD

**Issue by cliffbuck1** [Zomboided/service.vpn.manager#332]
hi

i cant get this to install in the new matrix release it is hidden,it worked great in 18 but now it wont install,i get dependency 2.7.0
 cant be satified also i tried then open vpn manager  but that says not compatible with this version

**Comment by peno64** [comment]
You must install release 6.9.3 on Matrix. See https://github.com/Zomboided/service.vpn.manager/releases

**Comment by cliffbuck1** [comment]
Thanks I had just found it before you e-mailed,but thank you for your prompt reply I was about to post solved
