### ISSUE TITLE
Update for Kodi 19 Matrix

### ISSUE THREAD

**Issue by Roebie** [Zomboided/service.vpn.manager#333]
The repository can be installed on Matrix but appears empty when trying to install service.vpn.manager from it.
The service itself (direct download) can't be installed because the Python 2 requirement is not satisfied on Matrix which works with Python 3.
Please update for Python 3.
Thanks!

**Comment by peno64** [comment]
See https://github.com/Zomboided/service.vpn.manager/releases
version  6.9.3

**Comment by peno64** [comment]
@Zomboided 
Maybe you should put this on your start page https://github.com/Zomboided/service.vpn.manager/

**Comment by Zomboided** [comment]
@peno64 Good suggestion (for those that actually try and read!).  Done.

**Comment by peno64** [comment]
@Zomboided 
You can also fix an issue about it on top such that people see it when they want to create an issue...

**Comment by Zomboided** [comment]
Ooooooh yeah, done that too.  Appreciate your help, thanks.
