### ISSUE TITLE
Connecting to private VPN (PiVPN) not possible

### ISSUE THREAD

**Issue by lafreak88** [Zomboided/service.vpn.manager#336]
Hello all,

I hope that I haven't missed an important information, but as far as a understand it should work.

Following situation:
Kodi 19 on a Windows 10 PC. Your Addon is working with eg ExpressVPN without problems.

Now I started an OpenVPN server using PiVPN on an RaspberryPi 4. The VPN software ín windows can connect without problems, but the addon gives an error. 
https://paste.kodi.tv/simabexuga.kodi

The .ovpn file doesnt require password or username. 
So i used "user defined" provider and left username and password empty. Import of the .ovpn file without errors.

So do you have any idea? 

Thanks in advance

**Comment by Zomboided** [comment]
See this https://github.com/Zomboided/service.vpn.manager/issues/60 it has
issue and solution in.
