### ISSUE TITLE
Windows - OpenVPN Connect not reachable

### ISSUE THREAD

**Issue by simi55** [Zomboided/service.vpn.manager#340]
Hi,
Tried to get the VPN Manager running under Kodi 19.0 and Windows 10 20H2. I installed the latest OpenVPN Connect client - unfortunately the default installation folder (/Program Files/OpenVPN Connect) cannot be changed. I also added a VPN connection in OpenVPN Connect which is just working fine.

I tried both ways to setup the VPN Manager as described in the wiki:

1. Added C:\Program Files\OpenVPN Connect to the path variable and was able to start OpenVPNConnect.exe from the root folder within the CLI. I selected "Use openvpn with no path" under advances options, but VPN Manager threw an error message "The OpenVPN executable isn't working." Is the VPN Manager referring to openvpnconnect.exe? There is also a ovpnconnector.exe but there is no openvpn.exe in the folder.

2. I selected the installation path c:\Program Files\OpenVPN Connect\ and got the same error message. According to the log file VPN Manager automatically added a folder \openvpn - so of course it wasn't able to find the exe under c:\Program Files\OpenVPN Connect\openvpn. As I wrote above - the installation path of the OpenVPN client cannot be changed.

Many thanks :)

**Comment by Zomboided** [comment]
https://openvpn.net/community-downloads/

You don’t need Connect.  Well done for trying to help yourself with the wiki tho, so much more than most people!

**Comment by simi55** [comment]
Life can be so easy - it is working now. Thanks a lot. Maybe you take over the more specific OpenVPN link into the wiki... :)
