### ISSUE TITLE
Windscribe NOT WORKING

### ISSUE THREAD

**Issue by BestNoob** [Zomboided/service.vpn.manager#341]
I think Windscribe changed their Servers as example Germany: deu.windscribe.com instead of de.windscribe.com
maybe only on the website but i cannot see any other reason it isnt working. Or its because of the configuration.

They have also added new configurations

https://windscribe.com/getconfig/openvpn
https://windscribe.com/features/config-generators

I dont know another VPN Service that gives you 15GB monthly traffic for free

**Comment by Zomboided** [comment]
Provide a log.  Then I'm probably going to tell you to provide ovpn files
for the broken servers.

**Comment by BestNoob** [comment]
Thats a Deal ;D ...... im sorry i thought its not such hard work to fix it .... i mean you can use files etc. from other gits
Would be awesome when we could get windscribe to work. Here the logfile
https://gist.github.com/BestNoob/9a1f01bbaeeb817cbd896f1034a975bd

**Comment by Zomboided** [comment]
Need an example ovpn file with the latest certificates.  The log is showing
that it's connecting so it's not a problem with the server, but
authentication is failing.

**Comment by BestNoob** [comment]
My test Subscribtion has ended so im FreeUser now. I have only the standard User Login to use. If this is an issue but on PC its working well ..... i also tested different locations (Garmany, Austria, USA)

Here the stuff from my Raspi 4: 
[userdata_addon_data_Windscribe.zip](https://github.com/Zomboided/service.vpn.manager/files/6741410/userdata_addon_data_Windscribe.zip)


This is the stuff i tried from you + the v6.3.7 directly from your Repository:

[repository.zomboided.plugins-1.0.0.zip](https://github.com/Zomboided/service.vpn.manager/files/6741135/repository.zomboided.plugins-1.0.0.zip)
[service.vpn.manager-6.2.3.zip](https://github.com/Zomboided/service.vpn.manager/files/6741136/service.vpn.manager-6.2.3.zip)
[service.vpn.manager-6.4.2.zip](https://github.com/Zomboided/service.vpn.manager/files/6741137/service.vpn.manager-6.4.2.zip)
[service.vpn.manager-6.9.3.zip](https://github.com/Zomboided/service.vpn.manager/files/6741138/service.vpn.manager-6.9.3.zip)

**Comment by Zomboided** [comment]
I'm not gonna change anything based on a test subscription not working because I may break real users.
If a user with a full subscription has an issue, then they can supply the latest data and I'll go look.

**Comment by Converted007** [comment]
> I'm not gonna change anything based on a test subscription not working because I may break real users.
> If a user with a full subscription has an issue, then they can supply the latest data and I'll go look.

I got an issue with the latest release candidate on kodi 19.1 matrix. And im a Pro user. Ill upload a log shortly...

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager.providers/issues/64

**Comment by Converted007** [comment]
> [Zomboided/service.vpn.manager.providers#64](https://github.com/Zomboided/service.vpn.manager.providers/issues/64)

Thanks! Working perfectly:-)
