### ISSUE TITLE
Does not work on new release of Kodi

### ISSUE THREAD

**Issue by malfroid** [Zomboided/service.vpn.manager#342]
```
Failed to install add-on from zip file. The dependency on xbmc.python 2.7.0 could not be satisfied.
```

Can you update this add-on to Python3 so it can be installed on recent versions of Kodi / LibreELEC?

**Comment by peno64** [comment]
It is. Look at the Issue on top. There is  a version for kodi 19

**Comment by peno64** [comment]
https://github.com/Zomboided/service.vpn.manager/issues/338
