### ISSUE TITLE
NordVPN Connection Issues for US (Started 9-20-2021)

### ISSUE THREAD

**Issue by dootsie5times** [Zomboided/service.vpn.manager#346]
I'm using LibreElec 9.2.8 which is Kodi 18.9 and CoreElec 9.2.8 which is also 18.9.
Yesterday, 9-20-21 I started experiencing issues with VPN NordVPN and the United States connection.
It says it connects, but VPN status gives garbage and when trying to run "SpeedTest" addon, it goes off into neverneverland.
If I use Canada, it works as expected.

**Comment by Zomboided** [comment]
Maybe the United States is broken.  Biden has a lot to answer for.  Luckily you can still rely on Trudeau.
Best of luck writing future fabulous bug reports and expecting people to take them seriously.
