### ISSUE TITLE
On Libreelec 10/kodi Matrix RaiPlay addon is bypassing it

### ISSUE THREAD

**Issue by alfredosc8** [Zomboided/service.vpn.manager#347]
I'm using Libreelec 10/kodi Matrix to run RaiPlay addon and watch Italian live TV with VPN, it's look like the plugin is going over the VPN. Apparently routing table looks good but it is connections are not going to the tunnel.
Can you take a look? I could help you if you will give me same directions because I never build an addon.
Thanks

**Comment by Zomboided** [comment]
What does it report when you connect? Does it show a different country?  It’s using an external api service to report location so if this is showing somewhere other than your real location/ip address then it’s connected.

In the UK, many VPN services are blocked by the legitimate TV providers to prevent use outside of the country. Maybe this is your issue

**Comment by alfredosc8** [comment]
it could be but using IKEV2 or Surfshark crome add-on(that uses iKeV2) it works.
The issue is on using openvpn

**Comment by Zomboided** [comment]
Maybe, but the addon only supports openvpn and that's not going to change.
If it connects and reports a different location/IP, then it's working and
the issue is outside of the addon.  I'm not sure what more you're expecting
me to do.
