### ISSUE TITLE
Can't install Open VPN 7.0 in kodi on Nvidia

### ISSUE THREAD

**Issue by Rvhalewyn** [Zomboided/service.vpn.manager#354]
I changed from Eminent to Nvidia Pro.
Installed the add-on from Zomboid rep. 
Wizard starts up.
Asks me to install certain elements through a command line. 
I'm not a programmer. 
Is there any simple guidance to make this work?

Or should I install Open VPN for Android outside the kodi app?

**Comment by Zomboided** [comment]
I don't know this hardware.  The instructions for installing onto Linux based systems are on the wiki.  It doesn't (and probably will never) work on Android.
