### ISSUE TITLE
TorGuard VPN config

### ISSUE THREAD

**Issue by garypower** [Zomboided/service.vpn.manager#358]
Good morning Zomboided,
I've been using VPNManager for ages, its a great addon. Thank you for developing.

But since I updated to 7.0 and Kodi Matrix, I've not managed to connect to some of the locations available from TorGuard. For example I can connect to UK London but not Amsterdam or Paris. Torguard have also added some new locations that are not on the vpn manager list e.g. Manchester.

Both the password and the email are correct, as i am able to connect to London successfully.

Just wondering as TorGuard is not a super popular VPN provider could some config files need updating? Happy to provide any log files you need

Thank you beforehand.

**Comment by Zomboided** [comment]
Hello, I think I've found the latest set of files.  Can you download this
zip and check out a couple of broken/new locations against their config
generator please? If the contents of the zip appears to be up to date, I'll
drag them into VPN Mgr.

https://torguard.net/downloads/OpenVPN-TCP-Linux.zip

**Comment by garypower** [comment]
Hey thanks for getting back to me.

So if I'm correct you want me to login to Torguard and download a config
file and compare to what you have. (Sorry if this is incorrect.)

I took the Sydney server, as it was first on the list. I do see some
differences. I've highlighted the settings I think need attention.

your file torguard file
client client
dev tun dev tun
proto tcp proto udp
remote au.torguardvpnaccess.com 1912 remote au.torguard.com 1912
remote 168.1.210.188 1912
resolv-retry infinite resolv-retry infinite
nobind nobind
persist-key
persist-tun
tun-mtu 1500
tun-mtu-extra 32 tun-mtu-extra 32
mssfix 1450
ca ca.crt
remote-cert-tls server remote-cert-tls server
auth-user-pass auth-user-pass
script-security 2c
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
compress compress
ncp-disable ncp-disable
verb 3
reneg-sec 0
keepalive 5 30
fast-io
sndbuf 393216
rcvbuf 393216
cipher AES-256-GCM cipher AES-128-CBC
auth SHA256 auth SHA256
key-direction 1 key-direction 1
setenv CLIENT_CERT 0

Let me know if this helps.

**Comment by Zomboided** [comment]
Let's do it a different way.  You mentioned a missing or broken location, I
think it was Amsterdam?  Whatever location it was, can you get that from
the config generator and attach it to this issue report please.

**Comment by garypower** [comment]
Hey Zomboided,

Sorry again for the late reply. The missing location was Manchester
England.

I have taken the config from the Torguard website see screenshot and
attached the config minus the ssh keys.

Let me know if you need anything else.

Kind regards

Gary

**Comment by garypower** [comment]
sorry my attachments didnt post via email reply
![configGen](https://user-images.githubusercontent.com/8248311/149311385-d9e56977-c998-411a-af9c-803eafff4423.png)

[26.TXT](https://github.com/Zomboided/service.vpn.manager/files/7861921/26.TXT)

**Comment by Zomboided** [comment]
The file I've linked above is from 2019, I can't find anything newer.

Either you can download all of the locations and send them to me in a zip, or I can deprecate support and you can just use user defined and import the locations you need.  Your choice how you proceed.

**Comment by garypower** [comment]
ok i've tried the user defined.

it wont connect either. Hangs when connecting to the ip of the server then
times out. I've SSH'd onto the server and the vpn server is pingable and
the port settings are correct.

Cant currently see what the issue is. Will work on it later.

Thanks for all your help thus far.

**Comment by Zomboided** [comment]
Deprecated TorGuard as I don't have that latest location data.  If anyone is willing to provide this, I'll reverse the deprecation.
