### ISSUE TITLE
Pi zero w Libreelec up script fails

### ISSUE THREAD

**Issue by Oblivion25** [Zomboided/service.vpn.manager#359]
I'm using  Libreelec on a pi zero w running version 9.2.6 of Libreelec I've tried everything I can think of to fix this problem with no luck but every time I go to establish a vpn connection (using user defined settings) I keep getting the error "up script fails with '/etc/openvpn/update-resolv-conf': no such file directory (errno=2)" I have gotten this addon to work with OMSC but no luck on Libreelec

**Comment by Zomboided** [comment]
update-resolv-conf is a separate package that's not installed by default with LE (or OpenVPN) but is included with the OMSC build.  There are some words here https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#potential-dns-fix-linux-only about using these scripts and where to get them from.

Your options are to install it yourself (and everything that it drags along) or determine if you need to use the up script (and one reason might be to ensure the right DNS is being used).  Either way, it's not an issue with VPN Mgr so closing this.
