### ISSUE TITLE
Router drops connection to internet

### ISSUE THREAD

**Issue by fthmhmt** [Zomboided/service.vpn.manager#36]
I was using openvpn connection by command line and saw your addon for Kodi. I am using PureVPN and setup your addon fine but for any reason(s) it drops the internet connection of the router. I have a cable router/modem from provider with really less setting options.

No logs are saved to get any idea why it is down. Over the command line the router is working fine without any problems.The Router is a Thomson TWG870UG

**Comment by Zomboided** [comment]
"All" the add-on does is run openvpn as if you had run it on the command line.  If you're saying that it works via the command line on the same machine without issue, but when run via the add-on it causes your router to fail in some way, then that makes no sense (unless there are some differences with the ovpn).

You could try disabling this option
https://github.com/Zomboided/service.vpn.manager/wiki/06.-Debug-Options#check-connection-with-ping

And maybe disable this option
https://github.com/Zomboided/service.vpn.manager/wiki/06.-Debug-Options#enable-updown-scripts

Changing these would make the ovpn file being used identical to those supplied by Pure.  If it still happens then, then I've no clue (and I'm not going to google around your router, you can do that)

There was also this issue, but if you're saying it works via the command line then maybe it's not relevant.
https://github.com/Zomboided/service.vpn.manager/issues/31

**Comment by Zomboided** [comment]
Closed as there's no evidence this is a problem with the addon
