### ISSUE TITLE
hide.me: ip is not changed

### ISSUE THREAD

**Issue by oliaros** [Zomboided/service.vpn.manager#360]
System: pi3 b+
libreelec leia v9.2.8
zomboid service.manager v6.4.2

issue: ip is not changed, no vpn

openvpn.log:
Sat Jan 22 12:36:09 2022 WARNING: file
'/storage/.kodi/addons/service.vpn.manager/HideMe/ta.key' is group or
others accessible
Sat Jan 22 12:36:09 2022 WARNING: file
'/storage/.kodi/addons/service.vpn.manager/HideMe/pass.txt' is group or
others accessible
Sat Jan 22 12:36:09 2022 OpenVPN 2.4.7 armv7ve-libreelec-linux-gnueabi
[SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [AEAD] built on Jul  6 2021
Sat Jan 22 12:36:09 2022 library versions: OpenSSL 1.1.1d  10 Sep 2019,
LZO 2.10
Sat Jan 22 12:36:09 2022 TCP/UDP: Preserving recently used remote
address: [AF_INET]37.46.120.105:3000
Sat Jan 22 12:36:09 2022 UDP link local: (not bound)
Sat Jan 22 12:36:09 2022 UDP link remote: [AF_INET]37.46.120.105:3000
Sat Jan 22 12:36:09 2022 WARNING: this configuration may cache passwords
in memory -- use the auth-nocache option to prevent this
Sat Jan 22 12:36:09 2022 [*.hide.me] Peer Connection Initiated with
[AF_INET]37.46.120.105:3000
Sat Jan 22 12:36:10 2022 Options error: Unrecognized option or missing
or extra parameter(s) in [PUSH-OPTIONS]:11: dhcp-renew (2.4.7)
Sat Jan 22 12:36:10 2022 Options error: Unrecognized option or missing
or extra parameter(s) in [PUSH-OPTIONS]:12: dhcp-release (2.4.7)
Sat Jan 22 12:36:10 2022 Options error: Unrecognized option or missing
or extra parameter(s) in [PUSH-OPTIONS]:13: register-dns (2.4.7)
Sat Jan 22 12:36:10 2022 Options error: Unrecognized option or missing
or extra parameter(s) in [PUSH-OPTIONS]:14: block-outside-dns (2.4.7)
Sat Jan 22 12:36:10 2022 TUN/TAP device tun0 opened
Sat Jan 22 12:36:10 2022 /sbin/ip link set dev tun0 up mtu 1500
Sat Jan 22 12:36:10 2022 /sbin/ip addr add dev tun0 10.134.152.96/23
broadcast 10.134.153.255
Sat Jan 22 12:36:10 2022 /sbin/ip -6 addr add
fd00:6968:6564:34c:c11e:c3b9:1dec:3a09/64 dev tun0
ip: RTNETLINK answers: File exists
Sat Jan 22 12:36:10 2022 ERROR: Linux route add command failed: external
program exited with error status: 2
Sat Jan 22 12:36:10 2022 add_route_ipv6(::/3 -> fd00:6968:6564:34c::1
metric -1) dev tun0
Sat Jan 22 12:36:10 2022 add_route_ipv6(2000::/4 ->
fd00:6968:6564:34c::1 metric -1) dev tun0
Sat Jan 22 12:36:10 2022 add_route_ipv6(3000::/4 ->
fd00:6968:6564:34c::1 metric -1) dev tun0
Sat Jan 22 12:36:10 2022 add_route_ipv6(fc00::/7 ->
fd00:6968:6564:34c::1 metric -1) dev tun0
Sat Jan 22 12:36:10 2022 Initialization Sequence Completed

what can i do? thanks for your support,
oliaros

**Comment by oliaros** [comment]
The support from hide.me (Matas) helped to solve the issue: In the *.ovpn files the following line has to be added
just before the <ca> block:
redirect-gateway def1
This worked for me,
oliaros

**Comment by Zomboided** [comment]
ok thanks, I'll update the template with this.

**Comment by oliaros** [comment]
it should read:
The support from hide.me (Matas) helped to solve the issue: In the *.ovpn files the following line has to be added
just before the block <ca>:
redirect-gateway def1
Sorry about the missing item,
oliaros

**Comment by oliaros** [comment]
t should read:
The support from hide.me (Matas) helped to solve the issue: In the *.ovpn files the following line has to be added
just before the block CA:
redirect-gateway def1
The system don't like the brackets :-(
oliaros

**Comment by oliaros** [comment]
@Zomboided
it would be nice if you could update teh Leia-version too.
regards oliaros

**Comment by Zomboided** [comment]
> t should read: The support from hide.me (Matas) helped to solve the issue: In the *.ovpn files the following line has to be added just before the block CA: redirect-gateway def1 The system don't like the brackets :-( oliaros

I don't understand what you're saying here.  When I look at the generated files using the new chnage I don't see brackets.  You'll need to show me a log demonstrating this issue.  (see the wiki trouble shooting page on how to do this).



> @Zomboided it would be nice if you could update teh Leia-version too. regards oliaros
Same files are shared across the different versions.

**Comment by Zomboided** [comment]
Closing this as I don't think there's an outstanding issue
