### ISSUE TITLE
option to use smart DNS proxy

### ISSUE THREAD

**Issue by CharlieTemplar** [Zomboided/service.vpn.manager#361]
Not really a bug with this plugin, more a question of how to achieve.
I have one addon that needs vpn for geo-location but doesn't work with the smartDNS configured at the same time.
Another addon (different country) that only works with smart DNS proxy and won't work properly with openVPN for the same country.
Currently I have to manually change /etc/resolv.conf to change between smart DNS and real DNS.
Is there a way to handle this in vpn.manager?  like force the DNS to local or 8.8.8.8 when connecting to the VPN? and turning off vpn for the other addon.

**Comment by Zomboided** [comment]
Default the VPN to off (ie don't connect on startup).
Use filtering to turn the VPN on when you enter the addon that needs it.
Enable the up and down scripts and use those as a hook to change the DNS.
All of these things are documented on the wiki if you need more info.

**Comment by CharlieTemplar** [comment]
thanks, trying to work it out from the wiki now.  running libreelec on rpi3 with kodi 18.

**Comment by CharlieTemplar** [comment]
put a simple up.sh in the provider dir but is never run, neither is down.sh
is there an option someplace to enable?

**Comment by Zomboided** [comment]
Yes, in the advanced tab i think.  You can see the effect from looking at the generated ovpn files in .../kodi/addons/service.vpn.manager/<provider>

**Comment by CharlieTemplar** [comment]
had the up.sh and down.sh in wrong place, had put them in the addons dir with the ovpn file...
now working great and added the other addon to excluded list from vpn, otherwise it didn't disconnect after switching from the addon that didn't use it.

Thanks
