### ISSUE TITLE
Backup, Ex- and Import function to transfer all settings to different devices

### ISSUE THREAD

**Issue by slider666man** [Zomboided/service.vpn.manager#364]
What is the best and easiest way to backup all relevant manager settings to transfer and backup to different devices?
I have a custom VPN setup and different countries set up for different addons. So far everything is finally running correctly. It took me a lot of time to get everything working correctly. 
To avoid having to do this over and over again on my other devices, and for backup, I would really appreciate such functionality :)

**Comment by Zomboided** [comment]
It'd take me a lot longer to code and test what you want!  And honestly this is too niche to implement.

You could install the addon on the new box(es) and don't configure.  And then copy the .../kodi/addons/service.vpn.manager/*.* and .../kodi/userdata/addon_data/service.vpn.manager/*.* from the working box to the new box(es) and reboot it.  If that doesn't work, then validate a single user defined connection and then do the copying.  Probably best done using SSH and SCP/SFTP so the GUI doesn't get involved.

**Comment by Zomboided** [comment]
Thanks for the confirmation.  With 'regular' VPNs, they'll be downloaded.
With user defined, there will be more to copy over.  Maybe you just need to
copy the userdata piece...I can't recall exactly where stuff gets placed!
