### ISSUE TITLE
huge amount of logs from kodi.sh

### ISSUE THREAD

**Issue by lmarceg** [Zomboided/service.vpn.manager#365]
Hi,
I have just installed the VPN Manager  in LibreELEC 10.,0.0.2 and I am using NordVPN. It looks like it is working fine (it's not so easy to check it from the GUI, actually) but I saw iit in the logs
However, the journalctl reports thousands of logs coming from kodi.sh that reports a number:

```
Apr 27 13:04:55 LibreELEC kodi.sh[18555]: 775
Apr 27 13:05:00 LibreELEC kodi.sh[18560]: 775
Apr 27 13:05:05 LibreELEC kodi.sh[18565]: 775
Apr 27 13:05:09 LibreELEC kodi.sh[18662]: 775
Apr 27 13:05:14 LibreELEC kodi.sh[18667]: 775
Apr 27 13:05:18 LibreELEC kodi.sh[18672]: 775
Apr 27 13:05:23 LibreELEC kodi.sh[18677]: 775
Apr 27 13:05:28 LibreELEC kodi.sh[18682]: 775
Apr 27 13:05:32 LibreELEC kodi.sh[18683]: 775
Apr 27 13:05:37 LibreELEC kodi.sh[18688]: 775
Apr 27 13:05:42 LibreELEC kodi.sh[18785]: 775
Apr 27 13:05:46 LibreELEC kodi.sh[18790]: 775
Apr 27 13:05:51 LibreELEC kodi.sh[18795]: 775
Apr 27 13:05:56 LibreELEC kodi.sh[18800]: 775
Apr 27 13:06:00 LibreELEC kodi.sh[18805]: 775
Apr 27 13:06:05 LibreELEC kodi.sh[18812]: 775
Apr 27 13:06:09 LibreELEC kodi.sh[18856]: 775
Apr 27 13:06:14 LibreELEC kodi.sh[18914]: 775
Apr 27 13:06:19 LibreELEC kodi.sh[18915]: 775
Apr 27 13:06:23 LibreELEC kodi.sh[18920]: 775
Apr 27 13:06:28 LibreELEC kodi.sh[18925]: 775
Apr 27 13:06:33 LibreELEC kodi.sh[18930]: 775
Apr 27 13:06:37 LibreELEC kodi.sh[18935]: 775
Apr 27 13:06:42 LibreELEC kodi.sh[19032]: 775
Apr 27 13:06:44 LibreELEC connmand[465]: ntp: adjust (slew): -0.001108 sec
Apr 27 13:06:47 LibreELEC kodi.sh[19037]: 775
Apr 27 13:06:51 LibreELEC kodi.sh[19042]: 775
Apr 27 13:06:56 LibreELEC kodi.sh[19047]: 775
```

Basically, I cannot use the logs anymore as the logfile stores only a certain amount of rows.
if I do a ps, I see that 775 is the vpn process

```
550 root      0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
  771 root      0:50 /storage/.kodi/addons/service.tvheadend43/bin/tvheadend -B -C -u root -g video -c /storage/.kodi/userdata/addon_data/service.tvheadend43
  775 root      0:00 /usr/sbin/openvpn --daemon --config /storage/.config/openvpn.config
  782 root      0:00 [kworker/u9:1-hc]

```

I didn't activate any logs (AFAIK), is there a way to stop this log? It appeared right after I installed the vpn service.
Thanks!

**Comment by Zomboided** [comment]
That's not something the add-on produces.  You could try turning down the level of debugging that kodi is doing or using the add-on to reduce the verb (ie the openvpn logging).

There used to be a lot of crap sent to the log because Kodi 10 wasn't happy with the way the add-on front end was defined, but last time I looked they'd not provided any doc to show what needed to be updated.  And I'm not sure it's relevant here as it was a different kind of crap to what you're seeing.
