### ISSUE TITLE
OpenVPN Manager holds window focus Kodi 19.4 on RPi3 (arch 64bit)

### ISSUE THREAD

**Issue by stuckinthe** [Zomboided/service.vpn.manager#366]
I've been running OpenVPN Manager for awhile on 19.3 and previous versions without issue. I did a fresh install of 19.4 and then OpenVPN Manager and then some other addons. When I clicked on the other addons (including (OpenVPN Manager), I get the circle screen and nothing appears. I noticed in the logs it says it can't focus the window. I deleted my ,.kodi folder and then installed some addons and then went to the addons without issue. I then installed OpenVPN Manager and was able to go to some addons that I previously tested but when I went to a selection of the addon that I hadn't before I lost focus and I couldn't go to any apps. I'm pretty sure it's an issue with OpenVPN Manager or my OS but I have run OpenVPN Manager on other versions of arch albeit 32 bit.

**Comment by Zomboided** [comment]
There's nothing I can do with this....there's no debug data pointing at an issue with VPN Mgr, I don't have the same environment to even test this with and I've no intention of moving to 64bit until it's better adopted.  I'll look at this if/when there's some supporting data.

**Comment by stuckinthe** [comment]
Your plugin wasn't the issue as it was something else. Sorry for the static.
