### ISSUE TITLE
Could not connect to repository error / Kodi 20 support? 

### ISSUE THREAD

**Issue by WizardKnight** [Zomboided/service.vpn.manager#368]
I was wondering if Kodi 20 was supported. 
I was trying to install the OpenVPN client onto a LibreElec Kodi 20-alpha based system, and I got a can not connect to 'could not connect to repository'. 
I know system has network and internet access, and that the hardware is functioning as expected in general. 
So I thought I would see if Kodi 20 is supported before doing any serious digging into the problem.

**Comment by Zomboided** [comment]
The repository has been reported for not being up to date, which I've still
not fixed.
I've no idea about running on 20 though, I've not even moved to 19 yet for
LE.

**Comment by Zomboided** [comment]
Honestly, my interest in being part of alpha testing whilst they're sorting
things out is low...if this problem still exists as the code firms up, feel
free to add a debug log (as per the wiki, not a full kodi debug log) to
this issue.

**Comment by Zomboided** [comment]
https://github.com/Zomboided/repository.zomboided.plugins/releases/tag/1.0.1
