### ISSUE TITLE
pivpn compatibillity

### ISSUE THREAD

**Issue by agusto3** [Zomboided/service.vpn.manager#369]
Hi, I am running the following scenario:
I have a raspberry pi 2 with kodi . I have installed the service.vpn.manager on it I have this raspberry pi at my home, and for the other hand I have a raspberry pi 3 with pivpn (openVpn) in a remote network I have a NAS behind it, my idea is to access my NAS' videos. I followed the wizard (with the option 'user defined') but I had got the following error: 
 
neither stdin nor stderr are tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Private Key Password:'. If you used--daemon, you need to use --askpass to make passphrase-protected keys work,and you can not use --auth-nocache. Exiting due fatal error

Software versions:
On Raspberry pi 2
LibreElec (Official) : 10.0.2
Kodi 19.4-Matrix
service.vpn.manager : v7.0.0

On Raspberry pi 3
Pivpn Running OpenVpn v2.4.7

**Comment by Zomboided** [comment]
See here https://github.com/Zomboided/service.vpn.manager/issues/60
The wizard doesn't deal with password protected keys and my motivation to fix this is super low.  You can either modify the imported files after the wizard has had a go, or you can not use password protected keys.
