### ISSUE TITLE
My kodi freezing when i connect to vpn server

### ISSUE THREAD

**Issue by Doktor-X** [Zomboided/service.vpn.manager#371]
Hello, i have problem for a long time that when i connect to vpn server, my android tv box that is running  coreelec freezes and i need to ssh to it in order to issue a reboot command. And then after couple of more freezes and reboots finaly start working

**Comment by Zomboided** [comment]
The add-on doesn't support Android and I've no plans to change this.

**Comment by peno64** [comment]
@Doktor-X 
Your question is confusing. You say Android box and then you say running coreelec. Coreelec is not Android. So Esther it runs Android or it runs coreelec  ..

**Comment by Doktor-X** [comment]
Its simple, i have tv box that have android on its internal storage but i run coreelec booted from sdcard on that tv box
