### ISSUE TITLE
No Colombia PIA

### ISSUE THREAD

**Issue by zofbtb** [Zomboided/service.vpn.manager#376]
I've got your 6.3.6 version on a pre Matrix Kodi box. It works great with PIA VPN but (unlike their Android app) there's no entry for Colombia.

Could this be added? I imagine it is really an issue with PIA's API

Many thanks

The work around for anyone else wanting to use Colombia is to go to

~/.Kodi/add-ons/service.vpn.manager/PIA

copy the Venezuelan TCP and UDP ovpn files and rename them as Colombia and change the subdomain in the 4th line (the 'remote' value) to "bogota.privacy.network"

**Comment by Zomboided** [comment]
https://helpdesk.privateinternetaccess.com/kb/articles/where-can-i-find-your-ovpn-files

I've regenerated based on the files PIA supply, but I don't see Colombia there.  You could have a discussion with their support team about this if you want.  Or you can carry on with the workaround, or you could use User Defined.

Feel free to reopen if PIA actually update their files so their subscribers can use their service without their app.

**Comment by zofbtb** [comment]
Thanks. Spoke to PIA but they weren't great and didn't really understand
what I wanted. They just told me to created it manually via their API
(which I don't have access to).
