### ISSUE TITLE
Zomboided VPN on router/server, multiple clients 

### ISSUE THREAD

**Issue by siliconhippy** [Zomboided/service.vpn.manager#378]
Of course this is a great tool for Kodi !

But how can we use it as a standalone package for Linux Debian/Ubuntu? This should be handy installed on a router/server with multiple clients feeding in... 😜👻 

That is, same applications on various clients could be assigned the same VPN or VPN location, saving much configuration headache on each client. Maybe have multiple VON streams supported at the same time?

Or is there such a GUI package already available for Linux ?

**Comment by Zomboided** [comment]
This was designed for Kodi, and switching based on Kodi prompts.  I'm not interested in expanding it, although I don't disagree with the use case.
