### ISSUE TITLE
/etc/openvpn/update-resolv-conf: no such file or directory

### ISSUE THREAD

**Issue by stemy2** [Zomboided/service.vpn.manager#379]
Hello, i can't use my vpn connection. I'm using the right files, but the connection fails because of the error mentioned in the title.

**Comment by Zomboided** [comment]
update-resolv-conf needs to be installed separately.  Depending on the
platform you're using Kodi with, it may or may not be there with openvpn.
For LibreELEC, I don't think it is there.  You'll need to google on how to
install it in your environment, this isn't something that  VPN Mgr can help
with

Some links here pointing to the package you need.
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#potential-dns-fix-linux-only
