### ISSUE TITLE
Don't ask to configure on every boot if user decides not to configure on instal

### ISSUE THREAD

**Issue by axelsimon** [Zomboided/service.vpn.manager#380]
Hi there,
Having a pop-up that asks technical questions (ie: the service.vpn.manager config dialog) on start up is a rather user unfriendly approach. Kodi boxes are often shared with other family members that might benefit from one person's technical knowledge but who would not know what to do when presented with the dialog.

I suggest that if a user doesn't chose to configure on first launch, the plugin should just wait until the user decides to configure it, rather than insistently ask to be configured on each boot.

**Comment by Zomboided** [comment]
You can turn the wizard nag off in the settings....I forget where exactly....
