### ISSUE TITLE
how to whitelist a port or subnet

### ISSUE THREAD

**Issue by peno64** [Zomboided/service.vpn.manager#382]
I run kodi 19 via libreelec on a raspberry pi.
I also use vpn manager to enable vpn via NordVPN.
I also installed the docker addon from kodi and then in a shell I installed home assistant in a docker container.
To access home assistant from any computer you use in a browser http://ip:8123
That all works fine.
To be able to access home assistant also from the internet I created a route on my router that my internet ip:8123 redirects to the pi ip:8123
That also works as long as the vpn is not on on the pi.  From the moment it is on it doesn't work anymore.

NordVPN says I have to whitelist subnet 192.168.0.0/16

My question now is, how can I do this? I guess I have to do this somewhere with openvpn but I have no idea how.
Do you have a clue?

Thank you.

**Comment by Zomboided** [comment]
No idea, time to use google and read the openvpn documentation.
It's likely you'll need to use the up/down scripts as the connection is
made to make the white list happen, but that's pretty well documented on
the wiki.
