### ISSUE TITLE
SmartDNSproxy VPN 

### ISSUE THREAD

**Issue by mrXoo** [Zomboided/service.vpn.manager#383]
Hi there,

Im trying to connect to SmartDNSproxy VPN, Ive tried a few ways but always cant connect. Are you able to help?

**Comment by Zomboided** [comment]
Import a vpn downloaded from your provider using the User Defined wizard.  If the ovpn file you've downloaded works via the CLI, then it should work via the User Defined wizard.  If it doesn't, then your provider should be able to support you with your use of the ovpn via the CLI.  I'm not familiar with SmartDNSproxy so can't provide any guidance here.

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/09.-User-Defined-VPNs

**Comment by mrXoo** [comment]
CLI ? What does that stand for?

**Comment by Zomboided** [comment]
CLI = command line interface.  You need to get an SSH session into the Kodi box and run openvpn via the command line.
