### ISSUE TITLE
Unable to install - Dependency could not be satisfied

### ISSUE THREAD

**Issue by matiasw** [Zomboided/service.vpn.manager#384]
I am getting "The dependency on xbmc.python version 3.0.0 could not be satisfied" when trying to install the VPN Manager Plugin on LibreELEC 9.2.8.7. `python --version` gives `Python 2.7.16` and `python3 --version` gives `python3: not found`, so what is the latest version for Python 2.7?

**Comment by matiasw** [comment]
Ok, I could install version `6.0.2`. Is this the latest that is compatible with Leia (Python 2.7)?

**Comment by peno64** [comment]
According to me 6.4.2 is the latest version compatible : https://github.com/Zomboided/service.vpn.manager/releases/tag/6.4.2

**Comment by Zomboided** [comment]
THere are two versions in the repo...a version that works with Python 3 and
a version that works with Python 2 - I can't remember the numbers, but pick
the old one and turn off automatic updating.
No more updates/fixes are happening on the older versions but it's pretty
stable anyway and I've not needed to make code changes in quite some time.
