### ISSUE TITLE
Any chance for "Lite" or "Micro" version of VPN Manager?

### ISSUE THREAD

**Issue by macruspareto** [Zomboided/service.vpn.manager#386]
Thank you for this wonderful plugin!

Just a thought/suggestion:

While the current version is working fine, the number of options and settings is overwhelming.
Its nice to have this level of customization, but maybe some of the features could be split between "Basic" and "Expert" mode?

The "Basic" level could carry only the essential number of steps:

Import the "User-Defined" ovpn script - Check for errors (pre-connection) - Connect - Mark as valid. Ready to use!

The "Expert" level would be everything else:
Pre-defined VPN providers, chain/reorder, delete/cleanup keys and certs etc.

Since many people use Kodi with a simple remote control with buttons (up, down, left, right), this would spare them of redundant typing and hopping between the menus.

Does that make any sense? 

Thanks again!

**Comment by Zomboided** [comment]
Valid suggestion, and if I wrote it all again I'd do a lot of things differently.  However, the reality is that I don't have the time or energy to rewrite it.
