### ISSUE TITLE
Nexus

### ISSUE THREAD

**Issue by pnperehod** [Zomboided/service.vpn.manager#388]
Does it work in Kodi 20 Nexus?

**Comment by peno64** [comment]
Yes it does. I have it running on Nexus and it works fine.

**Comment by pnperehod** [comment]
It stopped  working after upgrading from 19.XX to 20.  
OpenSSL: error:0A00014D:SSL routines::legacy sigalg disallowed or unsupported

**Comment by peno64** [comment]
Maybe also say on what device and OS you run this?

**Comment by pnperehod** [comment]
Sorry, Coreelec Nexus. 20.0 on Odroid C4

**Comment by peno64** [comment]
I run it on a raspberry pi 4 with libreelec and as I stated I have no problems after upgrading from kodi 19.5 to 20.0
Can't help you wil your system.

Probably you should post a full kodi log with debug from the vpn addon on to know more.

**Comment by Zomboided** [comment]
This above isn't a VPN Mgr error from what you're sharing.  Follow the troubleshooting guide on the wiki and demonstrate that a connection works through the command line and then I'll look at a debug log.  I don't have this device and I'm not going to install Coreelec to trouble shoot.
