### ISSUE TITLE
/etc/openvpn/update-resolv-conf: no such file or directory

### ISSUE THREAD

**Issue by stemy2** [Zomboided/service.vpn.manager#391]
Hello,

The vpn worked fine until today. Now i have the following error:

option error: --up scripts fails with '/etc/openvpn/update-resolv-conf': no such file or directory (errno=2)
Options error: Please correct this error.
Use --help for more information.

**Comment by Zomboided** [comment]
The error is telling you the answer...the connection file is calling that script and it doesn't exist.  What you're calling may or may not be part of your installation.  You can install update-resolv-conf if it's not.  This isn't a problem wtih the addon.
