### ISSUE TITLE
DNS leaking

### ISSUE THREAD

**Issue by healyeah** [Zomboided/service.vpn.manager#392]
Hello, 
After installing zomboided and connected successfully to a user-defined VPN provider, i ran a dns leak test and it showed as a conclusion my public IP adress at the external location, 9 DNS servers at my local location with the name of my internet provider, and the conclusion "DNS lay be leaking"? 

Any idea how to resolve this please ?

**Comment by peno64** [comment]
According to me, this VPN is for outgoing taffic, not for incoming traffic
