### ISSUE TITLE
NordVPN access issues not yet fully resolved?

### ISSUE THREAD

**Issue by TooManyUsers63920** [Zomboided/service.vpn.manager#399]
Following recent NordVPN access changes I updated service.vpn.manager to 7.0.3, configured a non-expiring access token via NordVPN's account page and successfully connected to NordVPN using this access token. Unfortunately this success was shortlived as I could no longer access NordVPN the following day.

NordVPN still seems to require username and password (pass.txt) despite logging in with an access token. My best guess is that in my troubleshooting I must have removed cached user credentials or something as I reset the VPN provider, cleared data and reinstalled the addon several times.

**Kodi log states:**
info <general>: VPN Mgr : Writing VPN credentials file to C:\Users\\\<user>\AppData\Roaming\Kodi\addons\service.vpn.manager\NordVPN\pass.txt
info <general>: VPN Mgr : Getting user credentials
error <general>: VPN Mgr : (alternativeNord.py) Couldn't get user credentials
error <general>: VPN Mgr : (alternativeNord.py) API call was https://api.nordvpn.com/v1/users/services/credentials
error <general>: VPN Mgr : (alternativeNord.py) Response was 401 Unauthorized
error <general>: VPN Mgr : (alternativeNord.py) b'{"errors":{"code":101301,"message":"Unauthorized"}}'
error <general>: VPN Mgr : (common.py) User name or password were not found, couldn't create credentials file C:\Users\\\<user>\AppData\Roaming\Kodi\addons\service.vpn.manager\NordVPN\pass.txt

**Open VPN log states:** 
Error reading username from Auth authfile: C:\Users\\\<user>\AppData\Roaming\Kodi\addons\service.vpn.manager\NordVPN\pass.txt

**Log with VPN Manager debug enabled:**
[kodi_23-04-14_20-32-55-username-removed.log](https://github.com/Zomboided/service.vpn.manager/files/11231977/kodi_23-04-14_20-32-55-username-removed.log)

Please let me know if I can do anything else to help out.

**Comment by TooManyUsers63920** [comment]
I am using the latest version with an access token, see description of issue above.

It worked for one day before the above issue started.

**Comment by peno64** [comment]
It still works here without a problem.

**Comment by TooManyUsers63920** [comment]
My best guess is that I may have removed cached user credentials or something when I reset, removed provider data and reinstalled the addon during troubleshooting.

**Comment by TooManyUsers63920** [comment]
I managed to get it working again.

I created a new access token, removed VPN Manager and related data, restarted Kodi, reinstalled VPN Manager and logged in using the new access token.

Hopefully this will continue working. No idea what happened before.

**Comment by lmarceg** [comment]
I am having exactly the same problem, it all worked (for more than one day) and then now, suddently, VPN Manager is looking for login and password in the text file. The token is still there but apparently, it's not checked

**Comment by peno64** [comment]
The file is also read with a token. I think that  your token expired for some reason so try to create a new token an provide it again to the addon.

**Comment by lmarceg** [comment]
Indeed, with a new token, it worked again
