### ISSUE TITLE
NordVPN not connecting

### ISSUE THREAD

**Issue by FatFreddysDog** [Zomboided/service.vpn.manager#404]
Hi

Can anyone help with this please, it just stopped connecting to NordVPN  this morning (see attached)
![20230824_133156](https://github.com/Zomboided/service.vpn.manager/assets/129892459/96374c58-3019-4361-8e5a-f833e367f01d)

I already use the token method for connecting so am assuming its not this
 
Thanks in advance.. !

**Comment by peno64** [comment]
No problem here with NordVPN on my kodi. I would try to generate a new token and use that one. Maybe it was expired. Make sure that you check that it may not expire.

**Comment by FatFreddysDog** [comment]
> No problem here with NordVPN on my kodi. I would try to generate a new token and use that one. Maybe it was expired. Make sure that you check that it may not expire.

@peno64  Brilliant thanks
