### ISSUE TITLE
VPN Speeds

### ISSUE THREAD

**Issue by RobJM2** [Zomboided/service.vpn.manager#415]
Hi,
Recently upgraded to full fibre 900Mb with Vodafone, I have a raspberrypi 4 with libreelec installed, VPN Manager with NordVPN , without VPN I get speedtests around 850Mbps, however with VPN, tried multiple servers, I only get around 160 Mbps ( using EZ Maintenance apps' speedtest), is this a normal drop in speed? 
Or do other VPN's work better with libreelec?

**Comment by Zomboided** [comment]
I see a drop when using PIA.  This isn't to do with the add-on though, and I don't have a view on which provider is "best".

**Comment by RobJM2** [comment]
OK, thanks, just wondered if anyone else had come across the same, and if it was normal.
