### ISSUE TITLE
VPN Connection only for kodi?

### ISSUE THREAD

**Issue by Xaratos** [Zomboided/service.vpn.manager#427]
Hello, this isnt realy an issue but more of a question:

Does this addon establish the connection only for kodi or for the whole system? 

Thank you.

**Comment by Zomboided** [comment]
Whole system, it doesn’t try and channel just kodi On 4 Nov 2024, at 06:51, Xaratos ***@***.***> wrote:﻿
Hello, this isnt realy an issue but more of a question:
Does this addon establish the connection only for kodi or for the whole system?
Thank you.
