### ISSUE TITLE
Not populating all servers

### ISSUE THREAD

**Issue by abhollan** [Zomboided/service.vpn.manager#44]
When I go to verify my VPN account (I use NordVPN), it only loads about 30 servers to choose from - mostly US and two from Vietnam. Previously in version 2.5 it showed all ~500 servers from all over the world. The servers are all up and running according to NordVPN's website so I think this is a software issue.

**Comment by Zomboided** [comment]
Works fine for me, I see 1500.  Try Settings/Utilities/Delete .ovpns and if that doesn't work, post a log with debug switched on (Settings/Debug/Enable debug)

**Comment by zeengo** [comment]
It seems that the app is unable to retrieve full server list from API. Check your firewall, make sure that NordVPN is allowed to use TCP 443 and UDP 1194 ports and that both of these ports are open.

**Comment by Zomboided** [comment]
It doesn't use the API currently, and doesn't validate the ability to get outside the firewall as a criteria for displaying a connection.

**Comment by Zomboided** [comment]
No log provided and can't recreate on latest version so closing
