### ISSUE TITLE
Asking for an update of PerfectPrivacy

### ISSUE THREAD

**Issue by stoffeldad** [Zomboided/service.vpn.manager#46]
Hi Zomboided,

thanks for this great addon! Works like a charme. Congrats for getting it into LE9... ;)
Would it be possible to update the servers of PerfectPrivacy? They made some changes and some servers are new (e.g. Basel) and some are gone (e.g. Duesseldorf).
Do you need the ta-keyfiles for the actual servers? I have them... :)

Thank you again for your great work!
Chris

**Comment by Zomboided** [comment]
Sure either attach them here or PM me on LE (zomboided) and I'll let you know an email to send them to.

**Comment by stoffeldad** [comment]
[perfectprivacy_ta_keys.zip](https://github.com/Zomboided/service.vpn.manager/files/760968/perfectprivacy_ta_keys.zip)

Here you go! ;)
Thanx!

**Comment by Zomboided** [comment]
Can I also get the ovpns please?  Either post here without your private keys or PM me on LE and I'll keep them safe.

**Comment by Zomboided** [comment]
Fixed in 2.6.2
