### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by eSkRo32** [Zomboided/service.vpn.manager#47]
So sorry to post here in issues since i didnt know where :/

Would be good to have in settings a way to only select kodi addons we want to use with a vpn

Instead of the contrary meaning, selecting addons we dont want to vpn... 

Thx :)

**Comment by Zomboided** [comment]
It already does this but the documentation wasn't clear.  I've updated it here :
https://github.com/Zomboided/service.vpn.manager/wiki/04.-Monitor-Options#automatically-connect-to-first-vpn
and :
https://github.com/Zomboided/service.vpn.manager/wiki/03.-Addon-Filtering

**Comment by schumi2004** [comment]
@Zomboided 
I followed the links but it's still not clear for me how to launch VPN for specific app(s) only.
Is this functionality removed recently?

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/03.-Connection-Filtering

Wiki page moved, functionality is still there
