### ISSUE TITLE
Unable to disable VPN for PVR IPTV Simple client

### ISSUE THREAD

**Issue by mbennehar** [Zomboided/service.vpn.manager#49]
Hello, 
Thanks for your great work. This is more of a feature request than an issue. My IPTV provider has decided to block VPN connections. I wanted to exclude IPTV Simple client from using VPN but it didn't appear on the excluded list. I don't know if there is some kind of a workaround but anyways, great addon.

**Comment by Zomboided** [comment]
Yeah it'll only switch when it detects a plugin which the TV guide is not. You should set up a cycle button on your remote to disconnect when you use the TV or run with VPN disconnected normally and only connect when you use an add-on that needs one (so switch off connect at boot)

**Comment by Zomboided** [comment]
This will be fixed in 2.8.0 with window filtering.  Instructions will be on the wiki when that release is available

**Comment by mbennehar** [comment]
Hello, 
Thanks for considering my request, waiting for the update. Great work !
