### ISSUE TITLE
Cannot install from repo on fresh installation of LibreELEC 7.0.2

### ISSUE THREAD

**Issue by matthew798** [Zomboided/service.vpn.manager#5]
Using LibreELEC 7.0.2 on RPi (version 1) the repo installs just fine. When trying to install the add-on, it says downloading o% and eventually says "unable to download ...".

Installing the addon from the zip file also fails after a long wait.

Here is a bit of the kodi log:
```
22:20:02 387.712158 T:1746924448   ERROR: Remove - Error removing /storage/.kodi/addons/service.vpn.manager/NordVPN/
22:20:02 387.712616 T:1746924448   ERROR: Remove - Error removing special://home/addons/service.vpn.manager/NordVPN/
22:20:07 393.005798 T:1746924448   ERROR: Remove - Error removing /storage/.kodi/addons/service.vpn.manager/NordVPN/
22:20:07 393.006409 T:1746924448   ERROR: Remove - Error removing special://home/addons/service.vpn.manager/NordVPN/
22:20:07 393.019287 T:1746924448   ERROR: CAddonInstallJob[service.vpn.manager]: could not read addon description of special://home/addons/service.vpn.manager
22:21:22 468.301239 T:1790702496   ERROR: Remove - Error removing /storage/.kodi/addons/service.vpn.manager/NordVPN/
22:21:22 468.301758 T:1790702496   ERROR: Remove - Error removing special://home/addons/service.vpn.manager/NordVPN/
22:21:26 471.858704 T:1790702496   ERROR: Remove - Error removing /storage/.kodi/addons/service.vpn.manager/NordVPN/
22:21:26 471.859283 T:1790702496   ERROR: Remove - Error removing special://home/addons/service.vpn.manager/NordVPN/
22:21:26 471.859833 T:1790702496   ERROR: CAddonInstallJob[service.vpn.manager]: could not read addon description of special://home/addons/service.vpn.manager
```

Some more info...

I just tried again and noticed that it very quickly goes from 0% to 100% when installing from the repo but then goes right back to 0% and gets stuck. Is it possible it's trying to download a dependency that's failing?

**Comment by matthew798** [comment]
Even more info...

I got it to install quite by accident. After the initial 0%-100% (and subsequent return to 0%) i accidentally unplugged the Pi. When i rebooted the addon was installed. When i tried to add my VPN info, it said something like: unable to activate the addon (or service or something). It sounded like it couldnt get OVPN started but thats just a guess.

**Comment by Zomboided** [comment]
Provide a full log (via pastebin) that shows the problem

**Comment by Zomboided** [comment]
No log, I can't recreate, so closing.

**Comment by matthew798** [comment]
Hello,

sorry it took so long but here are the kodi logs:

`﻿15:55:25  24.851336 T:1962643456  NOTICE: special://profile/ is mapped to: special://masterprofile/
15:55:25  24.851723 T:1962643456  NOTICE: -----------------------------------------------------------------------
15:55:25  24.851980 T:1962643456  NOTICE: Starting Kodi (16.1 Git:c327c53). Platform: Linux ARM 32-bit
15:55:25  24.852196 T:1962643456  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
15:55:25  24.852430 T:1962643456  NOTICE: Kodi compiled Jun 22 2016 by GCC 5.3.0 for Linux ARM 32-bit version 4.4.13 (263181)
15:55:25  24.853479 T:1962643456  NOTICE: Running on LibreELEC (official) - Version: 7.0.2, kernel: Linux ARM 32-bit version 4.4.13
15:55:25  24.853745 T:1962643456  NOTICE: FFmpeg version: 2.8.6
15:55:25  24.853939 T:1962643456  NOTICE: WARNING: unsupported ffmpeg version detected
15:55:25  24.854141 T:1962643456  NOTICE: Host CPU: ARMv6-compatible processor rev 7 (v6l), 1 core available
15:55:25  24.854326 T:1962643456  NOTICE: ARM Features: Neon disabled
15:55:25  24.854523 T:1962643456  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
15:55:25  24.854748 T:1962643456  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
15:55:25  24.854950 T:1962643456  NOTICE: special://masterprofile/ is mapped to: /storage/.kodi/userdata
15:55:25  24.855146 T:1962643456  NOTICE: special://home/ is mapped to: /storage/.kodi
15:55:25  24.855345 T:1962643456  NOTICE: special://temp/ is mapped to: /storage/.kodi/temp
15:55:25  24.855677 T:1962643456  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
15:55:25  24.856049 T:1962643456  NOTICE: Local hostname: MediaCenter
15:55:25  24.856285 T:1962643456  NOTICE: Log File is located: /storage/.kodi/temp/kodi.log
15:55:25  24.878698 T:1962643456  NOTICE: -----------------------------------------------------------------------
15:55:25  25.179714 T:1962643456   ERROR: DBus: Error org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
15:55:25  25.222473 T:1962643456  NOTICE: load settings...
15:55:26  25.654369 T:1962643456  NOTICE: Found 2 Lists of Devices
15:55:26  25.654686 T:1962643456  NOTICE: Enumerated PI devices:
15:55:26  25.654898 T:1962643456  NOTICE:     Device 1
15:55:26  25.656448 T:1962643456  NOTICE:         m_deviceName      : HDMI
15:55:26  25.656971 T:1962643456  NOTICE:         m_displayName     : HDMI
15:55:26  25.657228 T:1962643456  NOTICE:         m_displayNameExtra:
15:55:26  25.657440 T:1962643456  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
15:55:26  25.657646 T:1962643456  NOTICE:         m_channels        : FL,FR
15:55:26  25.657856 T:1962643456  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
15:55:26  25.658068 T:1962643456  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
15:55:26  25.658401 T:1962643456  NOTICE:     Device 2
15:55:26  25.658806 T:1962643456  NOTICE:         m_deviceName      : Analogue
15:55:26  25.659065 T:1962643456  NOTICE:         m_displayName     : Analogue
15:55:26  25.659277 T:1962643456  NOTICE:         m_displayNameExtra:
15:55:26  25.659491 T:1962643456  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:55:26  25.659691 T:1962643456  NOTICE:         m_channels        : FL,FR
15:55:26  25.659891 T:1962643456  NOTICE:         m_sampleRates     : 48000
15:55:26  25.660198 T:1962643456  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
15:55:26  25.660431 T:1962643456  NOTICE:     Device 3
15:55:26  25.660793 T:1962643456  NOTICE:         m_deviceName      : Both
15:55:26  25.661129 T:1962643456  NOTICE:         m_displayName     : HDMI and Analogue
15:55:26  25.661360 T:1962643456  NOTICE:         m_displayNameExtra:
15:55:26  25.661566 T:1962643456  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:55:26  25.661766 T:1962643456  NOTICE:         m_channels        : FL,FR
15:55:26  25.662077 T:1962643456  NOTICE:         m_sampleRates     : 48000
15:55:26  25.662300 T:1962643456  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
15:55:26  25.662518 T:1962643456  NOTICE: Enumerated PULSE devices:
15:55:26  25.662718 T:1962643456  NOTICE:     Device 1
15:55:26  25.663111 T:1962643456  NOTICE:         m_deviceName      : Default
15:55:26  25.663404 T:1962643456  NOTICE:         m_displayName     : Default
15:55:26  25.663647 T:1962643456  NOTICE:         m_displayNameExtra: Bluetooth Audio (PULSEAUDIO)
15:55:26  25.663860 T:1962643456  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:55:26  25.664059 T:1962643456  NOTICE:         m_channels        : FL,FR
15:55:26  25.664270 T:1962643456  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
15:55:26  25.664474 T:1962643456  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
15:55:26  25.731949 T:1962643456  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
15:55:26  25.732874 T:1962643456  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <showexitbutton>false</showexitbutton>
                                              <fanartres>720</fanartres>
                                              <imageres>540</imageres>
                                              <video>
                                                <busydialogdelayms>750</busydialogdelayms>
                                              </video>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                              <network>
                                                <readbufferfactor>4.0</readbufferfactor>
                                              </network>
                                            </advancedsettings>
15:55:26  25.738474 T:1962643456  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
15:55:26  25.738771 T:1962643456  NOTICE: Default DVD Player: dvdplayer
15:55:26  25.738981 T:1962643456  NOTICE: Default Video Player: dvdplayer
15:55:26  25.739174 T:1962643456  NOTICE: Default Audio Player: paplayer
15:55:26  25.739414 T:1962643456  NOTICE: Disabled debug logging due to GUI setting. Level 0.
15:55:26  25.739622 T:1962643456  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
15:55:26  25.740635 T:1962643456  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
15:55:26  25.745594 T:1962643456  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
15:55:26  25.751999 T:1962643456  NOTICE: Loaded playercorefactory configuration
15:55:26  25.753263 T:1962643456  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
15:55:26  25.754179 T:1962643456  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
15:55:26  26.023792 T:1962643456  NOTICE: Running database version Addons20
15:55:26  26.419416 T:1962643456  NOTICE: ADDONS: Using repository repository.xbmc.org
15:55:26  26.419725 T:1962643456  NOTICE: ADDONS: Using repository repository.zomboided.plugins
15:55:26  26.419924 T:1962643456  NOTICE: ADDONS: Using repository repository.libreelec.tv
15:55:27  26.652760 T:1962643456  NOTICE: Raspberry PI firmware version: Jun 20 2016 18:18:51 
                                            Copyright (c) 2012 Broadcom
                                            version 460b39c674ef2ac89360e15331f97a2cb1388a44 (clean) (release)
15:55:27  26.653147 T:1962643456  NOTICE: ARM mem: 352MB GPU mem: 160MB MPG2:0 WVC1:0
15:55:27  26.653591 T:1962643456  NOTICE: cacheMemBufferSize: 20MB
15:55:27  26.654331 T:1962643456  NOTICE: Config:
                                            audio_pwm_mode=1
                                            config_hdmi_boost=2
                                            disable_auto_turbo=1
                                            disable_commandline_tags=2
                                            enable_uart=1
                                            force_pwm_open=1
                                            framebuffer_ignore_alpha=1
                                            framebuffer_swap=1
                                            hdmi_channel_map=8
                                            hdmi_force_cec_address=65535
                                            hdmi_ignore_cec_init=1
                                            ignore_lcd=1
                                            init_uart_clock=0x2dc6c0
                                            overscan_bottom=48
                                            overscan_left=48
                                            overscan_right=48
                                            overscan_top=48
                                            pause_burst_frames=1
                                            program_serial_random=1
                                            temp_limit=85
15:55:27  26.654936 T:1962643456  NOTICE: Config:
                                            device_tree=-
15:55:27  26.655268 T:1962643456  NOTICE: InitWindowSystem: Using EGL Implementation: raspberrypi
15:55:27  26.664413 T:1962643456  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 60.000000 Hz
15:55:27  26.664753 T:1962643456  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 59.940063 Hz
15:55:27  26.664993 T:1962643456  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 72.000000 Hz
15:55:27  26.665228 T:1962643456  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 71.928070 Hz
15:55:27  26.665495 T:1962643456  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 75.000000 Hz
15:55:27  26.665730 T:1962643456  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 60.000000 Hz
15:55:27  26.665962 T:1962643456  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 59.940063 Hz
15:55:27  26.666193 T:1962643456  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 72.000000 Hz
15:55:27  26.666426 T:1962643456  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 71.928070 Hz
15:55:27  26.666658 T:1962643456  NOTICE: Found resolution 800 x 600 for display 0 with 800 x 600 @ 75.000000 Hz
15:55:27  26.667002 T:1962643456  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 60.000000 Hz
15:55:27  26.667242 T:1962643456  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 59.940063 Hz
15:55:27  26.667473 T:1962643456  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 70.000000 Hz
15:55:27  26.667728 T:1962643456  NOTICE: Found resolution 1024 x 768 for display 0 with 1024 x 768 @ 75.000000 Hz
15:55:27  26.667959 T:1962643456  NOTICE: Found resolution 1152 x 864 for display 0 with 1152 x 864 @ 75.000000 Hz
15:55:27  26.668188 T:1962643456  NOTICE: Found resolution 1280 x 800 for display 0 with 1280 x 800 @ 60.000000 Hz
15:55:27  26.668425 T:1962643456  NOTICE: Found resolution 1280 x 800 for display 0 with 1280 x 800 @ 59.940063 Hz
15:55:27  26.668659 T:1962643456  NOTICE: Found resolution 1280 x 960 for display 0 with 1280 x 960 @ 60.000000 Hz
15:55:27  26.668995 T:1962643456  NOTICE: Found resolution 1280 x 960 for display 0 with 1280 x 960 @ 59.940063 Hz
15:55:27  26.669353 T:1962643456  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 60.000000 Hz
15:55:27  26.669601 T:1962643456  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 59.940063 Hz
15:55:27  26.669844 T:1962643456  NOTICE: Found resolution 1280 x 1024 for display 0 with 1280 x 1024 @ 75.000000 Hz
15:55:27  26.670258 T:1962643456  NOTICE: Found resolution 1360 x 768 for display 0 with 1360 x 768 @ 60.000000 Hz
15:55:27  26.670509 T:1962643456  NOTICE: Found resolution 1360 x 768 for display 0 with 1360 x 768 @ 59.940063 Hz
15:55:27  26.670746 T:1962643456  NOTICE: Found resolution 1440 x 900 for display 0 with 1440 x 900 @ 60.000000 Hz
15:55:27  26.670986 T:1962643456  NOTICE: Found resolution 1440 x 900 for display 0 with 1440 x 900 @ 59.940063 Hz
15:55:27  26.671217 T:1962643456  NOTICE: Found resolution 1440 x 900 for display 0 with 1440 x 900 @ 75.000000 Hz
15:55:27  26.671448 T:1962643456  NOTICE: Found resolution 1440 x 1080 for display 0 with 1600 x 1200 @ 60.000000 Hz
15:55:27  26.671680 T:1962643456  NOTICE: Found resolution 1440 x 1080 for display 0 with 1600 x 1200 @ 59.940063 Hz
15:55:27  26.671911 T:1962643456  NOTICE: Found resolution 1680 x 1050 for display 0 with 1680 x 1050 @ 60.000000 Hz
15:55:27  26.672144 T:1962643456  NOTICE: Found resolution 1680 x 1050 for display 0 with 1680 x 1050 @ 59.940063 Hz
15:55:27  26.672396 T:1962643456  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 60.000000 Hz
15:55:27  26.672634 T:1962643456  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 59.940063 Hz
15:55:27  26.672863 T:1962643456  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
15:55:27  26.673096 T:1962643456  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 59.940063 Hz
15:55:27  26.673330 T:1962643456  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
15:55:27  26.673647 T:1962643456  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940063 Hz
15:55:27  26.673889 T:1962643456  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
15:55:27  26.674128 T:1962643456  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 23.976025 Hz
15:55:27  26.674360 T:1962643456  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 30.000000 Hz
15:55:27  26.674614 T:1962643456  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 29.970032 Hz
15:55:27  26.674835 T:1962643456  NOTICE: Found (1920x1080@60.000000) at 51, setting to RES_DESKTOP at 16
15:55:27  26.675121 T:1962643456  NOTICE: Checking resolution 16
15:55:27  26.798801 T:1962643456  NOTICE: GL_VENDOR = Broadcom
15:55:27  26.799097 T:1962643456  NOTICE: GL_RENDERER = VideoCore IV HW
15:55:27  26.799303 T:1962643456  NOTICE: GL_VERSION = OpenGL ES 2.0
15:55:27  26.799511 T:1962643456  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
15:55:27  26.799772 T:1962643456  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
22:59:56  29.497116 T:1962643456  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
22:59:57  30.142847 T:1962643456  NOTICE: Running database version Addons20
22:59:57  30.159874 T:1962643456  NOTICE: Running database version ViewModes6
22:59:57  30.182508 T:1962643456  NOTICE: Running database version Textures13
22:59:57  30.245075 T:1962643456  NOTICE: Running database version MyMusic56
22:59:57  30.353792 T:1962643456  NOTICE: Running database version MyVideos99
22:59:57  30.383165 T:1962643456  NOTICE: Running database version TV29
22:59:57  30.401344 T:1962643456  NOTICE: Running database version Epg11
22:59:57  30.414833 T:1962643456  NOTICE: start dvd mediatype detection
23:00:01  34.604164 T:1962643456 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
23:00:02  35.106197 T:1962643456  NOTICE: ActiveAE DSP - starting
23:00:02  35.176773 T:1962643456  NOTICE: initialize done
23:00:02  35.177147 T:1962643456  NOTICE: Running the application...
23:00:05  38.619102 T:1962643456  NOTICE: starting zeroconf publishing
23:00:05  38.622219 T:1962643456  NOTICE: WebServer: Started the webserver
23:00:05  38.622890 T:1962643456  NOTICE: starting upnp client
23:00:05  38.680782 T:1708127136  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
23:00:05  38.681274 T:1708127136  NOTICE: UDP: Listening on port 9777
23:00:12  45.292381 T:1812984736  NOTICE: ## LibreELEC Addon ## 0.7.3
23:00:12  45.523296 T:1812984736 WARNING: CSkinInfo: failed to load skin settings
23:00:22  55.306641 T:1962643456   ERROR: Unable to activate the previous window
23:01:40 133.231216 T:1649406880 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
23:01:42 135.227066 T:1649406880 WARNING: Previous line repeats 1 times.
23:01:42 135.227402 T:1649406880  NOTICE: LoadJpeg: unable to load http://mirrors.kodi.tv/addons/jarvis/script.evernote/fanart.jpg
23:01:42 135.548187 T:1795945376 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
23:01:44 137.217316 T:1795945376 WARNING: Previous line repeats 1 times.
23:01:44 137.221451 T:1795945376  NOTICE: LoadJpeg: unable to load http://mirrors.kodi.tv/addons/jarvis/plugin.program.wienerlinien/fanart.jpg
23:02:15 168.767624 T:1766847392 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
23:02:17 170.067566 T:1766847392 WARNING: Previous line repeats 1 times.
23:02:17 170.068176 T:1766847392  NOTICE: LoadJpeg: unable to load http://mirrors.kodi.tv/addons/jarvis/script.tv.show.last.episode/fanart.jpg
23:14:11 884.408264 T:1804333984   ERROR: Remove - Error removing /storage/.kodi/addons/service.vpn.manager/NordVPN/
23:14:11 884.408752 T:1804333984   ERROR: Remove - Error removing special://home/addons/service.vpn.manager/NordVPN/
23:14:25 897.998657 T:1804333984   ERROR: Remove - Error removing /storage/.kodi/addons/service.vpn.manager/NordVPN/
23:14:25 897.999146 T:1804333984   ERROR: Remove - Error removing special://home/addons/service.vpn.manager/NordVPN/
23:14:25 898.002991 T:1804333984   ERROR: CAddonInstallJob[service.vpn.manager]: could not read addon description of special://home/addons/service.vpn.manager`

Let me know if you need anything else

**Comment by Zomboided** [comment]
The log is saying that it can't delete some files and it can't read the descriptor in plugin.  The plugin isn't bad generally otherwise nobody would be able to install it.  I'd say this was either a problem with your install (maybe the file system has become corrupted or your memory card is bad), a problem with your download or a problem with Libreelec.

**Comment by matthew798** [comment]
I tried installing it again, and noticed that the addon gets stuck when being copied to the addon directory. Specifically, it stops in NordVPN/Switzerland (12). So I manually copied (over scp) the unzipped contents of the addon and when the copy was done, to my surprise, kodi reacted by saying the addon was successfully installed. So... It must be something with my SD card. Thanks for the help!
