### ISSUE TITLE
VPN Manager Install Fails on LibreElec 8.0.0 - 404 Not Found

### ISSUE THREAD

**Issue by Chiper82** [Zomboided/service.vpn.manager#51]
Hi,

Followed installation instructions here https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation. 

The repository installs fine, however, when you try to install the VPN Manager it fails with 

ERROR: CCurlFile::Open failed with code 404 for https://github.com/zomboided/xbmc.zomboided.plugins/raw/master/plugins/service.vpn.manager/service.vpn.manager-2.3.0.zip

http://pastebin.com/qQmq8ZNF

If I browse to that web address it doesn't exist. Throws a 404 error. From what I can tell it looks like the source files have been moved but the script hasn't been updated?

Apologies if this is the wrong place to report, however, their is no information in the wiki on how to get support and I couldn't find Zomboided in the add-ons category on the kodi forum. 

Would apreciate if someone could kindly point me in the right direction? Thanks 

Cheers,
Chiper

**Comment by Zomboided** [comment]
Urgh, screwed up the XML in the repo, thanks for reporting.  Just fixed on GitHub.
You can wait for Kodi to work it out, or you can go to your add-on, repositiories, find the zomboided repo, right click to get the info, then select update.  Then you should be able to install 3.0.0.
