### ISSUE TITLE
Cannot stop active VPN conection in OSMC

### ISSUE THREAD

**Issue by Seekser** [Zomboided/service.vpn.manager#52]
Today I encountered VPN manager dialog box freezing when trying to switch/stop VPN. 
I am with IPvanish.

http://pastebin.com/9R7gX60z

01:04:09.432 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:04:09.451 T:1715205104   DEBUG: Previous line repeats 1 times.
01:04:09.452 T:1715205104 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:04:09.452 T:1715205104   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:04:09.694 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:09.842 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:09.871 T:1390408688   DEBUG: CWebServer[80]: request received for /jsonrpc
01:04:09.961 T:1390408688   DEBUG: Previous line repeats 1 times.
01:04:09.961 T:1390408688 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:04:09.961 T:1390408688   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:04:10.424 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:10.566 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:10.744 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:04:10.764 T:1715205104   DEBUG: Previous line repeats 1 times.
01:04:10.764 T:1715205104 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:04:10.764 T:1715205104   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:04:11.149 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:11.320 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:11.899 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:12.048 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:12.632 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:12.774 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:13.355 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:13.496 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:14.076 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:14.218 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:14.796 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:14.936 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:15.515 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:15.657 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:16.253 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:16.426 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn

01:04:42.603 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:42.741 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:43.322 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:43.462 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:44.044 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:44.183 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:44.323 T:1750070256   DEBUG: script.module.osmcsetting.updates :  - blurp 971 - DialogConfirm.xml
01:04:44.765 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:44.907 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:04:45.490 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:04:45.632 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn

01:07:20.081 T:1390408688   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:20.107 T:1390408688   DEBUG: Previous line repeats 1 times.
01:07:20.107 T:1390408688 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:07:20.107 T:1390408688   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:07:20.518 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:20.655 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:20.762 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:20.783 T:1715205104   DEBUG: Previous line repeats 1 times.
01:07:20.783 T:1715205104 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:07:20.783 T:1715205104   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:07:21.262 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:21.425 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:21.763 T:1390408688   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:21.783 T:1390408688   DEBUG: Previous line repeats 1 times.
01:07:21.783 T:1390408688 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:07:21.783 T:1390408688   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:07:22.004 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:22.148 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:22.727 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:22.762 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:22.870 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:23.448 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:23.590 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:23.701 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:23.733 T:1715205104   DEBUG: Previous line repeats 1 times.
01:07:23.733 T:1715205104 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:07:23.733 T:1715205104   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:07:24.169 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:24.311 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:24.762 T:1390408688   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:24.783 T:1390408688   DEBUG: Previous line repeats 1 times.
01:07:24.783 T:1390408688 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:07:24.783 T:1390408688   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:07:24.890 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:25.043 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:25.625 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:25.762 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:25.776 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:25.788 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:25.789 T:1715205104 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:07:25.789 T:1715205104   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:07:26.372 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:26.526 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:26.759 T:1390408688   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:26.773 T:1390408688   DEBUG: Previous line repeats 1 times.
01:07:26.773 T:1390408688 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0
01:07:26.773 T:1390408688   DEBUG: CWebServer [MHD]: Internal application error, closing connection.
01:07:27.107 T:1431553008    NONE: VPN Mgr Debug: (Linux) Checking VPN task with sudo pidof openvpn
01:07:27.248 T:1431553008    NONE: VPN Mgr Debug: (Linux) Stopping VPN with sudo killall -9 openvpn
01:07:27.766 T:1715205104   DEBUG: CWebServer[80]: request received for /jsonrpc
01:07:27.785 T:1715205104   DEBUG: Previous line repeats 1 times.
01:07:27.785 T:1715205104 WARNING: CWebServer[80]: invalid response data with range start at 1 and end at 0

**Comment by Zomboided** [comment]
Looks like it can't stop the process. What version of the add-on?  Is this seen during manual switching or cycling or filtering?  And can you reliably recreate or is this randomly occurring?

**Comment by Seekser** [comment]
I'm using version 3.0.0. This happens for both manual switching, and cycling. I cannot even add a second VPN connection, unless I disable auto connect on boot. Either way it still fails to stop active the active VPN connection. This problem is persistent.

**Comment by Zomboided** [comment]
Is this the first version of the add-on you've used?  Have you successfully
used older versions of the add-on on this level of OSMC previously (and
what level?)

I've made some filtering changes in 2.8.0 and 3.0.0 so it's not out of the
question that I've introduced a bug.  If you've have it working earlier,
try 2.7.0 (from GitHub).  Seems unlikely though given the problem you're
having.

If OSMC has changed recently, check out this option
https://github.com/Zomboided/service.vpn.manager/wiki/06.-Debug-Options#alternative-running-openvpn-task-detection-linux-only

Another thing to try would be to issue the sudo kill command you see in the
log and tell me what happens - do you still see openvpn if you type in ps
-ef ?

**Comment by Seekser** [comment]
I installed the latest version of the add-on approx 2 weeks ago, I believe it was 3.0.0.

For some strange reason, the psmisc package seemed to have uninstalled itself which contained 'killall'. 

The problem was solved by installing PSmisc package.
