### ISSUE TITLE
Display current VPN status

### ISSUE THREAD

**Issue by Ferdy888** [Zomboided/service.vpn.manager#53]
Hi,
is there a possibility to press a button on the remote to display the VPN connection for about 5 seconds. I would like to check if I am still connected to my VPN while streaming via Exodus and I don't want to quit Exodus therefore.
Thank you for an answer ;-)!

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/07.-Connection-Cycling
