### ISSUE TITLE
vpn not disconnecting after exiting kodi

### ISSUE THREAD

**Issue by ringeer** [Zomboided/service.vpn.manager#54]
running kodi on a windows machine, vpn connects just fine when I start Kodi, but when I exit Kodi, openvpn  is still running and does not disconnect the vpn. any ideas?

**Comment by Zomboided** [comment]
Working as designed, but it's not a very good design I guess (doesn't matter on LibreELEC running on dedicated devices).

I'll kill the openvpn process when a shutdown signal is received. It won't close the connection if the Kodi process dies unexpectedly, but I think it will stop any running process when it starts back up again.

I'll put it in the next version when that happens

**Comment by ringeer** [comment]
Sounds good, thanks for the help.

**Comment by Zomboided** [comment]
Just fixed this in 3.1.0 which will be out in the next week or so
