### ISSUE TITLE
new nordvpn server

### ISSUE THREAD

**Issue by herrwusel** [Zomboided/service.vpn.manager#55]
Hi,
NordVPN added some new server so I thought I give you a hint that you can update your list ;) [1] Thanks for the great addon!

[1] https://nordvpn.com/blog/service-update-new-servers-added/

**Comment by Zomboided** [comment]
Thanks for the heads up.  I've updated today for 3.1.0.  They need to manage their servers transparently to the user though as the constant updating is making me want to pull support/move it to user defined.

**Comment by herrwusel** [comment]
Again new server were added by nordvpn.

**Comment by herrwusel** [comment]
Sorry to bother but again NordVPN added new servers. Thanks :)

**Comment by Zomboided** [comment]
Thanks, I've done this, but I'm going to pull support for Nord in the next update in a week or so due to the constant updates and issues with downloading so many files (now over 3000....).

**Comment by herrwusel** [comment]
Alright. Is it still to maintain NordVPN manually?

**Comment by Zomboided** [comment]
Yeah for sure, import the connections you care about using the User Defined wizard.  They should import without any modification.  And then when they change those connections, you'll need to do it again...and again.
