### ISSUE TITLE
Cannot get list of Servers for my VPN provider

### ISSUE THREAD

**Issue by The-Target** [Zomboided/service.vpn.manager#56]
Using PIA as my vpn provider entered my user name and password. Goto vpn connections and click first connection and there is nothing there punts me back to settings.

here is a log snip
11:42:09.530 T:140142877677312 NONE: VPN Mgr Debug: VPN monitor service was requested to run an update
11:42:09.531 T:140142877677312 NONE: VPN Mgr Debug: Update primary VPNs from settings
11:42:09.533 T:140142877677312 NONE: VPN Mgr Debug: Found no VPNs, setup is invalid
11:42:09.534 T:140142877677312 NONE: VPN Mgr Debug: Flag lists have changed
11:42:09.535 T:140142877677312 NONE: VPN Mgr Debug: Checking if a timer or file reboot is required
11:42:09.537 T:140142877677312 NONE: VPN Mgr Debug: Reboot timer is Off at 02:00, waiting
11:42:09.538 T:140142877677312 NONE: VPN Mgr Debug: Encountered a new window ID 10000
11:42:09.539 T:140142877677312 NONE: VPN Mgr Debug: Previous window ID was 0
11:42:09.640 T:140142877677312 NONE: VPN Mgr Debug: Requested update to service process via settings monitor
11:42:09.641 T:140142877677312 NONE: VPN Mgr Debug: Update service requested KodiMonitor
11:42:09.642 T:140142877677312 NONE: VPN Mgr Debug: Requested update to service process via settings monitor
11:42:09.643 T:140142877677312 NONE: VPN Mgr Debug: Update service requested KodiMonitor
11:42:09.644 T:140142877677312 NONE: VPN Mgr Debug: Requested update to service process via settings monitor
11:42:09.645 T:140142877677312 NONE: VPN Mgr Debug: Update service requested KodiMonitor
11:42:09.646 T:140142877677312 NONE: VPN Mgr Debug: Requested update to service process via settings monitor
11:42:09.647 T:140142877677312 NONE: VPN Mgr Debug: Update service requested KodiMonitor
11:42:09.647 T:140142877677312 NONE: VPN Mgr Debug: Requested update to service process via settings monitor
11:42:09.648 T:140142877677312 NONE: VPN Mgr Debug: Update service requested KodiMonitor
11:42:09.697 T:140144505702784 DEBUG: LogindUPowerSyscall - Received unknown signal NameAcquired
11:42:10.124 T:140142860891904 DEBUG: CZeroconfAvahi::groupCallback: Service successfully established
11:42:13.544 T:140142877677312 DEBUG: Previous line repeats 1 times.
11:42:13.545 T:140142877677312 NONE: VPN Mgr Debug: VPN monitor service was requested to run an update
11:42:13.547 T:140142877677312 NONE: VPN Mgr Debug: Update primary VPNs from settings
11:42:13.551 T:140142877677312 NONE: VPN Mgr Debug: Found no VPNs, setup is invalid
11:42:13.553 T:140142877677312 NONE: VPN Mgr Debug: Flag lists have changed
11:42:13.555 T:140142877677312 NONE: VPN Mgr Debug: Checking if a timer or file reboot is

**Comment by Zomboided** [comment]
Uninstall it.  Upgrade to 3.1.1 as there was an issue generating VPN files. Then try again with debug switched on. Put a FULL log on pastebin if that fails, don't guess what you think is relevant

**Comment by The-Target** [comment]
Ok just did sending you the full debug 
[kodi_17-03-24_12-49-41.txt](https://github.com/Zomboided/service.vpn.manager/files/869015/kodi_17-03-24_12-49-41.txt)

**Comment by Zomboided** [comment]
Openvpn can't write a logfile on whatever version of Linux you're using. See the settings/debug tab and there's an option to change it. You can read about it on the wiki if you can't find it.

**Comment by The-Target** [comment]
so I tried that settings debug and changed the path to my home/log dir I will look again and see what i can do. I am using Kodibunto


thank you for helping

**Comment by Zomboided** [comment]
Run the command exactly as shown below.  There's another debug option to remove the path name for openvpn if it's installed elsewhere if that's the problem.

sudo /usr/sbin/openvpn > /home/foomaster/.kodi/temp/openvpn.log &

**Comment by The-Target** [comment]
foomaster@Kodi-Home:~$ sudo /usr/bin/openvpn > /home/foomaster/.kodi/temp/openvpn.log &
[1] 2057
foomaster@Kodi-Home:~$

I also tried setting the remove user path but still get an error about open vpn not working

**Comment by Zomboided** [comment]
I've look at this area of code now and basically all it's doing it issuing the command via an os call then sitting in a loop for 10 seconds waiting for a log file to appear.

The tracing implies that a log file does appear, but then it doesn't think the log file is valid (which is basically just checking to see if it says 'General Options' anywhere, which from your openvpn.txt file, it does.

I'm pretty confused right now - this works for many other folk and the only bit of switching logic is to get the path for the log (which looks right, and you've tested it from the command line).  If you wanna pursue this further, reboot, run the connection and wait for the error message to happen then switch to the command line and get a ls -l of the .kodi/temp directory, and if there's a new openvpn.log file in there, copy that out.

**Comment by The-Target** [comment]
Ok it looks to be a error when running as sudo, when running as sudo from the command ling or running sudo from the addon the vpn log files would have nothing in them.

but running with out sudo was fine.

now I am getting to the checking connection but got another error do you want me to start a new item

mind you i can connect with PIA from both a command line and the network manager, but when i tryu and to connect with the addon I get the following in the log

on Mar 27 08:50:58 2017 OPTIONS IMPORT: timers and/or timeouts modified
Mon Mar 27 08:50:58 2017 OPTIONS IMPORT: LZO parms modified
Mon Mar 27 08:50:58 2017 OPTIONS IMPORT: --ifconfig/up options modified
Mon Mar 27 08:50:58 2017 OPTIONS IMPORT: route options modified
Mon Mar 27 08:50:58 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Mon Mar 27 08:50:58 2017 ROUTE_GATEWAY 10.10.2.1/255.255.255.0 IFACE=eth0 HWADDR=00:15:5d:5f:33:02
Mon Mar 27 08:50:58 2017 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
Mon Mar 27 08:50:58 2017 Exiting due to fatal error
[openvpn.txt](https://github.com/Zomboided/service.vpn.manager/files/872996/openvpn.txt)

**Comment by Zomboided** [comment]
Right, but I suspect you're getting this because you're not running openvpn
with sudo.  I'm guessing the operation is not permitted because you don't
have the right level of authority to alter something like the IP table?  Or
you aren't running Kodi with the right level of authority.

There's nothing wrong with PIA (unless they changed it overnight) because
it's what I use each and every day.

It's up to you to work this out (or not)...there's no code bug and this
works on LE and OSMC (and a variety of other flavours of Linux).  I'm not
able to debug all the problems caused by all the different versions of
Linux.

**Comment by The-Target** [comment]
understood :) I appreciate all the help so far. I am new to linux so still figuring things out.

I thought running as sudo fixes everything LOL. I will figure it out

thanks again

**Comment by The-Target** [comment]
Hate to do this but I think thee is still an issue, I am writing up exact repo steps with Pics

**Comment by Zomboided** [comment]
I still think this is a problem with your install of Linux.  Recreate on LE or OSMC and I'll look.
