### ISSUE TITLE
RA4W VPN changed encryption to AES

### ISSUE THREAD

**Issue by txGeek** [Zomboided/service.vpn.manager#57]
As noted above, on 19 March, 2017, 6 AM UTC, RA4W changed to AES encryption. The openvpn files included with the Manager need to be updated to reflect this change.

FYI, manually configuring for RA4W does work fine.

(Edit to add) Thanks for an excellent add-on!

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/releases/tag/3.1.2
Can you try it and let me know if it's good please?  I don't have a RA4W account.

**Comment by txGeek** [comment]
I tested it and it fails with a timeout error. I'll try to attach logs
later today.

**Comment by Zomboided** [comment]
Thanks....can you do a reset .ovpn and try it again please?  Just for
completeness.  Shouldn't make any difference, and I'll need a full log but
it's worth trying.

**Comment by txGeek** [comment]
The 3.1.2 version works! I did have to manually download and install it, it
wouldn't update beyond 3.1.1 automatically.

Thanks again!
Bill

**Comment by Zomboided** [comment]
Good, thanks for trying.  It won't update as I was waiting to hear it worked before updating the repository.
