### ISSUE TITLE
Unable to stop active VPN connections - OSMC

### ISSUE THREAD

**Issue by packhamc** [Zomboided/service.vpn.manager#58]
OSMC (Mar17 build)
Kodi 17.1
RPi3
VPN - Private Internet Access

Problem:
Using setup to configure secondary servers or change to a different VPN server, when a VPN is already connected, the script window hangs at "Stopping any active VPN connections".

If I open a putty terminal: 
ps -ax 
kill xxxx (openvpn)

The current VPN connection drops, the script continues without error, and connects to new VPN server successfully. However if attempt to change to another VPN server the problem continues to hang at the  "Stopping any active VPN connections" window.

 Regards, Chris.

**Comment by txGeek** [comment]
I had this, as well. Need to install "psmisc" from the command line:

**Comment by txGeek** [comment]
Sorry, 
"sudo apt-get install psmisc'

**Comment by packhamc** [comment]
Hi txGeek,

 You are a star, thanks for the very quick reply and the solution.

 Regards, Chris.

Regards,

       Chris Packham.
