### ISSUE TITLE
Hi I haven't been able to validate or connect any VPN 

### ISSUE THREAD

**Issue by mrrizvionline** [Zomboided/service.vpn.manager#59]
Hi ... I have tried the OpenPVN Manager with over 9 services now and it hasn't validated or worked with either one of them. I am attaching the Log File with the error in it I hope it can sort this issue for me. 

![kodi openvpn manager error](https://cloud.githubusercontent.com/assets/24730565/24708441/4d3342e6-1a30-11e7-8858-6dba45e6cb5a.jpg)

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation#windows

**Comment by mrrizvionline** [comment]
hey man ... the OpenVPN link takes me to PrivateTunnel's website which I already know about. I am a reviewer I need to make your add-on work from within Kodi before I can write a review.  Any suggestions?

**Comment by Zomboided** [comment]
The second paragraph about running Kodi in admin mode.  If you don't, it
won't let the add-on mess with IP routing tables.

**Comment by mrrizvionline** [comment]
ok got it ... let me check , i think I have admin access

**Comment by mrrizvionline** [comment]
thanks man works like a gem ... most obliged !
