### ISSUE TITLE
Unable to validate server using PIA/Kodi 17.1

### ISSUE THREAD

**Issue by beckyboo123** [Zomboided/service.vpn.manager#63]
Hi I had been using OpenElec 7 and today upgraded to 8 so that I could get the Kodi 17.1 update but since I upgraded I have been unable to connect to any PIA servers.
I have uninstalled and reinstalled VPN but each time it times out validating the connection.
I am seeing an error message in the logs but I don't know what it means. Could you help please?

"ERROR: Cannot open TUN/TAP dev dev/net/tun:No such file or directory (errno=2)

Thanks in advance

**Comment by Zomboided** [comment]
https://github.com/Zomboided/repository.zomboided.plugins/issues/3#issuecomment-293478920

Looks like an issue with OE8
