### ISSUE TITLE
OpenElec Raspberry Pi B+ PIA error

### ISSUE THREAD

**Issue by p759441** [Zomboided/service.vpn.manager#66]
Hey I've been trying to get this to work but I've had no luck here is the error https://gist.github.com/p759441/409e6d14d051c0d985861f8675383b79 .

**Comment by Zomboided** [comment]
Fixed in 4.0.5

**Comment by Zomboided** [comment]
You should also look if you've got this installed several times somehow as there looks to be competing tasks running.
