### ISSUE TITLE
Switch between location and server views

### ISSUE THREAD

**Issue by cannyjock** [Zomboided/service.vpn.manager#67]
Running Kodi 17.1 in Libreelec 8.01. Manually updated from 3.1.1 to 4.05. When setting up first VPN connection, get a box which says Switch between location and server views, but there doesn't seem to be a way to select this, only cancel.

**Comment by cannyjock** [comment]
Fixed this by uninstalling, deleting user addon data including xml file, and now it works

**Comment by Zomboided** [comment]
Yeah, bug, fixed in 4.0.6
