### ISSUE TITLE
Windscripe stopped working

### ISSUE THREAD

**Issue by derrabe1980** [Zomboided/service.vpn.manager#68]
I am unable to connect to windscribe. It successfully pulls down the sever listings and  It works fine on kodi 16 but 17.1 fails wet I try to connect to any of them.  I tried multiple diferent platforms and connections but I get the same error.  I have a screen capture of log but I don't know how to upload the log on this issue.

**Comment by derrabe1980** [comment]
OpenVPN Log 

Tue Apr 18 20:40:21 2017 WARNING: file is group or 

others accessible 

Tue Apr 18 20:40:21 2017 WARNING: file Vstorage/.kodi/addons/service.vpn.managermindscribe/pass.txt' is group or 

others accessible 

Tue Apr 18 2017 OpenVPN 2.4.1 armv7ve-openelec-linux-gnueabi ESL (OpenSSL)) CLZOI CEPOLLJ CAEADI built on 

Apr 9 2017 

Tue Apr 18 2017 library versions: LibreSSL 2.4.5, LZO 2.10 

Tue Apr 18 2017 WARNING: --ns-cert-type is DEPRECATED. Use --remote-cert-tls instead. 

Tue Apr 18 2017 TCP/UDP: Preserving recently used remote address: CAF_1NET1207.244.67.1 :443 

Tue Apr 18 2017 UDP link local: (not bound) 

Tue Apr 18 2017 UDP link remote: :443 

Tue Apr 18 20:40:21 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option 

to prevent this 

Tue Apr 18 2017 VERIFY ERROR: depth-I error-format error in certificate's notAfter field: c-CA, ST-ON, 

L:Toronto, O-Windscribe Limited, OU-Operations, CNSWindscribe Node CA 

Tue Apr 18 2017 OpenSSL: verify failed 

Tue Apr 18 2017 TLS_ERROR: BIO read error 

Tue Apr 18 20:40:21 2017 TLS Error: TLS object incoming plaintext read error 

Tue Apr 18 2017 TLS Error: TLS handshake failed 

Tue Apr 18 20:40:21 2017 SIGUSRI Csoft,tls-error) received, process restarting

**Comment by Zomboided** [comment]
Go to setting/utilities and clear the provider files and try again to connect. TLS errors are documented on the wiki in trouble shooting. Windscribe was working for me on 17 a few days ago.

**Comment by Zomboided** [comment]
Just tried Windscribe, worked fine.  This is something to do with your environment.

**Comment by derrabe1980** [comment]
Please reopen this.   I have tried it on multiple platforms and even a brand new untouched install of Librelec and getting the same results.   Below is the error message I am getting no matter what system I use.   I get the list and have tried clearing the provided data as well as downloading and install a brand new OS and the only add on I install is zombioded.

**Comment by derrabe1980** [comment]
This is the error I am getting no matter what version of kodi 17.1 I use.    I contacted my vpn provider over this issue and they say it is a problem with the addon.  [http://imgur.com/AerMZan](url)

**Comment by Zomboided** [comment]
Well it works for me (and other people), and I've checked that the ovpn
files in use are the same as are available from Windscribe today.  The
error you're seeing suggests that it's your environment that's causing the
problem - which I'm not going to debug for you.  If you can show that it
works from the command line, outside of the add-on then I'll take another
look.

**Comment by derrabe1980** [comment]
I would love to test it from the command line for you but I have no idea how to do that.   Part of the reason I am asking you the developer.   If it was just one system having this problem then I would agree that this is possibly a problem on my end.    But it works just fine on version 16 and it does not for me on raspberry pi.   Please provide me some instruction on the commandline side and I will give it a shot and let you know

**Comment by Zomboided** [comment]
Go and read the trouble shooting page on the wiki, that's why it's there. I
don't have the time to support everyone in your position, especially when
it's pointing to a problem in your environment which I'm not going to be
able to recreate.  Sorry...

**Comment by Zomboided** [comment]
This is likely your problem
https://github.com/Zomboided/service.vpn.manager/issues/48

**Comment by BetterTimes** [comment]
I get the same error massage like derrabe1980 does, using Kodi 17.1 on windows 10 and libreelec 8.01.

**Comment by derrabe1980** [comment]
This issue appears to be related to the 2038 bug.   I downloaded and
installed an the latest alpha version for Openelec with kodi 18 and the
issue is resolved so it looks like it is something in the coding of kodi 17
