### ISSUE TITLE
VPN monitor

### ISSUE THREAD

**Issue by kebogaer** [Zomboided/service.vpn.manager#70]
This is not really a bug, but more like a feature request ...
It happens often (with various vpn providers) that my vpn connection is just stuck, meaning, the vpn seems to be running, the ip is still there, but no traffic seems to be running over the tunnel.
A reconnect to the vpn solves the poblem.
So my question: would it be possible t add like a simple ping towards any high available DNS every minute or so, so that you know at least some higher layrs work?
I actually dont know what you test for themoment to check if the VPN is still working?

**Comment by kebogaer** [comment]
by the way, I love your addon!

**Comment by Zomboided** [comment]
I added a keep alive ping a couple months ago where openvpn itself will ping the connection every 30 seconds (I think, can't exactly remember) to keep it alive if the connection was dormant.

To be honest tho if you're seeing this across multiple providers on multiple different servers, I'd be thinking it was something to do with your modem/network. If it was just one server, then I'd be nagging the provider to find out why their service is a bit crap.

**Comment by kebogaer** [comment]
where are you pinging to and what happens when the ping does not get a reply?

**Comment by Zomboided** [comment]
https://openvpn.net/index.php/open-source/documentation/manuals/65-openvpn-20x-manpage.html
Search for ping-exit

**Comment by kebogaer** [comment]
causes openvpn to exit, not sure what that means ... does that mean that after 1 minute openvpn cuts the connection, and you get in hanging state?

**Comment by Zomboided** [comment]
I use 30 seconds for most providers, but it means that after 30 seconds,
openvpn will terminate and VPN Mgr will start it up again when it notices
(which is some more seconds later).

However, it's possible that ping is working but data can't be transferred I
guess.

I still think there's something else going on with your network or ISP here
though - it's really not normal that you see that many issues across
multiple providers.

**Comment by kebogaer** [comment]
Well, it is really not happening often, sometimes after a week, sometimes after 2 weeks. Can be sometimes after a day. Then the connections just hangs. Luckily this also works  like some kind of a kill switch because the VPN hangs, but not other traffic can pass, so no private information is leaked ...
Just annoying because I have to go into the GUI, and manually restart the VPN service, and it works again.

**Comment by kebogaer** [comment]
perhaps forgot to mention, when I ping to www.google.com, when the situation occurs, the ping fails... After the VPN reconnect the ping works again.

**Comment by Zomboided** [comment]
You could have a script running in the background that does the ping every
minute to google and if it gets no response just goes and kills openvpn -
this should cause it to get restarted and the connection to restart.  I
don't know why the openvpn ping is working and yours is not.  Either way
it's too niche for me to fix in my add-on.

**Comment by kebogaer** [comment]
so if I kill openvpn, your addon tries to restart it, right?
might be a good solution then

**Comment by Zomboided** [comment]
Yeah...there are a bunch of options on the monitor tab to determine how
often to check openvpn is still running.  I run with every 30 seconds,
including when playing, but the reality is that the processing power to do
this is mega low and playing a movie is pretty low effort (HEVC aside) so
you could reduce it right down to the minimum (which I think is every 10
seconds?)
