### ISSUE TITLE
ExpressVPN not working VERIFY ERROR

### ISSUE THREAD

**Issue by zayfodbbox** [Zomboided/service.vpn.manager#71]
Followed the guide and the add-on is pretty self explanatory. I used the directions for Linux OpenVPN from the ExpressVPN website, got my username and password, pulled the .ovpn file for the location I was attempting to connect, and also downloaded my certificates. I uploaded the .ovpn file to the PI so that I could simply point to it when the initial connection requested it. I have run through several scenarios, using both credential sets that I have, one for the ExpressVPN site for my account and then the se that is provided under the Linux instructions. I must admit, that it has been some time since I troubshot a VPN connection so I am a little rusty. I thought about uploading my certificate files, rather than having them extracted from the .ovpn, but until I looked at the full log, I didn't know the path where those files reside. Aside from that have you any suggestions? I tried removing the #REMOVE statements from the template file referenced in the earlier issue. I know it's not internet connectivity as the status pulls my correct external address versus the VPN provider. It appears to be somewhere in my configuration but I have been through most of the options and nothing is jumping out at me.

Thanks, for your help!

20:52:36.181 T:1624105888    NONE: VPN Mgr Debug: Checking for user key /storage/.kodi/userdata/addon_data/service.vpn.manager/ExpressVPN/user.key
20:52:36.192 T:1624105888    NONE: VPN Mgr Debug: Checking for user cert /storage/.kodi/userdata/addon_data/service.vpn.manager/ExpressVPN/user.crt
20:52:36.204 T:1624105888    NONE: VPN Mgr Debug: One of the user key and cert files did not exist
20:52:40.623 T:1624105888    NONE: VPN Mgr Debug: Extracing key and cert from /storage/downloads/my_expressvpn_russia_udp.ovpn to /storage/.kodi/userdata/addon_data/service.vpn.manager/ExpressVPN/user.key and /storage/.kodi/userdata/addon_data/service.vpn.manager/ExpressVPN/user.crt
20:52:40.635 T:1624105888    NONE: VPN Mgr Debug: Checking directory path exists for key and cert /storage/.kodi/userdata/addon_data/service.vpn.manager/ExpressVPN
20:52:40.649 T:1624105888    NONE: VPN Mgr Debug: Connecting using profile Russia (UDP).
20:52:40.707 T:1624105888    NONE: VPN Mgr Debug: (Linux) Starting VPN with /usr/sbin/openvpn "/storage/.kodi/addons/service.vpn.manager/ExpressVPN/Russia (UDP).ovpn" > /run/openvpn.log &
20:52:42.871 T:1624105888    NONE: VPN Mgr Debug: Reading log file
20:52:42.893 T:1624105888    NONE: VPN Mgr Debug: VPN connection status is 3
20:52:43.404 T:1624105888  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 WARNING: file '/storage/.kodi/userdata/addon_data/service.vpn.manager/ExpressVPN/user.key' is group or others accessible
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 WARNING: file '/storage/.kodi/addons/service.vpn.manager/ExpressVPN/ta.key' is group or others accessible
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 WARNING: file '/storage/.kodi/addons/service.vpn.manager/ExpressVPN/pass.txt' is group or others accessible
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 OpenVPN 2.4.0 armv7ve-libreelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [AEAD] built on Feb 26 2017
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 library versions: LibreSSL 2.4.4, LZO 2.09
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]37.0.127.123:1195
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 Socket Buffers: R=[163840->327680] S=[163840->327680]
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 UDP link local: (not bound)
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:40 2017 UDP link remote: [AF_INET]37.0.127.123:1195
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 TLS: Initial packet from [AF_INET]37.0.127.123:1195, sid=8801cc09 0e1c4a77
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com
**20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 VERIFY ERROR: depth=0, error=format error in certificate's notAfter field: C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-285-1a, emailAddress=support@expressvpn.com
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 OpenSSL: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 TLS_ERROR: BIO read tls_read_plaintext error
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 TLS Error: TLS object -> incoming plaintext read error
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 TLS Error: TLS handshake failed**
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 SIGUSR1[soft,tls-error] received, process restarting
20:52:43.405 T:1624105888  NOTICE: Tue May  2 20:52:41 2017 Restart pause, 5 second(s)
20:52:43.405 T:1624105888  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end
20:52:43.783 T:1624105888   ERROR: VPN Mgr : (common.py) Error connecting to VPN, could not estabilish connection. Check your username, password and network connectivity and retry.
20:52:43.815 T:1624105888    NONE: VPN Mgr Debug: (Linux) Stopping VPN with killall -9 openvpn
20:52:43.920 T:1624105888    NONE: VPN Mgr Debug: Requesting service restarts
20:52:44.899 T:1481499552    NONE: VPN Mgr Debug: Service received a start request
20:52:47.075 T:1624105888 WARNING: CSkinInfo: failed to load skin settings
20:52:48.923 T:1481499552    NONE: VPN Mgr Debug: VPN monitor service was requested to run an update
20:52:48.944 T:1481499552    NONE: VPN Mgr Debug: Update primary VPNs from settings
20:52:48.990 T:1481499552    NONE: VPN Mgr Debug: Found no VPNs, setup is invalid
20:52:49.015 T:1481499552    NONE: VPN Mgr Debug: Flag lists have changed
20:52:49.034 T:1481499552    NONE: VPN Mgr Debug: Checking if a timer or file reboot is required

ExpressVPN works with my other devices, just trying this in LibreELEC on a PI...

**Comment by Zomboided** [comment]
Unfortunately, I suspect it's this : https://github.com/Zomboided/service.vpn.manager/issues/48#issuecomment-279220059

**Comment by derrabe1980** [comment]
I had this info with my vpn so far the fix is to run kodi ver 18 alpha or
ver 16

**Comment by Zomboided** [comment]
LE7 was fine...OE7 is probably ok.  The problem is not with Kodi, it's with
openSSL, and what the different distros choose to use from what I can
tell.  I don't know what they're plannign on doing in newer LE and OE builds

**Comment by zayfodbbox** [comment]
This was installed from NOOBS 2.4 so I assume that it pulled LE7. I guess I need to go in and check the LE version.

**Comment by michigan11** [comment]
![img_0467](https://user-images.githubusercontent.com/35116938/34585709-e1cbb328-f16e-11e7-9b2b-3d218635cd9d.jpg)
![img_0468](https://user-images.githubusercontent.com/35116938/34585711-e219a042-f16e-11e7-8542-7bff2c72f6d3.jpg)

I am getting an issue on Xbox One. "VPN Manager for OpenVPN error". I cannot upload logs so the pics is the best I have. Maybe this is a known issue? I can access the settings and configure them but when I click "First vpn connection", it gives me an error. Its from the 16:35 on down. that's the log after clicking on the app within kodi.
Thanks!

**Comment by Zomboided** [comment]
I think there are a couple of problems here, neither of them I can solve.

The thing that's failing is the import of the function used to start and
stop the openvpn executable.  This suggests to me that something is missing
from the kodi implementation on the xbone that allows it to start other
programs.

The second thing that I've no idea about is how you install the openvpn
executable on the xbone.  Without this, this addon won't help you at all -
it's needed to start and stop VPN connections.  Google seems to be
suggesting that you use a VPN with the xbone through a router.

**Comment by michigan11** [comment]
Ok thanks! I was trying everything possible before connecting my vpn to the router. My router doesn't support it. Good excuse to get a new one I guess.
