### ISSUE TITLE
user defined home folder

### ISSUE THREAD

**Issue by tarasian666** [Zomboided/service.vpn.manager#72]
It will be good to change in libs/userdefined.py default folder from "c:\\" for example, to os.path.expanduser("~")  because i can't browse local folders for vpn files on *nix platform.

**Comment by Zomboided** [comment]
Yeah you're right, that's dumb.  I'll look at fixing that, thanks.

**Comment by Zomboided** [comment]
Fixed in 4.0.7

**Comment by tarasian666** [comment]
hm... still not working, i see only custom added sources
