### ISSUE TITLE
up/down script location

### ISSUE THREAD

**Issue by pank** [Zomboided/service.vpn.manager#73]
Hi,

In the [documentation](https://github.com/Zomboided/service.vpn.manager/wiki/07.-Debug-Options#enable-updown-scripts) on `up`/`down` scripts, the location for user-defined scripts are said to be `/storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/up.sh`.  On my LibreELEC, these scripts were not picked up by `service.vpn.manager` when regenerating the `ovpn` files.

Looking at the `getUpParam` in `vpnprovider.py` the location is actually `getUserDataPathWrappI am using the up script to adjust the MTU value of tun0er(getVPNLocation(provider) + "/up." + ext)` which I figure translate to something like  `/storage/.kodi/userdata/addon_data/service.vpn.manager/<VPN PROVIDER>/up.sh`?

Could the documentation and the code perhaps be out of sync here?

Thanks,

**Comment by Zomboided** [comment]
Yeah, you're right, thanks for pointing it out, I'll update it.  The up/down needs to be in the userdata directory for the VPN you're using, which I'm guessing in this case is not UserDefined.
