### ISSUE TITLE
New Hide.me VPN Server location in Italy

### ISSUE THREAD

**Issue by iz8mbw** [Zomboided/service.vpn.manager#74]
Hi.
Recently Hide.me has added a new Server in Italy.
This is the updated list of Hide.me VPN Server in Italy:

it-1.hide.me
it-2.hide.me

Please update the Hide.me Server list for Italy.
Thanks.

**Comment by Zomboided** [comment]
Can you get me the ovpn from step 3 in this link please?  Just attach it
here, it has nothing personal to you in it.
https://hide.me/en/vpnsetup/ubuntu/openvpn-command-line/

**Comment by Zomboided** [comment]
it-1.hide.me resolves to it.hide.me, so that doesn't need changing.  Still need to see an ovpn for it-2.hide.me to understand if it's used to randomly load balance, or determine where it is, so VPN Mgr is consistent with what hide.me are advertising its location to be.

**Comment by iz8mbw** [comment]
No openvpn file available yet for the other Italian location.
it-1.hide.me is a CNAME of milan-1.hide.me
it-2.hide.me is a CNAME of milan-2.hide.me

With the actual VPN Manager I connect to "it.hide.me" (the only one that exists) and someone it connect to it-1.hide.me and some it connect to it-2.hide.me. It seems that for it.hide.me the DNS record changes.

Anyway users (like me) can specify where to connect and I can choose between it-1.hide.me or it-2.hide.me

**Comment by Zomboided** [comment]
Yeah, that's a common approach to los balancing, either mask it behind a single DNS name or explicitly list them in the ovpn with the remote-random option. Do you see multiple servers listed for other locations or is this just for Italy?

**Comment by Zomboided** [comment]
They do the same thing for the UK too - you can ping uk.hide.me,
uk-1.hide.me and uk-2.hide.me.  The website is just showing one location,
so I'm gonna leave this as it is.  Letting them load balance rather that
you aiming at a specific server is a better approach generally.

If you're feel strongly that you want to use these two servers, then you
can check out the section in the wiki about overriding a VPN.  It'll direct
you on how to update the LOCATIONS.txt file to add the two servers
separately.
