### ISSUE TITLE
Verify Error when using ExpressVPN UDP

### ISSUE THREAD

**Issue by jeschergui** [Zomboided/service.vpn.manager#76]
[https://p4.zdusercontent.com/attachment/61229/en3F3jEl7LpYlbtbBbACwywcT?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..t0kD6nutrCEdKDdOKUbGmA.P_oT7t1y3NzeKa4APtrw_TXLrzXBnXJNBex3ip_LbDRX51usmuVVh_vvz87JDiBUAL4kUWJnhMi1rmKp6fMe66aaZUXd13kYruNoz2k7dS5jp-_PK8ZzqtZT0FDH2hLQiQTQjfu3nPI2W4WoqLSFGEtvwMR6uJtnGqFDw99CezbvDOMSTHtYC45DQ34gVl9Opqq_kZgl-m4QGmL_Y12TtMRGiOc6Lv9FGHP3Vu2eIG4DSW6VReiCrKt_-DTEKD_yvpgIdyGR9rS8RMXR-EkeNQ.t85cUWkKy0J9Xp12ozDcIA](url)

This really looks like SSL Handshake issue. but what would cause this? I otherwise use the username/password provided together with the opvn file that match the location of the chosen first connection...

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/issues/71
