### ISSUE TITLE
Best way to submit new VPN providers?

### ISSUE THREAD

**Issue by packtloss** [Zomboided/service.vpn.manager#77]
Hi There!

I am just wondering if you accept submissions of VPN providers which are not currently listed?
If you do, what is the best way to submit them to you?

Thanks!

**Comment by Zomboided** [comment]
I'm not mega interested in adding more as user defined import works well now. Who is it?

**Comment by packtloss** [comment]
Understood, thanks!

**Comment by mspacemedia** [comment]
SlickVPN would be nice. Or better instructions on where .ovpn files need to go. Import wizard shows me only a repo I have added not local files on the box...

**Comment by Zomboided** [comment]
The import problem is fixed with the latest version. You can see root on a Linux box now. Otherwise you'll need to map the drive properly. Can't really be assed to add and maintain many more providers, get import working or pick one that's already supported
