### ISSUE TITLE
AUTHENTICATION PROBLEMS

### ISSUE THREAD

**Issue by bonzabud** [Zomboided/service.vpn.manager#79]
This software looked ideal for my purpose and I was very pleased to find it.  However, I am using a KODI OPENELEC TV BOX and I have just signed up to my new VPN provider - PRIVATE INTERNET ACCESS. They have sent me a password and username which includes a lower case, upper case, number and at least 8 chars. When I try to enter my FIRST VPN CONNECTION I get an error message telling me that AUTHENTICATION FAILED - CHECK USERNAME AND PASSWORD. When I check this I see that my password and username is showing all in upper case. Despite the fact that it is entered with the correct lower case chars. Is this a boob in your software or is it a problem elsewhere?

Thanks

**Comment by Zomboided** [comment]
Go to the PIA User area and look for the socks password. Use that instead. I use PIA, it works just fine

**Comment by bonzabud** [comment]
Thanks  for coming back so quickly – a fantastic program – well done

– I don’t know what I did – but just before your response – it started working with original password/username.

I am a newby – Maybe a silly question to you but - How do I know the VPN is running ok?

Thanks

**Comment by Zomboided** [comment]
A message box will pop up telling you you're connected and to what IP address. This will be different, and likely show a different ISP and maybe a different country. If it's the same IP address as your router is using its broken. You'll be fine tho, if it's connected you should not worry, PIA is solid
