### ISSUE TITLE
Im getting OpenVPN executable failure message 

### ISSUE THREAD

**Issue by mrrizvionline** [Zomboided/service.vpn.manager#80]
Hi 

I am getting an OpenVPN executable failure. I have attached the log error message here, kindly help if possible. 
![openvpn error](https://cloud.githubusercontent.com/assets/24730565/26571727/0030d852-44cc-11e7-85fe-a83e59d1deba.jpg)

**Comment by Zomboided** [comment]
The plugin can't run openvpn, it's not a problem with the plugin.
https://github.com/Zomboided/service.vpn.manager/wiki/01.-Installation#linux
https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting
