### ISSUE TITLE
Latest changes to kodi, possibly CSettingsManager cause kodi to crash

### ISSUE THREAD

**Issue by Stevehans** [Zomboided/service.vpn.manager#81]
Causing Kodi to crash, not sure whether a change is needed in Kodi or in VPN Manager.

This is the PR: https://github.com/xbmc/xbmc/pull/12125

This is the discussion thread:-

https://forum.kodi.tv/showthread.php?tid=298461&pid=2598843#pid2598843

**Comment by Zomboided** [comment]
Recreate on a stable released build, I'm not interested in looking at unstable builds and other people's errors. There's nothing here for me to look at anyway, just a random error message that doesn't help.

**Comment by Stevehans** [comment]
I'll update this if anything changes, the maintainer that made the CSettingsManager changes is looking at that
