### ISSUE TITLE
All Addon settings keep getting erased at random.

### ISSUE THREAD

**Issue by LucidEye** [Zomboided/service.vpn.manager#83]
I have been running this addon for about a month now on my Raspberry Pi 2B+ running LibreELEC KODI 17.3.
Can someone please explain why all my VPN settings keep getting erased and reset back to (blank) install defaults.
This happens randomly for no apparent reason at least once a week.
There are no obvious errors in the logs indicating why this is happening.
Really frustrating to have to completely re-setup this addon every few days.
Is there some setting I missed that will prevent this from happening?
Please help.
Thank you.

**Comment by Zomboided** [comment]
This is not related to a setting.
Uninstall the add-on.  Got to /kodi/.storage/userdata/addon_data/service.vpn.manager and delete EVERYTHING in that directory.
Reinstall it from the repo.
Switch on debug https://github.com/Zomboided/service.vpn.manager/wiki/07.-Debug-Options#enable-debug-just-for-vpn-manager
Get a complete log next time you switch on the box and find that it's reset.

**Comment by LucidEye** [comment]
It just happened again... right after setting it up for the first time after reinstalling!!!  Spent 20 minutes adding and validating all my VPN connections... then clicked OK, exited the setup menu... and immediately got the popup telling me there were no validated connections!!!!  WTF?!?!
Where exactly do I find the VPN log file?

**Comment by LucidEye** [comment]
Found it... here is the openvpn.log file...
Fri Jun 16 17:07:11 2017 WARNING: file '/storage/.kodi/addons/service.vpn.manager/IPVanish/pass.txt' is group or others a$
Fri Jun 16 17:07:11 2017 OpenVPN 2.4.0 armv7ve-libreelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [AEAD] built o$
Fri Jun 16 17:07:11 2017 library versions: LibreSSL 2.4.4, LZO 2.09
Fri Jun 16 17:07:11 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]216.151.183.27:443
Fri Jun 16 17:07:11 2017 UDP link local: (not bound)
Fri Jun 16 17:07:11 2017 UDP link remote: [AF_INET]216.151.183.27:443
Fri Jun 16 17:07:11 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prev$
Fri Jun 16 17:07:12 2017 [sjc-a19.ipvanish.com] Peer Connection Initiated with [AF_INET]216.151.183.27:443
Fri Jun 16 17:07:13 2017 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:5 is ignored by previous <connection> blocks
Fri Jun 16 17:07:13 2017 TUN/TAP device tun1 opened
Fri Jun 16 17:07:13 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Fri Jun 16 17:07:13 2017 /sbin/ip link set dev tun1 up mtu 1500
Fri Jun 16 17:07:13 2017 /sbin/ip addr add dev tun1 172.21.22.229/23 broadcast 172.21.23.255
Fri Jun 16 17:07:13 2017 ERROR: Linux route add command failed: external program exited with error status: 2
Fri Jun 16 17:07:13 2017 ERROR: Linux route add command failed: external program exited with error status: 2
Fri Jun 16 17:07:13 2017 Initialization Sequence Completed
Fri Jun 16 17:07:54 2017 [sjc-a19.ipvanish.com] Inactivity timeout (--ping-restart), restarting
Fri Jun 16 17:07:54 2017 SIGUSR1[soft,ping-restart] received, process restarting
Fri Jun 16 17:07:59 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]216.151.183.27:443
Fri Jun 16 17:07:59 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]216.151.183.27:443
Fri Jun 16 17:07:59 2017 UDP link local: (not bound)
Fri Jun 16 17:07:59 2017 UDP link remote: [AF_INET]216.151.183.27:443
Fri Jun 16 17:07:59 2017 [sjc-a19.ipvanish.com] Peer Connection Initiated with [AF_INET]216.151.183.27:443
Fri Jun 16 17:08:00 2017 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:5 is ignored by previous <connection> blocks
Fri Jun 16 17:08:00 2017 Preserving previous TUN/TAP instance: tun1
Fri Jun 16 17:08:00 2017 Initialization Sequence Completed

**Comment by Zomboided** [comment]
That's the openvpn log, I need the kodi log. See the troubleshooting page on the wiki for how to get it

**Comment by Zomboided** [comment]
There's a kodi.old.log too in the same place which would also be helpful to grab as well

**Comment by Zomboided** [comment]
And one more thing, the directory I mentioned in my first reply, get the settings.xml from it once you've set it up and then again when it stops working

**Comment by Zomboided** [comment]
No debug provided, closing

**Comment by peno64** [comment]
I have had this problem also. I installed this addon in the same configuration. Kodi 17, openelec 8 and  after defining 4 connections I suddenly loose all my settings and I have to start again from scratch.

I restored a backup of my card and did a new install with the latest version and hope that the problem will not occur anymore.

But so the reporter is not the only one who has had this problem...

**Comment by Zomboided** [comment]
I did find a problem without this debug being made available.  Please open a new issue if you see it again, with a debug log.

**Comment by peno64** [comment]
I activated debugging and will provide the requested info from this issue in a new issue when it occurs again
