### ISSUE TITLE
verb level setting has no effect

### ISSUE THREAD

**Issue by techionltd** [Zomboided/service.vpn.manager#85]
Tried setting verb level to 5 to diagnose a --ping-restart issue and find no additional info in vpn log.
Manually added 'verb 5' to .ovpn file gave desired output

**Comment by Zomboided** [comment]
What provider?

**Comment by techionltd** [comment]
Using custom config for TigerVPN that was imported using the plugin

**Comment by Zomboided** [comment]
This only happens with ovpn files that have no verb parameter.  I've changed the code to add verb explicitly if it doesn't exist, and will include this in the next release, but meantime this can be worked around by including verb in the ovpn file that you import.
