### ISSUE TITLE
User and pass.

### ISSUE THREAD

**Issue by dhayo** [Zomboided/service.vpn.manager#86]
Hellow! need help how to create username and password. Thanks for response.☺

**Comment by Zomboided** [comment]
You sign up for a VPN service and they give you one

**Comment by dhayo** [comment]
Where is that?
Sorry for slow.😢

**Comment by herrwusel** [comment]
Holy...
https://lmgtfy.com/?q=vpn

**Comment by dhayo** [comment]
Thank you very much for your concern.☺

**Comment by dhayo** [comment]
I dont know hot to register😢
help me please!

**Comment by Zomboided** [comment]
herrwusel is giving you really good advice.  Go and google what a VPN is to determine if you need one, then go look at the many VPN review sites to determine which one is right for you, then go and sign up.  If you pick one that's not supported by this add-on you'll need to set it up yourself.  I cannot spent time doing this for everyone.
