### ISSUE TITLE
Openvpn would not connect

### ISSUE THREAD

**Issue by EG19** [Zomboided/service.vpn.manager#87]
Hi,
I downloaded and set up the VPN Manager addon under Openelec 8. I am having trouble connecting to most VPNs available through my provider (PIA). I managed to connect briefly only once after many attempts, but unable to replicate that.
I am running Openelec on a Raspberry Pi 3 with Berryboot installed. Openelec is one of 4 OSs installed on this specific SD card. Had so far no issues with that.
Here is a Pastebin link for the Kodi Log. I hope it makes sense. The error messages that I see on the screen are included in it towards the end.
Thanks a lot.

[https://pastebin.com/qNkp3wT3](url)

**Comment by Zomboided** [comment]
So PIA is good (I use it personally on LibreELEC) so I'm reasonably
confident that the VPN provider is not the problem.

This : 06:47:13.403 T:1859122080  NOTICE: Thu Jul  6 06:45:57 2017 ERROR:
Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
looks to be the issue.  If you google the error message it appears that
there's some issue on the underlying base OS, either with regards to what's
installed or whether the privileges are appropriately set.

I think your options are either to switch to LE where it'll work fine, or
to try and run openvpn independently of the addon (see the troubleshooting
page on the wiki) and use that to try and debug the issue with the OE
team.  I'd be surprised if other people also aren't having trouble with
openvpn if they've not installed it correctly (my Linux knowledge is weak
so I don't know what needs to be done to fix it).

If you do decide to pursue getting it working on OE, then it'd be really
good if you could post a resolution here then it may benefit others who
will hit the same problem.

**Comment by EG19** [comment]
Alright, I opted for the easy way out, and installed Libreelec.
Openelec wasn’t all that important.
The addon works flawlessly on Libreelec. Thank you!
