### ISSUE TITLE
Digibit VPN

### ISSUE THREAD

**Issue by Ollieclews** [Zomboided/service.vpn.manager#88]
Hello is there any chance that you could add support for the new Digibit VPN? https://digibitdesign.com/vpn/

Thanks!

**Comment by Zomboided** [comment]
They don't make their ovpn files available so it's unlikely.
Someone here has done it using the import wizard though so take that root
if you want to use this VPN
http://community.kodiuk.tv/t/digibit-vpn-raspberry-pi/9227
