### ISSUE TITLE
ProtonVPN support

### ISSUE THREAD

**Issue by phunkular** [Zomboided/service.vpn.manager#89]
Hi there, please would you consider adding support for ProtonVPN

thanks

**Comment by Zomboided** [comment]
openvpn files for this provider are not available, and free account are on a waiting list basis (and will be crap for streaming anyway).  If you want to use them, use the user defined import wizard as documented on the wiki

**Comment by phunkular** [comment]
thanks for your reply. I'm new to VPNs and happened to start with proton so sorry for the silly request and thankyou very much for pointing me in the right direction!
