### ISSUE TITLE
Vpn not working with pvr addons

### ISSUE THREAD

**Issue by estimadarocha** [Zomboided/service.vpn.manager#9]
Hi...

i am using purevpn but my traffic from tvheadend htsp client (pvr addon) is not going throught vpn.

Thanks

**Comment by estimadarocha** [comment]
i have been trying and now its working like 8 in 10 times i try....

**Comment by Zomboided** [comment]
The VPN won't switch in the TV view, it will only switch when you're using an add-on as it needs to detect that an add-on has been opened.  You should use a default VPN and then cycle around the remaining ones when you need to.
