### ISSUE TITLE
Can not get NordVPN to work

### ISSUE THREAD

**Issue by jony0008** [Zomboided/service.vpn.manager#92]
I have tried connecting to NordVPN, both with user provided default TCP and UDP ports and alternative TCP and UDP port but I can't get it to work.

**Comment by Zomboided** [comment]
Go read the trouble shooting page on the wiki. A load of people use Nord and they're able to get it working.

**Comment by Zomboided** [comment]
Reopen with a full debug log if this still is an issue.
