### ISSUE TITLE
Update LimeVPN servers

### ISSUE THREAD

**Issue by JonBenNoah** [Zomboided/service.vpn.manager#94]
Dear Zomboided,

Thank you very much for this excellent software, which I have bee using over the last year.

I would be very grateful if you could update the servers for LimeVPN. There have been many changes over the last year. I attach the OpenVPN configuration files, which I download from their site. It is also available at:
http://www.limevpn.com/downloads/OpenVPN-Config.zip

With Best Wishes,

Jon Griver

[OpenVPN-Config.zip](https://github.com/Zomboided/service.vpn.manager/files/1211270/OpenVPN-Config.zip)

**Comment by Zomboided** [comment]
Thanks for mentioning that it's changed.  It looks like they no longer use
keys and certs.  Can you confirm that?  Do you have user specific config
files that you can download from within your account, or are they just
using what you've pointed me at now?

**Comment by JonBenNoah** [comment]
Thanks for your quick reply. I'm not sure what you mean by keys and certs. There is no need to download any further config files and I get the vpn to work in linux just using these files.

**Comment by Zomboided** [comment]
Ok, thanks, that's what I needed to know.

**Comment by JonBenNoah** [comment]
For your information, I got the VPN working, editing manually and setting up one of the servers in "UserDefined". No problem, except that it took me a while to realize I have to clear the "Manage key password" switch.

**Comment by Zomboided** [comment]
I've updated LimeVPN.  If you move to use LimeVPN natively rather than
UserDefined, it shoudl download the the new settings.  Let me know if it
doesn't work.

**Comment by JonBenNoah** [comment]
Thanks. I've downloaded the settings. I see that each server has a TCP option and a UDP option. I've tried several servers and for all of them the UDP option works well, but the TCP option does not. The log gives the warning "No server certification method has been enabled", and then "Connection refused". If you need the log, please tell me where it is, and I'll send it to you.

**Comment by Zomboided** [comment]
Can you find any openvpn files that use TCP?  They say that they support
TCP so there shoudl be some somewhere

**Comment by JonBenNoah** [comment]
No, I tried all the servers. None work with TCP. No problem for me, it's fine as it is. Thanks again.
