### ISSUE TITLE
Playback stops when vpn disconnects

### ISSUE THREAD

**Issue by allYourKeysBelongToUs** [Zomboided/service.vpn.manager#95]
I don't know if this is intentional, but playback abruptly stops when the VPN disconnects. If this is intentional, could we have an option to turn this feature off? I play content locally as opposed to streaming to it's a nuisance for me.

```
# Stop any media playing before switching VPNs around   
if player.isPlaying(): player.stop()
```

**Comment by Zomboided** [comment]
Yeah, a break in connection will cause this, nothing to do with the addon and nothing I can do about it.

You can work out why your VPN is so flakey. I basically get no outages with mine. Or you can turn the VPN off when you're using local media. Depending on how you've setup your library this may or may not be possible. Instructions for filtering are on the wiki

**Comment by Zomboided** [comment]
I might be changing my mind about this.  See this post
https://forum.libreelec.tv/thread/5032-vpn-manager-for-openvpn/?postID=63096#post63096
Feel free to try this and post up your results here or in the forum.

**Comment by Zomboided** [comment]
4.1.6 fixes this.  Streaming playback will still stop, but you can turn this off if you don't like this behaviour in the monitor tab
