### ISSUE TITLE
Ivacy 

### ISSUE THREAD

**Issue by slappy2** [Zomboided/service.vpn.manager#96]
1. I have Ivacy VPN added as User Defined and working find but I would like to introduce it in the available VPN Providers list. I copied the folder and rename it to Ivacy with the rest of the Providers but it is not sufficient. Ivacy is still not showing in the list.

2. Is there a way to enable a kill switch in case of VPN failure or disconnect ?

**Comment by Zomboided** [comment]
I'm not adding more providers, especially crappy ones like Ivacy.
You can use up/down scripts to modify the ip table to create a kill switch.  I don't know what commands you'll need to run in your environment, you'll have to google it.
