### ISSUE TITLE
Failing to connect (inactivity timeout)

### ISSUE THREAD

**Issue by siamesedlphn** [Zomboided/service.vpn.manager#97]
Hi,

Having followed the instructions and information in the wiki, I'm not sure what could be going wrong here. The most peculiar being that VPNs connect when calling the VPN Unlimited ovpn files directly [with openvpn via ssh].

However, running the same VPN (ovpn file) within VPN Manager appears to fail - with "inactivity timeout".

I usually like to investigate, diagnose and fix problems myself... but nobody seems to be referring to the same anywhere!

kodi_17-08-14_12-12-14.log
[https://pastebin.com/bmqvFAWs]

Many thanks!
siamesedlphn

**Comment by siamesedlphn** [comment]
A little wary to change any default settings, I changed UDP to TCP and the VPN connected! I'll leave the issue open to allow comment (if that's OK).

**Comment by Zomboided** [comment]
Can you paste up one of the UDP files you see in
/storage/.kodi/addons/service.vpn.manager/VPNUnlimited?
If you're on OSMC, the /storage/.kodi part of the path may be different.

**Comment by Zomboided** [comment]
Changed port to 1194 for UDP, pick up the update and try it.  If you still see problems then you'll need to get the openvpn files from VPN Unlimited as per step 1 here
https://www.vpnunlimitedapp.com/en/info/manuals/dd-wrt-openvpn-configuration-guide
and share them with me.
