### ISSUE TITLE
Option to append log

### ISSUE THREAD

**Issue by techionltd** [Zomboided/service.vpn.manager#99]
Trying to diagnose a VPN issue, however this is proving more difficult as disconnect/reconnects overwrite the previous log. 
If not already implemented, could this possibly be configured for a future release, possibly with a further option to constrain file size/number of lines to prevent huge log files consuming space

**Comment by Zomboided** [comment]
Switch debug on and it'll output the log to the kodi log when it finds that the connection has been lost.  Turn debug off and it'll not do this.
The openvpn log is cleared on reconnection and is used to determine connectivity so I'm not gonna mess with that.
